### ISSUE TITLE
Catalog API versus rsync/mirroring

### ISSUE THREAD

**Issue by tombh** [radiantearth/stac-spec#10]
I'm not sure if this is the best place to bring this up. Perhaps the mailing list would be better?

Whilst we're in the preliminary stages here, I just thought it might be good to at least briefly explore other approaches to the same goal, namely;

>increase interoperability, enabling more catalog clients and cross-catalog searching

In essence: what if only imagery was standardised?

This would mean that catalogs were able to easily ingest imagery from multiple sources, but were free to implement any form of search interface. Of course it would indeed be ideal to have standardised APIs as well, but does that extra effort reflect the extra value achieved? For example, if `rsync` and a standardised imagery specification were made the only requirements, the primary goal of cross-catalog searching would still be made possible by pointing your client to the catalog that archived the sources you were interested in. The only drawback I see is the headache to the client users who must write extra code *if* a single catalog didn't meet their requirements. This seems like a smaller thing than expecting multiple catalog owners to implement and conform to a single canonical API.

Whatever approach is taken, at some point I can foresee that someone will be able to create a catalog that archives everything! After all, they only need to store small JSON objects, not imagery, so the running costs will be trivial. So what if instead of standardising on an API, we just come together to maintain a single catalog implementation?

**Comment by cholmes** [comment]
Closing this, sorry for never responding. But I think the 'static catalogs' come closer to this I think.
