### ISSUE TITLE
Auto-merge non-controversial PRs

### ISSUE THREAD

**Issue by jisantuc** [radiantearth/stac-spec#1007]
This issue is to configure automatically merging PRs based on some conditions. The goal is to avoid review wrangling for extremely non-controversial PRs.

These PRs include things like PRing in a new vendor extension (adding a row to a table that points to another repo), though there may be other conditions that should apply as well. @cholmes, you normally do the legwork of chasing down reviewers -- are there other conditions you think might be sensible here?

I'm proposing:

- separate vendor extensions into a new file
- combine [checks conditions](https://docs.mergify.io/examples.html#automatic-merge-when-ci-works-and-approving-reviews) and [file changed conditions](https://docs.mergify.io/examples.html#merging-based-on-modified-files) to see whether the file can be automatically merged
- 🏎

**Comment by m-mohr** [comment]
I don't think I agree with the proposed behavior. Moving the vendor extension list to a less visible place for the sake of auto-merge seems wrong. At least I like having all extensions under each other, especially now that we move some out of the repo and then they'll be part of "vendor", too. Then you have EO and SAR in different places.

Also, what does auto-merge actually mean? Keeping some control over PRs would be great (i.e. someone from the team needs to merge; "auto" indicates all PRs are merged automatically.)

**Comment by jisantuc** [comment]
auto-merge means that a bot merges the PR if it matches some conditions that we can choose. Right now, we've (accidentally, silently) made a choice that it's @cholmes's job to recruit people for reviews for things that are languishing. That makes sense for some things like #955 and #989, where there are substantive changes to talk about. It makes less sense for things like #1005. The automatic merge would apply only to PRs like #1005.

**Comment by m-mohr** [comment]
Is this still important now that we moved out all extensions? It seems that there are only some edge cases like the CHANGELOG left, but other than that I guess having reviews for a stable spec is a good idea.

**Comment by jisantuc** [comment]
I agree -- I'll close
