### ISSUE TITLE
Instrument GSD lacks units

### ISSUE THREAD

**Issue by jlaura** [radiantearth/stac-spec#1015]
This is tangentially related to #1014. The ground sample distance (gsd) entry in unitless. I suspect for Earth focused observations one assumes that the unit is meters? For many planetary missions (Moon, Mars, etc.) we could infer the unit from the mission name. Unfortunately, this is not universally true as the highly elliptical orbits of some outer planets result in observation sets where the GSD (or mean gsd over the observation) can vary between tens of kilometers to tens of meters. 

I am wondering if it would make sense to either explicitly define the GSD as being meters (and if I missed this I apologize!) or to make the GSD an object and include the unit of the numeric.

**Comment by cholmes** [comment]
Hrm, that's definitely an oversight if we don't define that it's in meters. I'll check, and even if we do it sounds like we need to make it more clear. 

In general we try to not use objects so much, but I could see a gsd_units field, where units is defined. That one too I think probably makes sense to at least start in a 'planetary extension' (feel free to make a better name than that), and I think we could have the extension be able to redefine the units (and could put a mention in the GSD field of the main spec that the default is meters, but that extensions can over ride that or something).

**Comment by m-mohr** [comment]
It's defined in meters:

> gsd is the nominal Ground Sample Distance for the data, as measured in meters on the ground.

It's just not in the table, it's in the long description below. I agree that it is a good idea to add the unit to the table.

**Comment by m-mohr** [comment]
See PR #1016
