### ISSUE TITLE
Add more info on sizes / formats for thumbnail, overview and visual

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#1017]
I thought we agreed on having a chapter that defines recommended sizes and formats for thumbnail, overview and visual? maybe don't say a lot in the table and add a link there to this chapter while extending this chapter with recommendations about thumbnails, overviews etc. in general?

_Originally posted by @m-mohr in https://github.com/radiantearth/stac-spec/pull/989#discussion_r581923245_

**Comment by cholmes** [comment]
I forgot our recommendations - did a bit on thumbnail, but didn't get a chance to do more. Matt, if you can come up with the recommendations I'm happy to make the PR, or you just can.

**Comment by m-mohr** [comment]
Trying to remember... was it:

- thumbnail: <600x600, png/jpeg/webp, rgb
- overview: full res, png/jpeg/webp, rgb
- visual: full res, any file format (cog preferred), rgb
- (data, full res, any file format, all bands/bands per file)

@matthewhanson ?

**Comment by emmanuelmathot** [comment]
@m-mohr , I do not see the difference between overview and visual in your list except the format. IMO overview is a high definition browse image of the dataset, something that can be easily displayed on a map without tiling (e.g. overlay, kml). visual is the full res and thus often requires to have tiled images (recommended cog).

**Comment by m-mohr** [comment]
Yes, indeed, there's not much difference. It's just what I recall from a discussion, not necessarily a proposal from my side. We can figure out the file types from the `type` as well, so if we can't find a good enough difference, we should drop one of the roles again.

**Comment by cholmes** [comment]
I think there's decent value in 'overview', and like the use case you're suggesting @emmanuelmathot
