### ISSUE TITLE
Instrument Extension Mission as Array?

### ISSUE THREAD

**Issue by jlaura** [radiantearth/stac-spec#1029]
Another planetary question for everyone. 

We have some mosaics of Europa (I can hopefully share a link sometime soon). The mosaics are made from data collected by Voyager I, Voyager II, and Galileo.

The instrument spec defines the mission as a string. Right now, I have a STAC file that defines the missions as: `"Voyager I, Voyager II, Galileo"`. The instrument extension as an array of values. Does it make sense to also allow the mission to be an array of strings?

This is an issue for us planetary folks only when we are building mosaics (that we would like to share with STAC metadata) that use multiple instruments that flew on different missions. One other example would be HiRISE / MOLA DEMs.

**Comment by m-mohr** [comment]
For mosaics, you'd just not specify the missions as the data are basically newly computed values from different sources IMHO. I think the instruments extension is meant to list the metadata for the source. In STAC, you'd link to the source data, which then lists the missions for each of the sources. If you'd want to list all things that went into a mosaic, I guess you'd best define a mosaic extension, which defines those semantics (i.e. "the missions the data is composed from"). Mosaics came up quite often in the past, but no one took the effort yet to write an extension for it.

**Comment by m-mohr** [comment]
You could also use the themes extension.
