### ISSUE TITLE
Difference between "assets" and "item_assets" properties

### ISSUE THREAD

**Issue by l0b0** [radiantearth/stac-spec#1044]
What is the semantic difference between these two in a collection? The [collection spec](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md) documents `assets` as

> Dictionary of asset objects that can be downloaded, each with a unique key.

[Item assets](https://github.com/stac-extensions/item-assets) look very similar, and I'm not sure which one I'm meant to be using. I'm a software developer completely new to geospatial dataset jargon.

**Comment by m-mohr** [comment]
The main distinction is that "Item Assets Definition" can't define an href and they basically give an overview over what assets a STAC Item contains. It is a bit like a schema for the assets in items.

Collection assets are collection-level assets that are not specific to an Item. E.g. a collection-wide preview, collection-wide metadata or processing details that have been used across all collection etc. It doesn't make much sense to repeat them in all Items.
