### ISSUE TITLE
Prevent empty strings for required fields

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1048]
Several string fields are required, e.g. "id" in item or "description" in Collections. 
Although those fields are required, they can be provided as empty strings. 
Should we enforce a minimum length of 1 in JSON Schemas for required strings?

**Comment by cholmes** [comment]
I'm +1 on this.

**Comment by m-mohr** [comment]
- [x] Core
- [ ] mgrs
- [ ] datacube
- [ ] storage
- [ ] pointcloud
- [ ] label
- [ ] version
- [ ] sar
