### ISSUE TITLE
When, if ever, json5?

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-spec#1055]
Not meant as a near term item, as I think support for json5 is current rare. 

```json5
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```

No Earth shattering changes - just some easing of some of the sharper edges.

The biggest item for me is probably the ability to have comments.  The trailing comma does also make json generation easier for many systems that are not directly using a json library to write STAC json.

From https://json5.org/

*Summary of Features* 

The following ECMAScript 5.1 features, which are not supported in JSON, have been extended to JSON5.

* Objects
  - Object keys may be an ECMAScript 5.1 IdentifierName.
  - Objects may have a single trailing comma.
* Arrays
  - Arrays may have a single trailing comma.
* Strings
  - Strings may be single quoted.
  - Strings may span multiple lines by escaping new line characters.
  - Strings may include character escapes.
* Numbers
  - Numbers may be hexadecimal.
  - Numbers may have a leading or trailing decimal point.
  - Numbers may be IEEE 754 positive infinity, negative infinity, and NaN.
  - Numbers may begin with an explicit plus sign.
* Comments
  - Single and multi-line comments are allowed.
* White Space
  - Additional white space characters are allowed.

**Comment by m-mohr** [comment]
We basically inherit the JSON foundation from both OGC APIs and GeoJSON, so I think the answer is: Once they've adopted it. This will likely not be anytime soon (or never?) so I'm closing this to not have the issue floating around forever.

(I also face limitations with JSON, especially due to missing representations for NaN, infinite, etc., but support for JSON5 is also still quite weak, unfortunately.)

**Comment by schwehr** [comment]
Thanks for responding.  I was expecting something along those lines and my aim was mostly to document the situation.
