### ISSUE TITLE
mgrs grid extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#1057]
Sentinel data uses the MGRS grid, as does HLS, likely others. Derived products from these are likely to use the MGRS grid as well. 

Created repo https://github.com/stac-extensions/mgrs and will fill it in.  Three fields:

mgrs:utm_zone
mgrs:latitude_band
mgrs:grid_square

**Comment by matthewhanson** [comment]
Two other things: 

- This can also be used to assign data to an MGRS grid based on the closest centroid, the data doesn't have to be a full tile in the grid. This way you can make a browsable catalog based on location first, then by time.

- in the polar regions, `mgrs:utm_zone` is omitted, `mgrs:latitude_band` is A, B, X, or Z instead, and there is still a grid_square, just a reduced set of letters are used.

https://en.wikipedia.org/wiki/Military_Grid_Reference_System#Polar_regions

**Comment by matthewhanson** [comment]
Proposed extension up and ready for review: https://github.com/stac-extensions/mgrs

**Comment by alexgleith** [comment]
What do you think about having some kind of generic grid field?

In ODC we have `odc:grid_code`, which fits things like the MGRS code or Landsat's pathrow.

It would be awesome if there was one agreed name for a consistent footprint across STAC.

**Comment by philvarner** [comment]
@alexgleith Creating that here: https://github.com/stac-extensions/grid (might still be private)

**Comment by m-mohr** [comment]
Seems solved with two new extensions, great :-)
