### ISSUE TITLE
Collectionless item has collection field & link

### ISSUE THREAD

**Issue by duckontheweb** [radiantearth/stac-spec#1081]
The [`collectionless-item.json`](https://github.com/radiantearth/stac-spec/blob/v1.0.0-rc.2/examples/collectionless-item.json) example has a value for the `collection` field as well as a link to a collection. It's possible I'm misunderstanding the purpose of that example, but I was expecting it to be missing those fields, should that be the case?

**Comment by m-mohr** [comment]
See PR #1089
