### ISSUE TITLE
Object keys should be marked as unique in spec

### ISSUE THREAD

**Issue by l0b0** [radiantearth/stac-spec#1083]
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields mentions that `assets` is a

> Dictionary of asset objects that can be downloaded, each with a unique key.

Is that uniqueness constraint actually enforced by STAC? I can't seem to find any `uniqueItems` properties near the assets definition, but I'm a JSON schema newbie.

**Comment by m-mohr** [comment]
uniqueItems is for arrays, there's no equivalent for objects, I think.

Also, the spec talks about keys only, not unique objects. While I think the uniqueness is not part of the JSON spec, none of the JSON implementations I'm aware of supports multiple keys with the same name, including JSON Schema?!
