### ISSUE TITLE
Thumbnails outside of assets as links / Thumbnails for catalogs/collections

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1090]
It could be nice to also support some kind of thumbnails in catalogs. While we can provide thumbnails in collections and items through the assets, we could also align with OGC API Features and specify that thumbnails can also be specified as links with rel type preview in general so that they can be used in all STAC objects.

For context see https://github.com/opengeospatial/ogcapi-records/issues/94#issuecomment-822509010

**Comment by cholmes** [comment]
Sounds reasonable to me.
