### ISSUE TITLE
Best practice when root == parent?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1098]
When doing some examples, I was wondering what the best practice is for STAC entities for which the parent and the root catalog are the same (i.e. childs of the root). Should we have links with:
1. parent and root defined?
2. only root defined?

**Comment by matthewhanson** [comment]
+1 on both

**Comment by cholmes** [comment]
I'll do a PR to update the examples to always have both.

Not sure if we need to actually say this anywhere? I lean towards no, but happy to add something in.

**Comment by m-mohr** [comment]
I would mention it somewhere, at least it was something I was not sure about. Could be BP though.
