### ISSUE TITLE
Rephrase summaries requirement

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1106]
From Gitter:

@fredliporace wrote:

> Checking the use of summaries. The spec states "Summaries should summarize all values in every Item underneath the collection, including in any nested sub-Catalogs.". If 'all values' is to be interpreted as a requirement this increases significantly the implementation work. For CBERS case I consider that the only field that would be interesting (and easy) to include in summaries is the GSD for the CB4A/WPM camera, which has assets with 2m and 8m.

My response:

> It seems we need a PR to rephrase this.
> This was meant to say that for the fields you decide to add to summaries, you should list all potential values from all items underneath for that specific field.

**Comment by fredliporace** [comment]
@m-mohr I can work on this PR.

**Comment by m-mohr** [comment]
That would be great, @fredliporace ! Thanks.
