### ISSUE TITLE
sat-api implementation status and lessons learned

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#111]
I've got a new version of sat-api up and running at http://sat-api.developmentseed.org which includes Landsat-8 and Sentinel-2 data on AWS.  Not all the records are ingested yet, but by tomorrow night it should contain all of the landsat-8 and sentinel-2 data, around 5.5 million scenes.

sat-api a partial implementation of STAC 0.4.1 and includes the EO and Collections extensions.  Below are notes on my specific sat-api implementation, as well as questions and issues that came up about the STAC spec. Of particular note is the section on Collections below, which details how the search is able to search items by using metadata from both it and the collections they are part of.

If you don't have a JSON viewer browser plugin I suggest you install one, it will format the JSON to be readabale and will automatically make links from URLs.

### sat-api endpoints

There is no documenation endpoint ATM (I could use suggestions or help with how best to creaate that), but there are two endpoints, one for collections and one for items. `items` and `collections` have a collection property which is the name of the collection, and `items` also have a link in the links section to the collection. 

[/collections](https://sat-api.developmentseed.org/collections?limit=2): Can search on any field in the collection, e.g. https://sat-api.developmentseed.org/collections?collection=landsat-8
[/search/stac](https://sat-api.developmentseed.org/search/stac): Can search on any field that appears in `Items` *or* the `Collections` those items link to. More on that below.

It's a little weird because both endpoints are search endpoints.  /search/stac was to be compliant with WFS3, but /items here would make more sense or an equivalent /search endpoint for collections.

### Departures from STAC spec
Here is a list of things that are different between the sat-api implemenation and the STAC spec.

- Not yet implemented bbox for searching. However, it does accept the more useful 'intersects' term for searches based on polygons
- 'collection_name' is now just 'collection'
- No more CRS field, instead there is an 'eo:epsg' field. It is currently ommitted from Landsat, but is included for Sentinel
- datetime field, not 'time' (some parts of the spec I think still refer to just 'time')
- ISO 8601 is not implemented for date searches, so period strings are not accepted, however single datetimes, partial or full, work, as do date ranges specified with a slash, e.g., 2017-08-01/2017-08-31
- The spec does not currently have specifics on how ranges should be specified for other fields. For now I used the slash notation, but think the spec should specify using separate gt and lt filters.  e.g. eo:cloud_cover=0/20 for cloud cover between 0 and 20% 
- The assets are currently barebones, I did not add additional fields such as descriptions, filetype, etc.

Not all fields are included for both landsat and sentinel. Landsat does not have an eo:epsg code, sentinel does not have viewing azimuth (eo:azimuth) or sun angle information (eo:sun_azimuth, eo:sun_elevation)

### Links
Assets use a dictionary structure with a key. It feels like links should follow the same structure and instead of a 'rel' field, make it a key, e.g.

```
links = {
    "self": {"href": ...url...}
}
```

Also I couldn't decide whether or not provider supplied metadata files were an asset or a link. I currently made them assets (under the metadata key), but it might make more sense as a link.

### Collections
The most challenging aspect of the API ended up being handling the concept of collections as presented in the Collections extension. Collections can include any abitrary fields that were part of an item, and that would apply to all STAC `items` in that collection (specified through the **collection** field). So, for landsat-8 we can specify eo:platform as "landsat-8" and it applies to all items in the landsat-8 collection.

The challenge was how to implement this using elasticsearch, because you don't actually know what fields are in the `item` and which are in the `collection` (stored in two different indices in elasticsearch).  If the field is present in one it will be missing in the other, and by default missing fields do not match. So if you search `items` for eo:platform and that field is in an items collection, it will not be matched.  

So instead /search/stac takes a two step approach and in each it allows for missing fields.

1 - Search the collections index, but allow for either a match *or* a missing field. This ends up returning all collections for which each of the search fields is either a match or the field is missing. The exception to this is geometry. The geometry search in elasticsearch is a bit more complicated so for now I removed it when searching collections. So at this time, sat-api does not support geometry in collections, only items.

2 - With the list of matched collections, add these to the `item` search. Therefore any matched collection will now return all items that are part of it, further filtered by the additional fields. Again, a missing field is considered a match, because it is presumed to have been in the collection.

Overall this approach works well, however allowing missing fields to match does create a side effect which is both a feature and a bug. The issue comes in when a search field is missing from both the `collection` and the `item`, because this will stil return a match.

- On one hand this is a feature, because it allows you to search on terms only in one collection and have that filter only apply to items in that collection.  For example we can search for landsat and sentinel imagery in an area and daterange, but also further filter landsat based on path or row (e.g., landsat:row, landsat:path) and filter sentinel also based on the MGRS grid designation. Note that I currently do not have collection-specific metadata in sat-api, but will add them as they are found useful

- On the other hand this is a bug as you can search for non-existent terms by accident, for example searching for cloud_cover=0/10 instead of eo:cloud_cover=0/10. This may lead a user to think they are getting mostly cloud free imagery when they are not due to a typo. 

The benefits outweigh the problem I think, and we could fix the problem other ways by validating search terms against the spec.  Also, this approach still works fine when an item has no collection, since those `items` will have a missing collection field.

Please feel free to test out sat-api and point out any problems, or jump into the repo and take a look at open tickets if you want to contribute!
https://github.com/sat-utils/sat-api

**Comment by m-mohr** [comment]
Regarding links:
* I think the structure originates from the REST/Hypermedia principles and is somehow standardized in the HTTP specification (e.g. RFC 2068, chapter 19.6.2.4). It's also how it is used in XML/HTML (<link rel="" href="" />). What you suggest sounds much like [HAL](http://stateless.co/hal_specification.html). Whatever is chosen, it should be consistent across the whole spec.
* I had the same confusion about the meta data references: links or assets? @hgs-msmith once suggested me in the chat to add them to the assets.

Regarding endpoints:
* I agree that the endpoints are somehow inconsistently named and I must say that I really don't like the WFS-like naming of `/search/stac`. It just doesn't feel right in resource-oriented REST interfaces. I'd also expect it at `/collections` and `/items` (or similar names). If you'd follow REST you'd have to remove `/stac completely`. Content negotiation with aan Accept header would be the correct way to get a STAC response, I think.

**Comment by cholmes** [comment]
Awesome work Matt. Thanks for getting real world implementation and helping evolve the spec. Psyched for the next iterations.

Regarding links:

* For links, yeah, consistency across links and assets makes sense. Wish we'd thought of that at the last revision. And yes, I agree with @hgs-msmith that metadata should go in assets. I see assets are the things that a user would likely want to download, and links describing relationships with other online entities. I can see how the line is blurry, and I could see if there's a great html metadata that you don't download then using a like rel=describedBy could make good sense. But I feel like most imagery still has metadata as xml or text files.

Regarding endpoints:
* I don't love the STAC in the resource either. But I do think we should make something that is compatible with WFS. I'm not sure if /search/stac is the best way - that was a request from the WFS people, but they don't have a clear search endpoint.

Though I'm not sure I understand https://sat-api.developmentseed.org/collections?collection=landsat-8 - seems like it should be https://sat-api.developmentseed.org/collections/landsat-8 And then https://sat-api.developmentseed.org/collections/landsat-8/items which enables basic single collection search. The idea with the /search endpoint is that it allows cross collection search. Those resources make sense to me a /search endpoint to do more complex searches, and individual collections under collections/{collection-name}/

Regarding CRS

* Would be good to get the CRS field changed asap, I found myself not using it, and doing epsg. Maybe make an issue or PR on that specifically?

Regarding ranges:

* I'm +1 on specifying these more, have no real opinions though.

**Comment by m-mohr** [comment]
What's the state of this issue?
