### ISSUE TITLE
Clarify Catalog and Collection extension use cases

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#1120]
As described in the Gitter conversation [starting here](https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=609098d0f7e4221825b69a23), some clarification is needed around when a Collection should list an extension in it's `stac_extensions`. This will require updating the language of the core spec, probably in the `extensions/README.md`, as well as changes to the [stac-extensions](https://github.com/stac-extensions) repos.

Extensions should be listed in a Collection if:
- Any of the extension properties are listed in the 'summaries' list of that Catalog or Collection
- There is an extension to the Collection that brings in information specific to that extension; for example, if a Collection implements the [item-assets](https://github.com/stac-extensions/item-assets) extension and the Asset definitions have extension properties.
- Any of the Collection's `assets` entries have properties of that extension.

With #1122 Catalogs dropped summaries (again), so we won't need to mention Catalogs as part of these specific scenarios. However, we should add language that if a future extension extends Catalogs, and if part of that extension is bringing in other extension properties from child Collections or Items, that the Catalog should then list that second extension in the stac_extensions.

**Comment by m-mohr** [comment]
Once #1122 is merged, you can ignore Catalogs mostly. ;-)

**Comment by lossyrob** [comment]
Updated description to account for #1122
