### ISSUE TITLE
Backport attribution from OGC APIs to a STAC extension

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1126]
OGC API has a field "attribution" in the landing page and in collections. While it may not be very useful for us in the landing page, it feels useful to have it in Collections somehow. As I don't want to merge it into core, I think we could make this an extension.

The issue in OGC API - Common: https://github.com/opengeospatial/ogcapi-common/issues/174

**Comment by duckontheweb** [comment]
This seems like it has the potential to overlap with the scope of the Scientific Extension, at least at the Collection level...

> This extension adds the ability to indicate from which publication data originates and **how the data itself should be cited or referenced.**

If this becomes its own extensions, should there be either a restriction or a best practice that `attribution` and `sci:citation` must match for Collections?

**Comment by m-mohr** [comment]
Scientific citations (usually in scientific publications) and attributions (usually in maps) are pretty different.

For example, the OSM attribution in Leaflet is simply 
> (c) OpenStreetMap contributors

On the other hand, the scientific citation would be more like 
> OpenStreetMap contributors. (2017). Planet dump retrieved from https://planet.osm.org . https://www.openstreetmap.org .

**Comment by PowerChell** [comment]
To discuss and potentially close at the Sprint.

**Comment by PowerChell** [comment]
Discussed and agreed to be put in the core.

**Comment by m-mohr** [comment]
We discussed it again due to discussions in #1278. The mixture of CommonMark and HTML is an issue. We should test and evolve this in an extension.

**Comment by m-mohr** [comment]
Done (funded by EOX): https://github.com/stac-extensions/attribution
