### ISSUE TITLE
Recommendation to add titles to links?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1132]
While re-implementing STAC Browser, it more and more often occurs to me that missing titles lead to a bad user experience. 
For example, I'd like to show a "breadcrumb" and want to show the title or root catalog and parent without actually loading up those files, I'd need titles for those links as otherwise, I need to show something generic that is later replaced with the actual titles once the file has been loaded.
As most of these catalogs have titles anyway, it should be easy enough to list them in the links, right? So I'm thinking whether we should recommend adding titles to links such as item, child, root, and parent.

**Comment by cholmes** [comment]
I'm definitely into it, see https://github.com/stac-utils/stactools/issues/22 where I wanted it to be an option for STAC Tools. 

I don't know that this clears the bar for me as worth resetting our 1.0.0 counter with another release candidate. I guess if we put it in best practice then maybe it doesn't need a new release candidate? 

I'd also be in favor of making it the default in pystac, and we can recommend it in the api spec. And then put it as a PR for a 1.0.1 release (do be done when there's a few good issues to get in).

**Comment by m-mohr** [comment]
I don't think such a recommendation would need a reset of the 1.0.0 counter as it's just a best practice, similarly to the other issues in https://github.com/radiantearth/stac-spec/milestone/23, which we may integrate but likely won't reset the counter.

**Comment by cholmes** [comment]
Cool, I think the main thing to me is to not touch the actual spec documents (though I suppose I'm open to it). Putting it in best practice sounds good. And also updating all examples to reflect it also would be good.
