### ISSUE TITLE
New Extension: Solar System Extension (SSYS)

### ISSUE THREAD

**Issue by thareUSGS** [radiantearth/stac-spec#1143]
Please find a prototype STAC Solar System (SSYS) Extension. 
https://github.com/thareUSGS/ssys

SSYS covers data sets that represents an individual image, mosaic, or derived raster of a planetary body. Examples of SSYS data include sensors with visible, short-wave and mid-wave IR bands (e.g., the THEMIS instrument on Mars Odyssey), visible images (e.g. Context Camera (CTX) aboard Mars Global Surveyor), or derived data sets like digital elevation models (DEM/DTM).

Greatly simplified from our first attempt, this initial proposed version only adds two new items such that one can provide a list of targets (e.g. Mars, Moon, Ganymede, or even Earth). Generally this will only include one **target**, but there are times where multiple targets are within a single image.

Links to Jpeg ang COG cloud resources, as provided in the example, are currently "now" available.  For context, this Europa STAC catalog will be using data from this public release: https://astrogeology.usgs.gov/search/map/Europa/Mosaic/Equirectangular_Mosaics_of_Europa_v3

Recent abstract: https://www.hou.usra.edu/meetings/planetdata2021/pdf/7023.pdf from
from forthcoming the 5th Planetary Data Workshop meeting: https://www.hou.usra.edu/meetings/planetdata2021/

lightening talk: https://www.youtube.com/watch?v=cOMkgQssVPk&list=PL3QzFgBMGnbQWbW-V09AzSfCbnf6Q87Rq&index=5
from: https://medium.com/radiant-earth-insights/cloud-native-geospatial-outreach-day-recap-9b873ce3788e

**Comment by thareUSGS** [comment]
Updated with working public examples (thanks to @jlaura):
https://github.com/thareUSGS/ssys

Given the minimal additions of <targets> and <target>, please let us know what the next steps might be. We now have 3 working examples for Europa, Mars, and the Moon. New address name is being approved, but if you want a early peak please email (thare@usgs.gov).

**Comment by jlaura** [comment]
@thareUSGS In order to be compliant with current tools, I have omitted the ssys extension in the examples that are posted publicly. I am very happy to send along a sample or add to one of our existing catalogs. I was nervous that having a spurious extension floating around might be problematic.

I am really excited to use our stac-api service and be able to query based on body (as opposed to knowing the collection id).

**Comment by thareUSGS** [comment]
@jlaura thanks for the ping. I have updated to actually use ssys schema in the "item.json" example now. I left it out in yesterday's shuffle. https://github.com/thareUSGS/ssys

Question: I actually starting updating the scope for "ssys" beyond "item" and into catalog and collection. I have removed the use beyond item for now, but should we expand the scope for using ssys:targets within "catalog" and "collection"?

**Comment by matthewhanson** [comment]
I think the next step now is to make a release for the ssys extension. Right now the schema points to the "main" branch, but you'll want a permanent published link so I'd recommend publish a v1.0.0 version, update the examples and extension links to point to the new location, and create a v1.0.0 tag (this will happen automatically when you create a release).

Actually....you used the extension template, so this should all be automatic if you just create a release (still need to update all the links within the files) it will create a tag and publish it to github pages.   Let me know if you need a hand with any of this.

**Comment by thareUSGS** [comment]
minor updates and released pulled:
https://github.com/thareUSGS/ssys/releases/tag/1.0.0

**Comment by AndrewAnnex** [comment]
@matthewhanson working with @thareUSGS on this, looking at https://stac-extensions.github.io/ it appears this extension is now public, are there any changes needed? The website doesn't list the field name prefix so maybe a patch is needed?
