### ISSUE TITLE
BBOX definition

### ISSUE THREAD

**Issue by mrepse** [radiantearth/stac-spec#1154]
I have a short question regarding STAC metadata. What exactly is the definition of the BBOX field (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields) assuming the footprint is known? There are two ways of interpreting the text and we aren't sure what exactly is meant here.

1. stac bbox = bbox(stac geometry)
2. stac bbox = bbox(tiff file bbox reprojected to wgs84)

2 is always larger than (or equal to) 1. Would appreciate some clarification.

thanks

**Comment by PowerChell** [comment]
Closing due to updated language in item-spec bbox definition
