### ISSUE TITLE
[extension: scientific/citation] support BibTex-like fields

### ISSUE THREAD

**Issue by fmigneault** [radiantearth/stac-spec#1155]
In the scientific community, it is widely spread that citations are defined using BibTex for easy referencing in article bibliographies, such as: 

```bibtex
@techreport{landry2019ogc,
  title={OGC Earth System Grid Federation (ESGF) Compute Challenge Engineering Report},
  author={Landry, Tom and Byrns, David and Caron, David and Charette-Migneault, Francis},
  year={2019},
  institution={Open Geospatial Consortium}
}
```

I believe STAC would benefit in supporting fields defined in BibTex to facilitate citation definition. 
The current `citation` field only provide a string that could be formatted with any of the many citation styles (MLA, APA, Chicago, etc.). 

The above example could be converted into STAC-citation JSON as such: 

```json
{
    "citation": "Landry, Tom, et al. OGC Earth System Grid Federation (ESGF) Compute Challenge Engineering Report. No. DOE-OGC-19082. Open Geospatial Consortium, 2019.",
    "doe": "https://www.osti.gov/biblio/1570389",
    "type": "techreport",
    "title": "OGC Earth System Grid Federation (ESGF) Compute Challenge Engineering Report",
    "author": "Landry, Tom and Byrns, David and Caron, David and Charette-Migneault, Francis",
    "year": 2019
}
```

**Comment by m-mohr** [comment]
Hey, 

thanks for your thoughts. Would you mind transferring this issue to the corresponding repository?
https://github.com/stac-extensions/scientific
