### ISSUE TITLE
GeometryCollection not allowed according to Item schema

### ISSUE THREAD

**Issue by aznan2** [radiantearth/stac-spec#1160]
The section for the geometry field in [item-spec.md](https://github.com/radiantearth/stac-spec/blob/v1.0.0/item-spec/item-spec.md) refers to [RFC 7946, section 3.1](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1), which includes all seven geometry types, so I assume that the intent is that items can have a GeometryCollection.

In the JSON schema, the geometry field must be null or conform to https://geojson.org/schema/Geometry.json. However, this file only defines the six base geometry types and does not allow for the object to be a GeometryCollection.

Not sure if this is actually an issue with the GeoJSON schema but as things stand, items with a GeometryCollection as its geometry will not validate against the schema.

**Comment by m-mohr** [comment]
We don't allow GeometryCollection and remove it from the Item Spec Markdown.

**Comment by PowerChell** [comment]
Just needs a PR and then can close @matthewhanson
