### ISSUE TITLE
STAC representation of licenses with a choice of license

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-spec#1174]
Hi all,

There are a number of data products around that give the user a choice between two or more licenses as the users discretion. One option is to just pick one for a STAC Collection or STAC Item, but it would be better if we had some way to express that choice.  This is different than the case where multiple licenses all apply to the data.

e.g. some datasets say pick either `CC-BY-SA-4.0` or `ODbL-1.0`

I was thinking that the hoster of the STAC catalog could pick a default and then have a second field that gives a list license options.

**Comment by m-mohr** [comment]
You can use the license type "various" and provide multiple links with the relation type "license" (and title).

We had SPDX expressions in the spec previously, but that only worked for SPDX licenses and was quite complex. So I think the way of using links and, if required, giving additional information in the description should also work.

**Comment by schwehr** [comment]
That doesn't make search very easy.

**Comment by m-mohr** [comment]
That's what you can do with core STAC. If you need more, you'd need to write a STAC extension that gives you more flexibility.

**Comment by m-mohr** [comment]
See also #1178
