### ISSUE TITLE
Classification Extension

### ISSUE THREAD

**Issue by drwelby** [radiantearth/stac-spec#1175]
The Classification extension has reached an initial release with pilot implementations planned from Microsoft Planetary Computer for Landsat and Modis rasters and Maxar for ARD cloud mask rasters.

https://github.com/stac-extensions/classification

**Comment by m-mohr** [comment]
Great work! Not sure this is an "issue" though ;-)

**Comment by drwelby** [comment]
Just following https://github.com/radiantearth/stac-spec/blob/master/extensions/README.md#proposing-new-extensions to be extra sure everyone gets a chance to see it.

**Comment by drwelby** [comment]
Yeah, I was expecting to be able to put a label on it so it wouldn't look like an "issue" issue. Discussions are probably a better place but I always forget they exist.

**Comment by drwelby** [comment]
But since we've already had some good discussion in the extension repo I think you could close this too :)
