### ISSUE TITLE
Keywords with category attribute

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-spec#1177]
Dear all, I was wondering if you have already considered how to describe keywords from different "categories". 

At the moment it is only possible to add keywords as strings, no matter what the keywords are about. 
But it would be helpful to be able to assign them to a specific category as for example : 

- **spatial** keywords: "World", "Europe", "Antarctica" etc.
- **temporal** keywords: "daily", "8-day", "yearly"
- **thematic** keywords: "Land user", "Elevation"
etc.

Something like `{"category":"temporal", "value":"daily"}`

I've got a STAC catalog where I want to give the possibility to apply some filters for searching between the collections, but having all the keywords together as simple strings makes it impossible to make a sort of faceted search on keywords from different domains. I can just have a flat list of keywords that is kind of hard to use since all terms are mixed up.

**Comment by p3dr0** [comment]
+1
ideally this property could be defined with an IRI and be called "scheme"

**Comment by emmanuelmathot** [comment]
Please check and review https://github.com/stac-extensions/subjects and let me know if it covers the need here

**Comment by m-mohr** [comment]
Please see https://github.com/stac-extensions/themes
