### ISSUE TITLE
Correct license for Open Data but not available in the list of possible licenses

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-spec#1178]
In my STAC Catalog I've got various Open Data that have a license not belonging to the SPDX [License identifier](https://spdx.org/licenses/) list. Most of them simply have a specific Provider's license (such as the Copernicus ones) which though permits free reuse and download. 

At the moment the only option for the STAC license would be "proprietary" which though is a little misleading as concept if we're talking about data which is Open but just doesn't have one of the standard Open licenses listed. 

Couldn't there be another word to be used either than _various_ or _proprietary_? Something like "free" or "opendata" or  "open" or similar. 

That would help in particular in web catalogues where the user would right away think that a collection is proprietary and so probably not reusable, which though is not forcedly implied.

**Comment by m-mohr** [comment]
We've discussed this in the past, but couldn't come up with a good alternative yet as there's no better registry of licenses. Right now there's no alternative and your best bet is probably `various`, which is not too bad as that should then be explained with a link with rel type 'license' anyway. Software such as STAC Browser usually don't show the "proprietary" or "various" anyway if a link with rel type license and a title is given. It then shows the title which you can put anything you like.

**Comment by m-mohr** [comment]
Could you link to some examples of licenses you are using?

If the licenses are actually commonly used and it is missing from SPDX, I'd propose to try to add it:
https://github.com/spdx/license-list-XML/pulls

If the license is a custom one although it is making the data open, it really is a proprietary license. Proprietary doesn't necessarily mean closed source/data or so, it just means that someone wrote a proprietary/custom license. So STAC is correct here, although it might have been a wiser move to call it "custom" or so.

**Comment by chiarch84** [comment]
This is the exactly the case. It is a custom license (which many times isn't even defined anywhere) just saying that data is open. As you mentioned though the word "proprietary" is misleading. In our case we in effect used "proprietary" for these cases, but it just seems strange for the users who see this.  

Maybe I could propose to add to the https://github.com/spdx/license-list-XML/pulls list a "generic open data" license so that all that is open data with no specific license could fall there. I know it is a best practice to have a license defined but in many cases projects just produce it and don't care about this step.

**Comment by m-mohr** [comment]
In STAC the license currently allows:
- various
- proprietary
- SPDX license key (which is not enforced in the validation)

In OGC API - Records they are using:
- other
- SPDX license key (which is not enforced in the validation)

In the past we've learned that various and proprietary are not quite what implementors like. Is what Records proposes in https://github.com/opengeospatial/ogcapi-records/pull/236 better? Should we add "other" in STAC 1.1 and deprecae various and proprietary (i.e. to be removed in 2.0)?

**Comment by matthewhanson** [comment]
This will be resolved by changes proposed in the issue #1232
