### ISSUE TITLE
Minor: Wording in examples/catalog.json

### ISSUE THREAD

**Issue by batpad** [radiantearth/stac-spec#1183]
This line: https://github.com/radiantearth/stac-spec/blob/master/examples/catalog.json#L35

Says `"title": "Collection with no items (standalone)"` but the link is to `collectionless-item.json` which is an Item without a collection (Not a "collection with no items"). This seems maybe copy-paste error?

Hope I didn't get that wrong - can also make a PR - thank you for all your work!

**Comment by m-mohr** [comment]
Yes, indeed. The title should probably be something like "Item without collection" or so. A PR would be appreciated.

**Comment by m-mohr** [comment]
Has been solved in the meantime (dev branch).
