### ISSUE TITLE
Extend common metadata by keywords

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1187]
We've already made license and providers common metadata, but there are a couple more things that we could add there so that they get more "common".
- `keywords` from the Collection spec is general enough and could be useful elsewhere.
- `language` from OGC APIs: http://docs.ogc.org/DRAFTS/20-004.html#collections-properties-table, see also #1190 
- A potential new bands field could replace eo:bands/raster:bands.
- We could also look at some of the prefix-less fields from the timestamps and version extensions.

**Comment by KennSmithDS** [comment]
@m-mohr emphasizing from prior discussion on Slack that Common Metadata get applied to `Catalog` objects as well, particularly `keywords`, `created`, `updated`.

**Comment by emmanuelmathot** [comment]
Totally with all the propositions. We could make separate PRs to propose and decide for each of them? I already did the work for keywords in this extension proposal: https://github.com/stac-extensions/subjects

**Comment by m-mohr** [comment]
Yes, we can sure go on a 1:1 basis. Keywords is meant to stay free-form without vocabulary though so I still think there's value in the subjects extension (although potentially aligned with OGC APIs).

**Comment by p1d1d1** [comment]
could you please consider this? https://github.com/radiantearth/stac-spec/issues/1190

**Comment by m-mohr** [comment]
Wait for #1199 to be merged, then we can also remove keywords from the collection schema.

**Comment by emmanuelmathot** [comment]
> `keywords`: Wait for #1199 to be merged, then we can PR it into common metadata and directly remove keywords from the collection schema, too.

#1199 is not a PR. I dont find one that covers the keywords integration in common metadata

**Comment by emmanuelmathot** [comment]
ok. I can help with that if needed.

**Comment by m-mohr** [comment]
@emmanuelmathot Great, happy to review the PR.

I guess it's relatively simple, just add keywords to the Basics category: https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#basics
Update JSON Schema (move from Collection to common metadata and reference it from the Collection).
