### ISSUE TITLE
Multi-language support: add a property "language" to common metadata

### ISSUE THREAD

**Issue by p1d1d1** [radiantearth/stac-spec#1190]
Is there any discussion on adding a new "language" property to the common metadata? This would really support/enable several use cases.

**Comment by m-mohr** [comment]
Discussion started in https://github.com/stac-extensions/file/issues/12
Related issue in STAC API: https://github.com/radiantearth/stac-api-spec/issues/306
OGC APIs define the langauge keyword: http://docs.ogc.org/DRAFTS/20-004.html#collections-properties-table

I think language would be a useful addition to common metadata and fruther help with OGC API alignment.

@p1d1d1 I think it would help to convince people if you could describe what use cases you are thinking about.

**Comment by p1d1d1** [comment]
I'm working for the Swiss Government and we are currently using STAC for both raster and vector data: https://data.geo.admin.ch/api/stac/v0.9/
Now, Switzerland is a multilingual country and we have to support at least "de" and "fr" in all services that we provide.
We think that the STAC ecosystem is currently missing a generic multilingual support and to achieve it one would need:

1. https://github.com/radiantearth/stac-spec/issues/1190
2. https://github.com/radiantearth/stac-api-spec/issues/306
3. https://github.com/radiantearth/stac-browser/issues/123

Or do you see it differently?

A second use case / requirement we have is about the "data language" (asset file). For some datasets in our catalog, we provide Asset files (for the same Item) in different languages and we want to communicate to the user the language in which any textual information in the file is expressed. To achieve this we are currently using our self-defined extension: e.g. https://data.geo.admin.ch/api/stac/v0.9/collections/ch.bav.haltestellen-oev/items/haltestellen-oev

**Comment by m-mohr** [comment]
I've written a proposal for a new STAC extension that adds multi-language abilities to static STAC collections:
https://github.com/stac-extensions/language

There's also a proposal for a new STAC API extension:
https://github.com/stac-api-extensions/language

Feedback on both would be appreciated in the corresponding issue trackers.
