### ISSUE TITLE
Require type field in links and assets

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#1202]
Discussions about https://github.com/radiantearth/stac-api-spec/issues/351 in a call on Dec 12 22 lead to a conclusion that the core stac spec should also require type field in links. It'll be added for stac api spec, since it's very useful for API mechanics to use this, like with an 'accepts' header. It'd be good to align the specs. We might also consider it for 'assets' too, as links and assets are quite similar.

**Comment by m-mohr** [comment]
I randonly stumbled across a use-case where the type is not clear and as such having it required may lead to some confusion: https://github.com/stac-extensions/web-map-links

In the web-map-links extension we use templated URIs to a service. It doesn't really have a unique media type. What's the media type of a WMTS URL? XML? PNG? JPEG? ...

**Comment by m-mohr** [comment]
Due to https://github.com/radiantearth/stac-api-spec/issues/413 this is obsolete, at least for OGC API alignment. We can of course still discuss whether we want to require the type in 2.0.
