### ISSUE TITLE
Is geometry required for Item?

### ISSUE THREAD

**Issue by ka7eh** [radiantearth/stac-spec#1215]
The `Description` column (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields) says it's required, but the `Type` column says it can be null. Which one is correct? Does it accept `null` just to be compatible with geojson spec?

**Comment by emmanuelmathot** [comment]
Required means that the field `geometry` must be present either with a valid geometry or with `null` value.

**Comment by ka7eh** [comment]
Got it. Thanks. I'll close this.
