### ISSUE TITLE
Multiple parents?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1230]
Can (and should, if applicable) a STAC entity have multiple parent links?

Example: We have (for better browsability) a static catalog where multiple catalogs (A, B) link to another collection C. From the folder structure there's a clear parent (A) in this case. Should C link to both A and B or just to (e.g.) A?

I think the spec should clarify this (as requirement or recommendation). I didn't find a clear answer in the spec, maybe I missed it.
Right now I assume multiple parents are allowed and it's up to the implementation to decide whether they place one or more, depending on their usecase/requirements. BUT I think we might have meant to just have a single parent.

cc'ing some people for input: @matthewhanson @gadomski @cholmes @pvretano (any thoughts from the static Records perspective?)

**Comment by m-mohr** [comment]
A more specific example:

* Root (at `/`)
  * Product
    * S2
    * L8
    * S1
  * Domain
    * Multi-Spectral (links to `/Product/S2` and `/Product/L8` as "child")
      * (S2)
      * (L8)
    * SAR (links to `/Product/S1` as "child")
      *  (S1)

**Comment by gadomski** [comment]
I'm 👎🏼 on multiple parents. My personal mental model of STAC is filesystem-like, where one file can't live in multiple folders. Any additional relationships should be "sibling" or "child" relationships, IMO. Complexity goes _way_ up if we support multiple parents.

**Comment by m-mohr** [comment]
Yes, me too. I just want to clarify it in the spec. So the example above is fine to do, but only set one parent (ideally like in the filesystem, I guess).

**Comment by jlaura** [comment]
It might be valuable to have a best practices entry specific to dynamic catalogs. Does a dynamic catalog really need multiple parents if it is being generated on the fly? Is a dynamic catalog designed to be browsable via a hierarchy?

**Comment by raelwaed** [comment]
I am thinking the answers to your questions are:
1. Dynamic catalogs can be browsable by multiple hierarchies which I think requires multiple parents be supported at the storage level. I suppose if you had to have only single parents returned the API could dynamically remove the parents not in the traversal path... ?
2. I think a dynamic catalog is designed to be browsable via a hierarchy.

**Comment by matthewhanson** [comment]
Discussed in STAC sprint.

- Decided to not support multiple parents.  Dynamic catalogs can implement multiple parents through a dynamic browsing interface as they could dynamically create the parent link based on the desired browsing structure (though only 1 parent at a time).
- If multiple "parents" are desired the better approach is to use a different relational type (e.g., "related").
- We do not want to have to build support in the ecosystem for multiple parents.
