### ISSUE TITLE
Collection links for catalogs/collections

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1236]
I'm currently experimenting with collection links in non-Items. I think there can be value in having them.

Example implementation: https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/m-mohr/open-stac/3d-skysat/stac/open-skysat-data/cocabamba-peru/catalog.json

Having an easy way to navigate back to the next collection in the (potentially long) list of parents may help navigation.

Let's say you have a structure as such:

- Root
  - ESA (collection)
    - Sentinels (catalog)
      - Sentinel-1 (catalog)
      - Sentinel-2 (catalog)
        - Level 1A (collection)
          - 2020 (catalog)
            - Jan (catalog)
              - 01 (catalog)
                - 12345 (item)
                - 67890 (item)
                - ...
              - 02 (catalog)
              - 03 (catalog)
              - ...
            - Feb (catalog)
            - Mar (catalog)
            - ...
          - 2021 (catalog)
          - 2022 (catalog)
        - Level 2A (collection)
        - Level 2B (collection)
    - Others (catalog)
  - NASA (collection)

I think there should be easy ways without following multiple parent links up to the collection, e.g. for easy navigation from `Level 1A` to `ESA` or `01` to `Level 1A`. Thus my proposal is to also allow links with rel `collection` explicitly also in Catalogs and Collections. Currently it's only defined for Items.

Disclaimer: This is just an example for better understanding, it doesn't matter here whether ESA is a good or bad Collection. It could be something different.

**Comment by PowerChell** [comment]
Note: one of the most common questions Matthias gets. High Priority.
