### ISSUE TITLE
Additional fields for assets unclear

### ISSUE THREAD

**Issue by christophfriedrich** [radiantearth/stac-spec#1237]
Regarding additional fields for assets, [the docs](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#additional-fields-for-assets) say:

> For an example see the [sentinel2-sample](https://github.com/stac-utils/stac-examples/blob/main/sentinel2/sentinel2-sample.json). The Sentinel-2 overall `gsd` is 10m, because this is the best spatial resolution among all the bands and is defined in Item properties so it can be searched on. In the example Band 5 and others have a `gsd` of 20m, so that asset specifies the `gsd` as well, which overrides the Item `gsd` for this one asset.

But in fact, in the example the `gsd` is only specified in the `properties` and nowhere else in the file; just the individual assets' `title`s mention it (but that's not really machine-readable).

Now I'm unsure what is the correct way to express this in STAC? I raised the issue here, but maybe it will need to be transferred to the stac-examples repo.

**Comment by PowerChell** [comment]
Closing as duplicate issue #1228
