### ISSUE TITLE
Collection bbox schema

### ISSUE THREAD

**Issue by drwelby** [radiantearth/stac-spec#1243]
The definition of the bbox spatial extents has non-obvious construction:

`The first bounding box always describes the overall spatial extent of the data. All subsequent bounding boxes can be used to provide a more precise description of the extent and identify clusters of data.`

i.e.
`[[extent]]` or `[[extent], [child], [child]...]`

Should the schema try to catch people interpreting the spec as a simple list of bboxes by enforcing either a length of 1 or 3?

Or is that too restrictive and the catch should be passed down to validators like `stac-check`?

**Comment by m-mohr** [comment]
Yeah, that makes sense. Two bboxes don't make sense.

So either one or 3 or more.

**Comment by m-mohr** [comment]
See PR #1260
