### ISSUE TITLE
The schema for stac-item.json does not reflect the change in 0.5.0 release

### ISSUE THREAD

**Issue by asivapra** [radiantearth/stac-spec#126]
To validate the Item JSON created with "Link as a Dictionary" (https://github.com/radiantearth/stac-spec/releases/tag/v0.5.0) it is necessary to have the following change in stac-item.json. It appears that the master branch has not received this change.

  "links": { "type": "array" }
to
  "links": { "type": "object" }

**Comment by cholmes** [comment]
I believe this is fixed in 0.5.1 or 0.5.2 (and was part of why I issued that release). Can't go back to 0.5.0 and change it there, unfortunately.
