### ISSUE TITLE
Ambiguous Catalog example

### ISSUE THREAD

**Issue by fmigneault** [radiantearth/stac-spec#1266]
The following catalog example seems to contradict itself between the reference name and the description.

https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/examples/catalog.json#L32-L35

Shouldn't the description be something like "An Item not nested within any Collection (standalone)" ?

**Comment by emmanuelmathot** [comment]
@fmigneault Could you please submit a small PR for closing this? Thx

**Comment by fmigneault** [comment]
@emmanuelmathot I've opened #1282, but realized by targeting https://github.com/radiantearth/stac-spec/tree/dev that it was already adjusted there. These small fixes should probably be integrated more quickly in master, since no one will see `dev` for a long time until the next release.

**Comment by emmanuelmathot** [comment]
already fixed by https://github.com/radiantearth/stac-spec/pull/1146
