### ISSUE TITLE
Datasets without time

### ISSUE THREAD

**Issue by renaudjester** [radiantearth/stac-spec#1268]
Dear all,

We have some datasets that do not have time values and we are struggling on how to fill their metadata, as the STAC specification requires either a value (`properties/datetime`) or a range (`properties/start_datetime`, `properties/end_datetime`) and therefore pystac has the same requirements. We could see that it has been discussed here #792 but in our case we cannot find a proper “nominal” datetime for our datasets.

For example, some datasets are static datasets (bathymetry, coordinates) that are atemporal and that are released together with other temporal datasets in our catalog. Other cases might be aggregated statistics and indicators, which have lost the time dimension.

Would it be possible to relax the standard to not make the time properties mandatory? Otherwise, how would you suggest that we describe these datasets?

Many thanks for your help!

**Comment by m-mohr** [comment]
Well, this is the _SpatioTemporal_ Asset Catalog. As such it requires certain things such as space and time references to be available. I don't think this will be weakened. As an alternative OGC API - Records is evolving which has less strct requirements. Once standardized I imagine it could be mixed with STAC so that non-SpatioTemporal entities can be described in a compatible format through OGC API - Records.

If you aggregate statistics over a certain time range, shouldn't the statistics have a refernce to the source time range? Generally, I think a lot of data actually have a temporal reference although not completely obvious. But that's just my personal view here.

**Comment by fmigneault** [comment]
What about situations where the `end_datetime` is not known?
For example, a growing item definition that gets more and more labels applied gradually as a continuous annotation effort? 

Another case I have is for using ML models. 
Similar to what https://github.com/stac-extensions/ml-model?tab=readme-ov-file#spatiotemporal-fields describes, a max value of `"9999-12-31T23:59:59Z"` needs to be filled to work around the requirement, although it would make much more sense to leave the time range open-ended with `end_datetime: null`, similar to OGC's `<start_datetime>/..` nomenclature. The same issue applies for the MLM extension (https://github.com/crim-ca/dlm-extension/pull/2).

**Comment by mikemahoney218** [comment]
> What about situations where the end_datetime is not known?

It seems to me like the _current_ `end_datetime` is known, even if the _final_ `end_datetime` isn't. Is there a reason you can't update your `end_datetime` when updating other labels/data?

**Comment by fmigneault** [comment]
Yes. For that case I agree, the `end_datetime` could be updated at the same time as the labels get pushed.
I am more worried about users taking the other "patch" approach of simply setting a high value to work around the schema validation. I would prefer to have a way to specify an explicit representation of "undefined" than any random large value.

**Comment by m-mohr** [comment]
I think everything has been said here?!

- No time => OGC API - Records, STAC is unlikely to allow no time information - it's a bit inconsistent that geometry can be set to `null`. We could reconsider all this in STAC 2.0 if there's still enough interest outside of OGC API - Records.
- Open ranges => see #1161
- Closed ranges or instances => supported in STAC
