### ISSUE TITLE
item in multiple collections

### ISSUE THREAD

**Issue by mhogeweg** [radiantearth/stac-spec#1273]
what would one do if an item belongs to multiple collections in a STAC? the collection field in the item spec is a string. if an item belongs to multiple collections would it be indicated in a list? or comma-separated string? and then what would one do with the rel:collection link? multiple instances? or one instance for one of the collections the item is in and then have alternates for the other collection memberships?

**Comment by m-mohr** [comment]
Somewhat related (hierarchical collections): https://github.com/opengeospatial/ogcapi-common/issues/298#issuecomment-2115855204 So something we should review.

**Comment by m-mohr** [comment]
The work that OGC is doing is purely relevant to APIs, we don't need to consider it in the static version of STAC.

The question has also been answered and the OP did not respond yet, so we assume that this issue has been clarified sufficiently.

**Comment by mhogeweg** [comment]
For me the issue may be closed. In our back-end we can handle an item being part of multiple collections (like views on a table). But when looking at an item from the view of a collection, it is just part (or not) of that one collection.
