### ISSUE TITLE
STAC 'management API'

### ISSUE THREAD

**Issue by mhogeweg** [radiantearth/stac-spec#1274]
has there been work/consideration to extend the STAC API with management operations? For example:
- HTTP PUT on .../collections/{collectionId} with a proper body could define a new collection or update an existing one with the specified collectionId
- HTTP DELETE on .../collections/{collectionId} would delete the collection (and items)
- HTTP PUT on .../collections/{collectionId}/{itemId} with a proper body would add an item with the specified ID to the specified collection or add the item if it already exists
- HTTP DELETE on .../collections/{collectionId}/{itemId} would remove the specified item
- ...

**Comment by emmanuelmathot** [comment]
Those operations are defined in the following [STAC API extensions](https://stac-api-extensions.github.io/):
- https://github.com/stac-api-extensions/transaction
- https://github.com/stac-api-extensions/collection-transaction

This repository is dedicated to the STAC model specification. The STAC API has its own repository [here](https://github.com/radiantearth/stac-api-spec).
