### ISSUE TITLE
Don't require a specific list of roles for providers?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1277]
e.g. to align with STAT API

**Comment by emmanuelmathot** [comment]
Can you link to STAT API ref please?

**Comment by m-mohr** [comment]
It was renamed: https://github.com/stapi-spec

STAPI didn't want to choose with STAC yet, so we can discuss it but then potentially move it to later.

**Comment by m-mohr** [comment]
Also, this is a breaking change, so this should go into 2.0 (if at all).

**Comment by m-mohr** [comment]
Duplicate of https://github.com/radiantearth/stac-spec/issues/1147
