### ISSUE TITLE
API date/time filtering

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#130]
Right now the API calls for a 'time' parameter, e.g.

```
{
  "bbox": [ 5.5, 46, 8, 47.4 ],
  "time": "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z"
}
```

But that's actually a datetime, and the metadata field in the STAC `item` is also called datetime. In sat-api, the query term is datetime. If this is to be a query term for both date and time then I think it should be datetime, just like the STAC field.

However, I also am wondering at the usefulness of combining both date and time together. Users are generally going to query on date and time for different reasons, and a start time and an end time that correspond with specific dates makes little sense for a user.

Instead a user is more interested in a date, or date range. Then they might also be interested in images within a certain range of time of day. 

So I think the API could be a bit more user friendly by allowing for a 'date' query term, and a 'time' query term. Since datetime is also a field I don't see any reason to be able to query on the complete 'datetime' as well. 

Thoughts?

**Comment by m-mohr** [comment]
I support to rename it to `datetime` for consistency.

The proposed `time` query for time ranges could be useful, but we would need to invent a new format for it, right? ISO 8601 doesn't seem to cover pure time ranges?!

**Comment by cholmes** [comment]
So the main reason to keep it as 'time' is for consistency with WFS3, where the convention is to use 'time' to match with whatever time field the server says is default. Just like bbox matches with a default geometry property.

I do think it's important we keep WFS 3 compatibility, or at least have a version of the spec that is compatible. But I think our WFS 3 compliant version could require a fuller query language than the WFS 3 core, where all attributes can be queried, which would give us the ability to respond to a named field time request (datetime) and not just the default.

**Comment by hgs-msmith** [comment]
I agree that consistency with WFS3 trumps internal consistency with the STAC metadata model. 

m-mohr, note that ISO 8601 notation does support time ranges. For example, if I wanted to search all data for July 2018, I could do this (range):
   2018-07-01/2018-07-31
or this (duration):
   2018-07-01/P31D

And if I wanted to search data from the last 5 Julys, I could do this (repeating duration):
   R5/2013-07-01/P31D

**Comment by matthewhanson** [comment]
Sure consistency with WFS3 is good, but if it's actual a datetime query than I think WFS3 should change their query term. A datetime is not a time or a date, it is both. It is immediately apparent what datetime means, if 'time' means 'datetime' then it is not self describing and requires looking at the documentation.

I do think querying just 'time' separate from 'date' is also somewhat useful. As the amount of data grows users might very well be interested in images taken during a specific time of day. For example, I want to count cars during heavy traffic times or in parking lots during business hours.

**Comment by hgs-trutherford** [comment]
Perhaps the new query extension should consider "date", "time" and "datetime" as separate operators? That might help resolve the issue?

**Comment by cholmes** [comment]
Closing this. I think we can handle this at the query operator level. And we can also advocate for WFS to change their query term to datetime. @matthewhanson - you want to make an issue in their tracker, and reference this discussion?

**Comment by m-mohr** [comment]
I had to write an issue with temporal issues anyway on the WFS issue tracker, so I just added this: https://github.com/opengeospatial/WFS_FES/issues/155
