### ISSUE TITLE
Require title 

### ISSUE THREAD

**Issue by emmanuelmathot** [radiantearth/stac-spec#1300]
Following closure of #1232 and the [crosswalk between OGC API - Records and STAC](https://github.com/stac-utils/stac-crosswalks/blob/master/ogcapi-records/README.md), this issue aims at specifying a mandatory title in STAC 2.0

### title
`title` is required in Records for Collections and Items. Having titles in the resources and also in the links makes the browsing experience much nicer (see STAC Browser). Titles in Catalogs/Collections and their corresponding links should be aligned anyway. So I'm wondering whether we should require the title field in Catalogs and/or Collections and/or Items. Collections should always have a title, I think. It would also be good for Catalogs to explicitly choose a title and people use the id as title pretty often aynway. For Items real titles are often not available (e.g. for satellite captures), but anyway a default title provided by the provider would be good for UX.

**Comment by m-mohr** [comment]
Records doesn't require the title anymore, I think we can close this.
