### ISSUE TITLE
Consider having API spec use GeoJSON spec for geometry

### ISSUE THREAD

**Issue by metasim** [radiantearth/stac-spec#131]
Currently the `api-spec` schema defines it's own geometry types, while the static spec depends/defers on the `geojson.json` schema.

https://github.com/radiantearth/stac-spec/blob/b7fe13e5d9aab371ead0e80a9c9cb7c97c49ec5c/api-spec/STAC-fragment.yaml#L174-L217

Furthermore, the structure of the `api-spec` types appear to be different from the GeoJson types. 

Consider having a single set of geometry types across all schemas.

**Comment by cholmes** [comment]
cc @hgs-msmith and @hgs-trutherford 

I think the intent was to have the geometries be the same as GeoJSON - we just couldn't refer to the geojson.json directly as its a yaml document. 

@metasim - could you lay out what where the types between api-spec and geojson diverge? A PR to change it would be great, unless Michael and Tim have a reason it's the way it is.

**Comment by hgs-trutherford** [comment]
@cholmes I think one of the early versions of the STAC spec had that geojson schema and we just leveraged it. If there is a better way to indicate a goejson object, I am all for it.

**Comment by metasim** [comment]
@cholmes I'll try to take a look at it soon, what a api-spec mod would look like... I'm not all that adept with JSON Schema (more of an XSD background), so I'm not as confident on what I'd come up with. Excuses aside, here's where it seems the `stack-item.json` definition "defers" to GeoJSON.


https://github.com/radiantearth/stac-spec/blob/b7fe13e5d9aab371ead0e80a9c9cb7c97c49ec5c/json-spec/json-schema/stac-item.json#L19

**Comment by hgs-trutherford** [comment]
The new fragment model we added should help with this. We can pull the GeoJSON definition out into a separate file. I think the yaml library is intended to support JSON schema as well? @scisco

**Comment by hgs-truthe01** [comment]
#253 Should help fix this. I chose to use the schema definitions hosted by geojson.io, but if there is a preference for schemastore, I can probably switch over.

**Comment by m-mohr** [comment]
Seems to be fixed.
