### ISSUE TITLE
"item" v. "items" in collections

### ISSUE THREAD

**Issue by tpoisot** [radiantearth/stac-spec#1312]
In JuliaClimate/STAC.jl#17 we found a tricky situation where the STAC spec says `"rel"` can be `"item"` for links, but some catalogues ([ESA](https://eocat.esa.int/eo-catalogue/collections), [Planetary computer](https://planetarycomputer.microsoft.com/api/stac/v1/collections/terraclimate), and [GEOBON](https://stac.geobon.org/collections/soilgrids)) use `"items"` for their links.

The [STAC API spec](https://github.com/radiantearth/stac-api-spec/blob/release/v1.0.0/stac-spec/collection-spec/collection-spec.md#relation-types) says the relationship from collection to item should use `"item"`.

Where is the use of `"items"` documented, and is it something that's to be expected or a "convention" that some catalogues started using?

(cc. @glaroc / @jmlord)

**Comment by m-mohr** [comment]
items is a relation type in the STAC API spec that leads to a list of items, the item relation type is from STAC spec and leads to a single item.
