### ISSUE TITLE
Requiring title, id, description

### ISSUE THREAD

**Issue by 777arc** [radiantearth/stac-spec#1317]
Just wanted to share some thoughts while I learned about STAC for the first time.  I would have expected `title` to be required and `description` to be optional.  Eg one might not have any `description` because there might be nothing more to say besides what's already in the required metadata, and it's easily treated as an empty string (if left out) by applications like STAC Index.  This also brings up the question if applications that display Collections should use `id` instead of `title` as the primary label since `title` is optional.  Looking at STAC Index (first screenshot below) it looks like it uses `title (id)` as the overall title.  Meanwhile in Items, the `id` is used as the labeled title (see 2nd screenshot), bringing up the question why the `title` field even exists at all.  For folks creating applications around STAC it's nice to have one really clear way things are done.

![image](https://github.com/user-attachments/assets/e828749b-283d-4f62-a9b2-4e2a0ba6500a)

![image](https://github.com/user-attachments/assets/e83f9150-eaa3-47ee-acc8-73f24244a0ba)

Thanks!

**Comment by emmanuelmathot** [comment]
The [best practises document](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md) recommends to [always](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#titles) set the title field in order to avoid discrepancies
> One further recommendation to help tools is to always include the 'title' field when including a link, especially in the item, child, parent and root links, even if it repeats several times. This should be the same as the 'title' in the link destination. Having this enables clients to display a nice human readable name of the link without having to open the link destination.

In the version 1.x, the title field cannot be mandatory without a breaking change and thus [shall be expected for version 2.x](https://github.com/radiantearth/stac-spec/issues/1300) also for aligning with OGC features

**Comment by 777arc** [comment]
Awesome!  Will description be mandatory in 2.x?

**Comment by m-mohr** [comment]
I'd assume that description is still mandatory in 2.x, but it can always be discussed to be optional in 2.x.
Please not thet description can not be empty in the 1.1 and later schemas. We fixed the schemas accordingly as it was an oversight in 1.0 to not require it to be filled in some cases.
