### ISSUE TITLE
Array vs. Object for lists of links

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#134]
I'd like to re-raise this for discussion, per https://github.com/radiantearth/stac-spec/issues/127#issuecomment-405300991

**Comment by jeffnaus** [comment]
Sprint 3 Static Group:

We recommend arrays.  This is largely in line with these comments [#127 (comment)](https://github.com/radiantearth/stac-spec/issues/127#issuecomment-405300991)

**Comment by m-mohr** [comment]
Fixed with #207.
