### ISSUE TITLE
Publish code / tools to migrate between versions alongside spec version updates

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#135]
Many of the changes we're proposing between versions can be scripted given existing catalogs, so let's make it easier to migrate (and not use that as a disincentive to clean things up as we reach a 1.0).

**Comment by m-mohr** [comment]
@mojodna Do you already have some code for this? Otherwise, I'll probably start with this in August on a JS basis...

**Comment by mojodna** [comment]
Reading back through and I spotted this. No, nothing yet. Did you make any headway in August on it?

**Comment by m-mohr** [comment]
Unfortunately, other work blocked it. I just have a converter for Collections starting with 0.6.x...

**Comment by m-mohr** [comment]
I'll work on this here: https://github.com/m-mohr/stac-upgrade-js

**Comment by cholmes** [comment]
STAC Browser currently does not work with multiple versions afaik. Cc @vincentsarago

**Comment by matthewhanson** [comment]
PySTAC will now open up old versions of STAC and convert to latest version, https://github.com/stac-utils/pystac/ 

Closing
