### ISSUE TITLE
Add enhancements for richer display of STAC items on web pages.

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#145]
There are likely a number of enhancements to make a catalog and item pages look better when they are transformed in to HMTL with a tool like STAC Browser.

See http://planet-stac.netlify.com/ for an example.

Top of the list would be to add an image to be displayed - logos or other representations.

Perhaps also a way to include certain catalog or collection metadata down on child sub-pages.

Should brainstorm ideas and make concrete proposals, ideally prototyping with stac-browser.

**Comment by m-mohr** [comment]
Duplicate of #196.
