### ISSUE TITLE
start_datetime and end_datetime as optional core fields

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#154]
This was discussed at length in the first sprint, and a bit in the second.

In the end we decided for simplicity that a single datetime was the best approach, since every data source should have a single datetime.

However in reality no data item is going to be representative of a single instant in time. Even a 2D focal plane array has an exposure time. Push broom sensors collect data over swaths, mosaics merge together multiple images.

Yes, start and end datetimes could be part of extensions, but I think we'll find we end up adding them to every single extension (they really should be in the EO extension).

In this case I think it really makes sense to make them core fields, but make them optional while 'datetime' is required.

cc @cholmes @mojodna @scisco

**Comment by jeffnaus** [comment]
Sprint 3 static:

We need start/end for FMV.  Mosaics have a multiple dates.

This is one or more extensions.  
Note that one singular datetime is still required.

**Comment by cholmes** [comment]
Closed with #168
