### ISSUE TITLE
SAR Content Extension

### ISSUE THREAD

**Issue by hgs-msmith** [radiantearth/stac-spec#155]
Define metadata extension for SAR data.

**Comment by hgs-msmith** [comment]
Consider adding the following as SAR-specific metadata:

- Pass direction | ascending vs. descending orbit
- Polarization | HH, VV, HV, VH
- Instrument mode | IW, stripmap, etc.
- Product class | RAW, SLC, GDR, etc. – different levels of processing
- Range resolution | eo:gsd as array?
- Azimuth resolution | eo:gsd as array?

**Comment by jeffnaus** [comment]
I'll, jnaus, will own this and give an example and kick off for comment

Questions:  What is the relationship between this and the EO extension.  can they/ should they have the same parent.

**Comment by matthewhanson** [comment]
There is a lot of fields in the EO extension that apply here. The whole bands mechanism can be used as in EO extension - SAR bands can be specific with wavelength, FWHM, and even common_name can be used to refer to standard radar wavelength bands (e.g., x-band).

Regarding sharing a parent, multiple inheritance isn't something that has been discussed yet, unless you guys talked about this meeting. I'm not sure we want to go down that path.

**Comment by jeffnaus** [comment]
In my experience the bands are different then EO in that they are magnitude, phase, or SLC (single look complex, which is the response time and strength combined).  The wavelength information usually is set for the sensor and this is then combined with beam mode (like wide or fine...) to determine spatial and spectral resolution.  Multi-look data is different from this also and I don't have direct experience with those datasets.  I'll do more research around this, I may make an initial spec proposal for just single look derived products.

**Comment by m-mohr** [comment]
As we need it for openEO soon, we'll write a proposal in the next weeks and post it for discussions.

**Comment by m-mohr** [comment]
I made a first proposal for the SAR extension, please review #347. Thanks!

**Comment by m-mohr** [comment]
It has been merged to dev. There were still two comments by @mrepse ([see comment](https://github.com/radiantearth/stac-spec/pull/347#issuecomment-442357747)) and @AlenaDostalova ([see comment](https://github.com/radiantearth/stac-spec/pull/347#issuecomment-442383383)) with open points for discussion. It would be great if you could propose your changes as PR for discussion.

Other than that, I still need to add a JSON Schema.

**Comment by m-mohr** [comment]
Is complete now, I think.
