### ISSUE TITLE
What are the processing levels and where do they belong in STAC

### ISSUE THREAD

**Issue by jeffnaus** [radiantearth/stac-spec#161]
We should start reporting on the processing levels of our images.  What are the processing levels and where should we report them.  Is this one extension or is this additions to lots of extensions.

**Comment by jeffnaus** [comment]
Can we get direction from the ARD group about this?

**Comment by dlindenbaum** [comment]
Examples of different processing

- https://landsat.usgs.gov/landsat-processing-details

- https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/processing-levels
- http://www.geo-rapp.org/wp-content/uploads/2014/12/GEOGLAM-RAPP-Campinas_Joao-Soares_INPE.pdf
-

**Comment by dlindenbaum** [comment]
As a second comment:

Should there be a processing extentension

**Comment by sjskhalsa** [comment]
a little history - processing levels for satellite data originated with CEOS, I believe, but were adopted by NASA - "To facilitate the discussion of data processing in practice, several processing levels were first defined in 1986 by NASA as part of its Earth Observing System and steadily adopted since then" (wikipedia).
https://science.nasa.gov/earth-science/earth-science-data/data-processing-levels-for-eosdis-data-products

**Comment by matthewhanson** [comment]
There are no standard processing levels, everyone uses different nomenclature, and I really don't think there's any way we can hope to define a standard for that providers would use.

It makes more sense to have fields that specify units, or a flag for surface reflectance or atmospheric correction, or orthorectification, but even then I'm not sure how useful that is. Only if users were searching a catalog for specific types of data. 

It seems more useful to use Datasets/Collections and have a good description of what the data is rather then trying to define a new set of standards for how data has been processed.

**Comment by fredliporace** [comment]
I've drafted something on the line that @jeffnaus suggested:

https://gist.github.com/fredliporace/217d1dbd59ff1ba633ce145f04a39d55

I'm in transit now, will detail later as I reach the office.

**Comment by fredliporace** [comment]
See https://github.com/radiantearth/stac-spec/issues/150 for related discussion

**Comment by cholmes** [comment]
Where are we going to put this? As some attribute on the asset / asset definition?

**Comment by fredliporace** [comment]
@cholmes I'm preparing a PR to the EO extension based on the draft above for further discussion. Note that I'll limit that to "Electro-optical" sensors, other sensors should probably have specific attributes defining their processing levels.

**Comment by m-mohr** [comment]
@matthewhanson wrote in #235:

> @fredliporace I recently went to the ARD workshop this month at USGS, and this was one the things that was discussed.
> 
> It's just the start, but we've set up an [ard-spec](https://github.com/radiantearth/ard-spec) repo to start hashing out some sort of standards to describe processing as well as metrics for uncertainty.
> 
> If some standard fields come out of that effort, we can utilize those in STAC.
> 
> So I'm going to close this, feel free to post your ideas over in the ard-spec.
