### ISSUE TITLE
Allow Markdown in the description

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#162]
During discussions in the group sprinting on collection/dataset-level metadata, we had the idea to allow Markdown (or more specifically [CommonMark](https://commonmark.org/)) in the descriptions. The descriptions are usually written for humans anyway and it would allow to structure your texts better and have a more rich display on web pages (stac-browser) for example. In case markdown is not supported by tooling, it can still be easily read by humans due to it's intuitive syntax. This idea is adopted from OpenAPI and is also used in openEO.

**Comment by simonff** [comment]
+1. We already do this in EE dataset descriptions.

**Comment by m-mohr** [comment]
I think I'll just do a quick PR for this. ;)

**Comment by cholmes** [comment]
Interesting. Cool idea, and nice that there is precedent in EE and OpenEO dataset descriptions. I think I'm +1

Curious if it's easy for STAC Browser to implement rendering of markdown. cc @mojodna

**Comment by m-mohr** [comment]
I already implemented CommonMark support in a vue.js app in the context of openEO process descriptions. Was pretty easy. I could also just make a PR for stac-browser.

**Comment by m-mohr** [comment]
PR for stac-browser is available, too.

**Comment by cholmes** [comment]
awesome work! I merged this, perhaps in slight violation of our new '2 reviewer rule', but it seemed so minor.
