### ISSUE TITLE
Dataset hierarchy

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#184]
This is not a concrete proposal yet - just a place to record some thoughts on catalog organization. So far we have considered Datasets as fully independent objects, though existing in a hierarchy of catalog nodes.

In reality, some Datasets will be tightly grouped together. In EE, I represent this internally as parent and grandparent folders that may contain common attribute to avoid repeating them, though this is not visible to the user yet.

Example 1. A dataset with multiple versions (eg, GLIMS glacier data: http://www.glims.org/download/) has the same attributes across all versions. 

Example 2. Landsat can be considered as a single top-level dataset (forgetting about DN vs TOA vs SR for now). Zooming in, there are multiple Landsat subdatasets - from Landsat 1 to Landsat 8. Zooming in further, each of the subdatasets contain RT, T1 and T2 tiers (https://landsat.usgs.gov/what-are-landsat-collection-1-tiers). (To make this even worse, L7 is divided into SLC on and SLC off modes, and L8 may contain assets with only OLI or only TIRS bands). While all these datasets can be linked via keywords, some hierarchy would be useful here, but because its structure is very ad hoc, it's not clear how to generalize this well. 

Example 3. MODIS Terra and MODIS Aqua.

**Comment by m-mohr** [comment]
I think this is mostly(?) tackled by the dataset extension being introduced as extension to catalogs. After #239 has been merged, it should be clear that it is possible to have a hierarchy of datasets. What we still need to define, how inheritance between datasets should be working exactly or whether that is not a thing in STAC and everything needs to be repeated.

**Comment by m-mohr** [comment]
In the last months we concluded quite often that we don't do inheritance in STAC. Therefore, this issue is solved. Collections and Catalogs can build a hierarchy, but need to repeat data.
