### ISSUE TITLE
Enumerate the common 'rel' types for links

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#191]
This came up in #179 - we need someplace where we enumerate the 'common' link rel types and what they mean for us.  We have a draft for asset types in #180 but should do the same for links. 

It could make sense to include the most common link types in the core item json spec. And add in derived_by there.

**Comment by m-mohr** [comment]
I think we should do that per spec and not globally. I think I'll come up with a template for the specs and extensions so that something like this has the same place and style everywhere.

**Comment by cholmes** [comment]
Ah, good thought. I was only really thinking about the 'core' stuff. Definitely makes sense to have a little place where extensions list it. A template sounds really great.

Could be nice to have some place where they all are listed, but that is two things to maintain. Maybe some point in the future we'll have an 'implementors guide'...

**Comment by m-mohr** [comment]
I gave it a shot with #202.

**Comment by m-mohr** [comment]
Is this sufficiently solved with #202, @cholmes?

**Comment by cholmes** [comment]
Yup, great work.
