### ISSUE TITLE
Create a generic 'dataset' specification, and use that to replace 'root catalog' concept.

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#194]
There was lots of good discussion at STAC sprint 3 and continuing in github after on collection / dataset level metadata. 

Not everything is 100% sorted out, but we're homing in on a some good consensus.

The 'dataset' specification will be a more formal definition of the descriptive fields of the catalog (defined by the static catalog in the first sprint, and not really revisited much). This will be its own mini-spec, in its own folder, and other projects like GEE and OpenEO will be able to reuse it. The bulk of this work is being done right now in #164 

This will likely replace the 'root catalog' concept in the static catalog, which was the idea that an item would link to the catalog that had meaningful information about it, instead of just the catalog organization that's immediately above it. 

This will likely also obviate the need for the collection extension, so #174 may just result in removing it, if dataset covers all the needs of it. 

Related issues + PR's
#81 #164 #35 #152 #137

**Comment by hgs-msmith** [comment]
I've attached a UML diagram as an attempt to summarize the different metadata model approaches we have discussed. We can use this during today's (9/24/18) conference call.

[STAC-model.pdf](https://github.com/radiantearth/stac-spec/files/2411240/STAC-model.pdf)

**Comment by hgs-msmith** [comment]
Here is an updated model - my attempt to incorporate the discussion during the 9/24/18 conference call.
[STAC-model-060.pdf](https://github.com/radiantearth/stac-spec/files/2438404/STAC-model-060.pdf)

**Comment by m-mohr** [comment]
Why is contact, provider etc still in the catalog? That's not the current state AFAIK. The catalog should just hold name, description and links (and properties?!). All tge additional fields in catalog belongs to the dataset.

**Comment by hgs-msmith** [comment]
Updated version, reflecting changes as of 11:00am EDT 10/2/18.
[STAC-model-060.pdf](https://github.com/radiantearth/stac-spec/files/2439252/STAC-model-060.pdf)

**Comment by m-mohr** [comment]
By the way, we may need/want to update the extents object later, see https://github.com/opengeospatial/WFS_FES/issues/168

**Comment by hgs-msmith** [comment]
Here is an updated diagram with the changes noted by @m-mohr: 
[STAC-model-060.pdf](https://github.com/radiantearth/stac-spec/files/2451595/STAC-model-060.pdf)

and +1 on pressing the extents updates with WFS.

**Comment by hgs-msmith** [comment]
Finally, when we are settled on the final 0.6.0 model, let's find a better place to this diagram.

**Comment by m-mohr** [comment]
Agreed - and this diagram will need some more work for the final 0.6.0 release (stac_version added to dataset, type added for provider, ...)

**Comment by cholmes** [comment]
Closing, as I think this is all in.
