### ISSUE TITLE
Add an optional 'image' field to the dataset spec?

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#196]
So STAC browser lets us do nice displays of catalogs, like http://planet-stac.netlify.com/

But the pages end up pretty bare. I was thinking it could be nice to add the ability to reference an image that represents either the provider or the dataset. I'm mostly thinking of a logo - like on the one above I'd put the Planet logo. You could also see a thumbnail representation of the dataset? 

Lots of ways to do this. Could have a 'provider image' in the provider section. Could have just an image link in the main section that people could use as they want. Could even just use a special 'rel' in the 'links' section, since it should be a link to an image.

**Comment by m-mohr** [comment]
Hmm, not sure whether that's really a core thing. I'd more see this as part of an extension. Not even sure whether that would be a general extension, which we could call 'design extension', 'customize extension' or so. It could also just be a "vendor" extension for/by the stac-browser.

**Comment by cholmes** [comment]
Yeah, you're right, an extension makes sense. And you remind me of my philosophy I try to get in to all extensions (which we've slipped from some), which is to start in implementations.

I'll close this and add to STAC-Browser, and can play with adding some there.
