### ISSUE TITLE
Rename repositories and relevant text to reflect naming choice.

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#20]
In the [Boulder Sprint](https://github.com/radiantearth/boulder-sprint) and afterwards in [Gitter channel](https://gitter.im/Imagery-Catalog-API-Team/Lobby?at=59f206b3e44c43700a7f3b0d), we decided on the general name of the catalog system specified in this repository to be __SpatioTemporal Asset Catalog (STAC)__. We need to update the repository name and relevant text to reflect this choice.

**Comment by cholmes** [comment]
All updated!
