### ISSUE TITLE
API queries: Case sensitive or insensitive?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#200]
We'll get nice query support for the STAC API with PR #167, thanks to @hgs-trutherford. During the review, we were wondering whether operators like startsWith, endsWith, contains and maybe even eq and neq should be case-sensitive or insensitive. 

I think case insensitive search gives better and more predictable results. You never really know whether people will write "landsat" or "Landsat" or "LANDSAT". Saw all of them in API implementations for openEO and we would only get one result with case-sensitive. Sure, case insensitive could be more work to be implemented.

**Comment by cholmes** [comment]
I lean more towards case insensitive.

**Comment by hgs-trutherford** [comment]
Since we are targeting a "simplified" search experience, I think case insensitive makes sense. We could also leave it up to the implementation, but with a strong recommendation towards insensitive.

**Comment by matthewhanson** [comment]
I agree with @hgs-trutherford here, we want a simpler and better user experience and the only reason to have case sensitive searches is if a provider wants to treat something like LANDSAT-8 and landsat-8 as different entities, which is not only unfriendly but also not sure what that difference would imply.

**Comment by cholmes** [comment]
Cool, sounds like good consensus. Anyone up for a PR? I think we just have to specify in the query string operators, should be an easy one. OpenAPI definition is at https://github.com/radiantearth/stac-spec/blob/dev/api-spec/extensions/query.fragment.yaml#L61

**Comment by m-mohr** [comment]
Should this be apply to all string based opterations? Especially curious about equals `eq` and not equals `neq`.

**Comment by m-mohr** [comment]
Made a PR, please review it.

**Comment by m-mohr** [comment]
Fixed
