### ISSUE TITLE
License issues (not the field, but actual licensing of STAC components)

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#201]
We have several documents, e.g. api-spec/definitions/STAC-standalone.yaml in #167  or some package.json files, that report other licenses than Apache-2.0, which is the license for STAC. Is there any reson for that or should that just be changed in a PR?

**Comment by cholmes** [comment]
No, they should all be apache. A PR to change those would be great.

**Comment by m-mohr** [comment]
Will make a PR after #167 is in.

**Comment by m-mohr** [comment]
Is included in the restructuring PR #202.

**Comment by cholmes** [comment]
This is merged, closing. Thanks @m-mohr !
