### ISSUE TITLE
README for the api generation tools.

### ISSUE THREAD

**Issue by hgs-truthe01** [radiantearth/stac-spec#203]
We should have a readme with instructions and a description of how the yaml fragments work.

**Comment by cholmes** [comment]
@hgs-truthe01 - wondering if you could take this? Or do we need more from @scisco ? Perhaps @matthewhanson can help.

**Comment by cholmes** [comment]
@mojodna - if you can take this on too that'd be great. May take a bit of detective work. But it'd be good to describe how to properly edit OpenAPI files to work for STAC and how our system builds them.

**Comment by m-mohr** [comment]
Done with #432.
