### ISSUE TITLE
Add README to describe the STAC domain model

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#21]
We need to generate some text for the README that describes the domain model of the STAC at a high level. Some components to be defined are:

- __SpatioTemporal Asset Catalog (STAC)__: This is the general name of the catalog system specified in this repository.
- __Item__: An _Item_ is contained in a STAC, and is described by a [OGC SimpleFeature](https://en.wikipedia.org/wiki/Simple_Features) (expressible as GeoJson) that contains the footprint and timestamps of one or more linked Items or Assets.
- __Asset__:  An Asset represents the final thing a Catalog can point to, such as a GeoTiff representing imagery, a laz file representing some lidar information, a metadata file describing other assets, etc.

We should potentially also include the concept for a STAC that was introduced by the Static Catalog working group [in the Boulder Sprint](https://github.com/radiantearth/boulder-sprint/tree/master/workstreams/static-catalog), namely the idea that a STAC JSON representation can point to other STACs, creating a tree of crawlable, hierarchically grouped STACs.

**Comment by lossyrob** [comment]
Working with https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md. @notthatbreezy will iterate on this over implementing a full NAIP example, and work on writing up the open api spec.

**Comment by cholmes** [comment]
This is outdated, and I think the core has been covered.
