### ISSUE TITLE
Multiple DOIs and citations in a single dataset

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#211]
There can be datasets with multiple citations (eg, https://developers.google.com/earth-engine/datasets/catalog/CIESIN_GPWv4_ancillary-data-grids). This can happen if one aggregated dataset has data from several smaller independent datasets. Ditto for DOIs - EE already has an example where each band in a single image comes from a different provider dataset, hence the EE dataset has multiple DOIs.

**Comment by m-mohr** [comment]
Could these smaller independent datasets described on their own with a sub-dataset? Then you can assign individual DOIs for each sub-dataset.

**Comment by simonff** [comment]
Yes, but by the time we look at them they may no longer be divisible into subdatasets. Example - two bands in an image where each band came from a separate dataset with a separate DOI.

**Comment by m-mohr** [comment]
But then, how would you tell a user which DOI / citation he needs to use?

**Comment by simonff** [comment]
If a raster image has two bands with two different DOIs, or a dataset has two images with different source DOIs, and the user uses both, they need to cite both DOIs.

Example: https://data.csiro.au/dap/landingpage?pid=csiro:9989&v=5&d=true and https://data.csiro.au/dap/landingpage?pid=csiro:11467&v=2&d=true are combined into one dataset in EE.

Allowing DOIs in individual items and bands might help here.

I think I have seen a case where different parts of the same final image had different DOIs (eg, data for different Australian states), but I can't remember where.

**Comment by m-mohr** [comment]
I think we basically have three options:

1. Allow the scientific extension to be applies to Datasets, Items, the Band Object and potentially more places (that sounds a little messy but very precise).
2. Just specify the DOIs and citations in an array in the dataset (same schema used as in publicatio_doi / publication_citation) and bein imprecise where exactly they belong to.
3. Ignore this issue and let providers come up with a single DOI/citation (probably the worst option).

**Comment by cholmes** [comment]
The first option sounds outside of what I see as the main philosophy, which is make a spec that is easy to implement and not super complicated, even if it can't fully represent everything...

So I'd lean more towards like number 3 for the core, and encourage an extension for people who have use cases that don't fit.

**Comment by m-mohr** [comment]
I think this is mostly solved by #260, which changed the scientific extension to be in the Item scope. This means you can add more fine-grained and in the end basically multiple DOIs into a dataset/collection. I'll close this for now, but feel free to re-open or comment if you feel this doesn't solve the problem sufficiently.
