### ISSUE TITLE
Dataset periods not representable via ISO8601

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#212]
In rare cases, a dataset has the period that cannot be represented in ISO8601. Two examples I've run into are CHIRPS pentads (http://chg-wiki.geog.ucsb.edu/wiki/CHIRPS_FAQ#How_does_CHIRPS_define_a_pentad.3F) and PDSI files (see https://www.northwestknowledge.net/metdata/data/early/2018/)

In both cases, there are multiple assets per month with duration 5 or 10 days, and the last asset covers the remainder - its duration varies from month to month.

**Comment by m-mohr** [comment]
ISO8601 was just a quick shot and I feared that there are strange values for periodicity out there. Not sure how we can handle that. Fall back to a simple string data type where you can put a description? That is the least desirable option though and we should try to find something better.

**Comment by m-mohr** [comment]
Issue is outdated as we removed dataset periods from the collection spec. In data cube we now have a "step" field for temporal data, which allows ISO8601 for regular spaced steps and `null` for irregular steps.  I'd say for other periods we need a custom field as Chris said.
