### ISSUE TITLE
Period for climatology assets?

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#213]
The normal periodicity does not quite apply to climatology collections that have, eg, 12 assets with average monthly temperatures for each month over the last 30 years. We can still use start and end with the difference of 30 years, and set "1 month" as perodicity, but there should be some way to indicate they don't contain data for each month within these 30 years.

In Earth Engine, we have an enum to choose between three kinds of periodic assets - truly periodic (eg, global weather data daily), those with revisit time (like Landsat) and climatology.

**Comment by cholmes** [comment]
I'm leaning towards saying just do this as a 'vendor extension' in GEE to start? Like do whatever feels best and publish a little extension on what you did. If others reuse then we can evolve it to be more widely used.
