### ISSUE TITLE
Collection type

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#214]
Datasets need a field for their type. Eg, in Earth Engine we have images, image collections and tables (vectors). It's one of the most fundamental properties, as some other properties may be present or absent depending on the type.

**Comment by m-mohr** [comment]
Depending on how we implement the extensions, we may determine that on basis of the extensions used. Could datasets also be mixed (e.g. raster + vector)?

**Comment by simonff** [comment]
Leaf datasets cannot be mixed, I think. If we decide to have multilevel datasets, higher levels can have children of different types.

**Comment by m-mohr** [comment]
This seems to be related to https://github.com/opengeospatial/OGC-API-Hackathon-2019/issues/8#issuecomment-503972655 and might therefore be backported to STAC.

**Comment by m-mohr** [comment]
Haven't backported it in #525 as it would be only "feature" for WFS and is optional. We could specify our own itemTypes, but would break with WFS. Therefore we may better come up with an additional property or rely on #278.

**Comment by m-mohr** [comment]
Decided on the sprint to be done in a custom extension (i.e. GEE already uses gee:type).
