### ISSUE TITLE
Resolution (eo:gsd) in arc degrees/minutes/seconds

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#215]
For low- and medium-res datasets, there should be a way to represent resolution of, say, 1 degree or 30 arc seconds per pixel. It's not enough to convert them to meters, as the conversion will be approximate.

**Comment by matthewhanson** [comment]
The conversion is approximate no matter the resolution of the dataset if the projection used is in units other than meters. The description for eo:gsd says "nominal" resolution, this should be the resolution at the scene center.

The reason for including it in meters is the same reason why we don't give bounding box in native projection units. STAC is primarily for discovery of data and users will want to search and see in terms of meters. If as a user you want the actual resolution in projected units you will also probably want what the projection is (which will indicate units) and that is not part of the spec. For now they will have to download the original Item metadata or the data itself to get that info.

I don't think it's a good idea to add another field for specifying resolution units. If we do want to provide that information it should be by providing the entire CRS string, which was originally part of the spec but we dropped it as it didn't seem useful for data discovery.

Using a real world lower res dataset, MODIS is in a sinusoidal projection with resolution units in degrees, but all of the resolutions given in the MODIS product table are in meters. Most users know the resolution is approximately 500meters (or 250m for Bands 1-2), even though it varies by latitude. I can't tell you what the res is in degrees, somewhere around 0.005 or so I think, and I've been using MODIS for over 10 years.

**Comment by m-mohr** [comment]
This could also be something for our ingestion extension that we mentioned in #217.
@simonff Maybe we should make an issue on that one and collect what doesn't seem to be suitable for the core, but for a separate extension.

**Comment by cholmes** [comment]
Closing this, don't think we'll support this. Could be done in an extension.
