### ISSUE TITLE
eo:platform and eo:instrument may have multiple values

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#216]
eo:platform and eo:instrument are not necessarily single-value fields. Eg, for MODIS MCD* datasets platform is MODIS Terra + MODIS Aqua, and for combined Sentinel-1 or -2 data the platform is both S1A/S1B etc. As for the instrument, Landsat 8 has both OLI and TIRS instruments, and the main L8 product has bands from both.

**Comment by m-mohr** [comment]
We have a similar problems with the licenses and tried to solve it by using SPDX license expressions which allows something like `Apache-2.0 OR CC-BY-4.0`. I'm not suggesting that we use exactly this, but I think both fields mentioned by you should somehow stick to be strings as they are used inside the Items properties as well, which are not allowed to hold arrays or objects. Therefore we may just add a recommendation how to generally separate fields with multiple values, e.g. `|` or `/` or `;`.

**Comment by cholmes** [comment]
I like @m-mohr's thinking on this. Having a single value field to search on makes things a lot easier / gives us a simpler spec. 

Also I think 'constellation' in #169 was also supposed to somehow help S1A vs S1B, though I still need to see more concrete examples to really understand it.

**Comment by m-mohr** [comment]
By the way, the eo extension already has a paragraph on this: 
> eo:instrument is the name of the sensor used, although for Items which contain data from multiple sensors this could also name multiple sensors. For example, data from the Landsat-8 platform is collected with the OLI sensor as well as the TIRS sensor, but the data is distributed together and commonly referred to as OLI_TIRS.

This could be improved, for sure, e.g. by describing how multiple values should be separated.

**Comment by m-mohr** [comment]
For collections and catalogs it is solved with the summaries as proposed in #413. For Items, I think need further evaluation.

**Comment by m-mohr** [comment]
So the summaries now allow this for collections. The question here is whether there are really many Items that have multiple values for platform and instrument? Usually Sentinel-2A and Sentinel-2B images would be a separate items. And for "merged" imagery/mosaics/... I'm not sure whether it's worth the effort to change anything here. It could just be a string such as "Instrument1 + Instrument2" or so. Anyway, I think we should come to a decision before 1.0.
