### ISSUE TITLE
Representing non-EPSG projections

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#217]
The CRS might not correspond to an EPSG code (eg, for MODIS we hadd to add http://spatialreference.org/ref/sr-org/modis-sinusoidal-3/). There should be a way in the eo: extension to allow specifying a WKT string, for example.

**Comment by m-mohr** [comment]
We had this discussion within already, at least in #111 and maybe in another issue/PR, too. Most people see STAC designed for searching and you'd not really search by WKT/Proj4 strings so it was removed. But I certainly agree, that for a full description it would be required. I think, this could be something for a separate vendor/provider extension.

**Comment by simonff** [comment]
Yes, fill value and CRS are only important when someone needs to ingest the data. Normally GDAL encodes them anyway, but at GDAL level they can be missing, wrong, or unencodable (GDAL can only have one fill value per band, and not all WKT parametes can be saved in geotiff metadata).

**Comment by m-mohr** [comment]
That leads me to the question: Should we put all things that are mostly only relevant for ingestion in something like an ingestion extension? There are probably some more properties in the current specs that are relevant for such an extension.

**Comment by cholmes** [comment]
Yeah, Matt brought up the MODIS thing as the reason we originally did CRS and not EPSG. But it was a big pain to actually use. I tried to do it for my Planet sample, looking up the CRS for the EPSG code but then got stymied by all the special escape encoding I needed to do to get it into JSON so just gave up. So we decided that for known non-EPSG things we could just try to push a 'vendor epsg' - like you're allowed to use EPSG values above some amount as you want. 900913 for web mercator was done that way (and eventually got 3857 in the official database). So we could do that for MODIS.

I don't see a big downside to making an optional CRS field if people want to use it. But maybe just start it in a vendor way - use in GEE, etc. Like in general for dataset I think our goal should be to get to a solid core that others can extend. Not to handle every single thing that the most advanced structures need. Now obviously we want the core to have the flexibility to handle everything a super advanced catalog could do. But I'd say remember that as we make decisions about what should be in 'dataset'. Goal for me is not to have GEE catalog fully represented by what's in the core of dataset, but to cover the most common use cases and be easily extended.

As for the 'ingestion extension' - yeah, that sounds great, and is in line with what I just articulated. For things that feel a bit custom it'd be best to put them in their own little area, and not have 'core' end up as a 200 page spec, like everything else in our field. Let's get a nice self-contained core that's a minimum level of interoperability, and then a great ecosystem of best practices / extensions.

**Comment by m-mohr** [comment]
See PR #485

**Comment by davidraleigh** [comment]
@m-mohr, I was thinking about this comment by @geospatial-jeff:
https://github.com/radiantearth/stac-spec/issues/722#issuecomment-583625507

@geospatial-jeff just a question about the LTP. Could you use a custom Lambert Azimuthal Equal Area projection? 

I use LAEA and oblique mercator often and I wonder if a way to work with custom projections and staying in compliance with the "REQUIRED" quality of the `proj:epsg` field would be to use `proj:epsg` to describe the complete coordinate system **or** the method of projection. For instance in the case of a custom Lambert Azimuthal Equal Area projection method you could define projection as follows using the [9820 epsg code](https://epsg.io/9820-method):
```json
{
    "proj:epsg": 9820,
    "proj:proj4": "+proj=laea +lat_0=-112.9 +lon_0=-33.3 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
}
```

The nice thing here is that it still allows for discovery via `proj:epsg` even in the case of custom projetions. If I'm looking for all my LTP / LAEA, I could search by 9820.

I guess all I'm proposing is that we could amend the documentation to suggest the possibility of using the `proj:epsg` for coordinate system **or** in the case of custom projections, the projection method epsg code.

**Comment by m-mohr** [comment]
I'm not sure, I think things should be unambiguous. At the moment you can set epsg to null if no suitable code exists and then use wkt2/projjson to specify the custom projection.

This PR should have been closed already with the introduction of the proj extension. Maybe your proposal is better placed in a separate issue?

**Comment by davidraleigh** [comment]
Ahhhh, never mind @m-mohr . I didn't know that the field could be set to null and still be valid. Somehow I thought that would go against the **Required** quality for `proj:epsg`. Sorry for the misunderstanding, feel free to close this issue!
