### ISSUE TITLE
For raster bands: eo:common_name -> eo:name

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#218]
The term "common name" is too specific for optical bands and does not make sense for other raster data (eg, DEMs or preciptiation). Just "name" should be enough. We can require using one of the predefined common names ('red' etc) when applicable.

**Comment by m-mohr** [comment]
I think this may depend on the outcomes of #142 as we may need the key "name" for the actual name of the band and the "common_name" that is really a commonly used name. Also, I am not quite convinced as the common name might not be the actual name of the band so the key may be misleading?!

**Comment by simonff** [comment]
Yes, 'common_name' is not quite appropriate. It's actually something like 'common_meaning'. Or maybe 'standard_color_name'?

**Comment by m-mohr** [comment]
I'll leave this open to be decided by native speakers as to me as a non-native speaker `common_name` sounds quite right.

**Comment by hgs-truthe01** [comment]
I think #247 closes this issue? name and common_name are separate values.

**Comment by m-mohr** [comment]
I agree.
