### ISSUE TITLE
Decide on an Item <-> Asset linking structure.

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#22]
At the end of the Boulder Sprint, we came up with a number of ideas for linking together Assets and Items. We need to finalize that linking concept and codify it into the spec.

**Comment by lossyrob** [comment]
One idea is what was present in the diagram below, and was codified in [the NAIP example hacked together at the Boulder Sprint](https://github.com/radiantearth/boulder-sprint/tree/master/specs/core-api/naip-example):

![20171025_120214](https://user-images.githubusercontent.com/2320142/32201312-b614d1ba-bdac-11e7-90b0-395a30b037fc.jpg)

- Items contain `links`. Links are an object that contains at least a `rel` and an `href` property. 
- The `rel` describes the relationship of the link to the current Item. 
- The `href` points to either an `Item` JSON, an `Asset` JSON, or the bare asset itself (e.g. a GeoTiff). 
- `rel=asset` links can have additional properties that describe the asset, such as `format` or `product`. These would be inlining the Asset json directly into the link, in which case the href points directly to the asset file.

In this way, we can have `links` handle both assets and other links (such as thumbnails). Thoughts?

**Comment by lossyrob** [comment]
Proposal described [here](https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#rel-links) and [here](https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#item)

**Comment by cholmes** [comment]
Closing this, decision was made to not get too crazy with items that only contain assets and not other metadata. Though there likely are some good use cases to model things in Item hierarchy more. But it's not the core recommendation at this moment.
