### ISSUE TITLE
Specify state how mature extensions and specs are

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#220]
We should add some classification to extensions and spec pages stating how mature they are.

Copied over from #202 (@cholmes):
> I think it'd be good to have a bit more guidance on how mature the 'official' collections are. I'd either do four categories - 'official', 'incubating', 'vendor' and 'proposed', and likely not put anything in 'official' yet, but explain that they are mature extensions that have been implemented in X number of catalogs / software and will aim to not change any fields (though could add).
> 
> Other route, which I'm totally fine with too, is to add a field to the table called 'maturity' or something, with a few classifications - like 'alpha', 'beta', 'stable' or something. I think we could introduce some metric, like 'number of implementations' if we want it to be more quantitative.

and

> On the 'maturity' front I think we should also make it pretty obvious near the top of each individual document how 'mature' it is. The start end date time spec is pretty immature - we just put it out and there are no implementations of it yet. It'd be good to make it clear that people are using something that is not super widely accepted yet. This can help them prioritize which extensions to actually make use of, etc.

**Comment by m-mohr** [comment]
The vendor level could also be called candidate. Candidate of getting official. But that's just a quick idea. Community sounds also fine, but we could also divide them in community and official with each having the four levels of maturity.

Vendor (or community) was exactly meant as (usually) being proposed by others from external sources and I think the levels before should also be vendor/external. External extensions could also be in a branch in this repo, but can be linked from our master/dev branches in the vendor table.

But your suggestions sounds also like a good way of handling it. I'd give my +1 on both.

**Comment by cholmes** [comment]
Closed with #254
