### ISSUE TITLE
Naming of the STAC Start End (Date)time Extension Spec (`set`)

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#221]
In a recent PR (#202) I changed the name from the "STAC Start End Time Extension Spec (`set`)" to "STAC Start End Datetime Extension Spec (`set`)" as it actually describes datetimes and not times and we were very strict about separating these concepts.

Now I am wondering whether this name is really a good choice and the prefix doesn't really fit any longer.

I think it could be a good idea to change the name, I actually never really liked it and would suggest to rename it to something like date(time) range / period or so and choose the prefix accordingly. If we want to stick with Start and End Time Extension, the prefix would be `sed` or `sedt`.

**Comment by cholmes** [comment]
I'm fine for a name change. I still feel a bit weird about this extension, as we don't yet have concrete examples of things using it. If we had a 'maturity' class for this I'd call it 'idea'. It does seem good to have some recommendation for people to try out. But I really like the idea of not bringing stuff in until it really has a number of concrete implementations. Perhaps we could have 'extensions' and 'incubating', or maybe 'incubating' as a folder under extensions.

**Comment by matthewhanson** [comment]
This has been merged
