### ISSUE TITLE
Harmonize values in eo:platform / sar:platform

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#236]
I think it's a good idea to harmonize the values in eo:platform as most as possible so that a search on this field gives better/more predictable results. I'd suggest adding a recommendation to follow a list of platform names (see below).

This issue is inspired by the CEOS OpenSearch best practice document and our product name issues in openEO (https://github.com/Open-EO/openeo-api/issues/52).

In an older version (1.1 D3) they had this ToDo (cited for the potential lists of platform names): 

> OpenSearch servers supporting collection (or granule) search based on satellite name are
recommended to pass the satellite name via the {eo:platform} search parameter defined in
[OGC 13-026r5].
> To avoid name mismatches (e.g. "SPOT 5" versus "SPOT5" versus "SPOT-5" or "SEASAT 1"
versus "Seasat"), implementations are encouraged to support names as defined in TBD.
> 
> NOTE 3 – Harmonised platform names?
> This TBD above should be replaced by a reference to a recommended naming. Candidates are:
> * GCMD Platforms: See skos:prefLabel of the platform as defined in
http://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.rdf (e.g. "SPOT-5", "SEASAT
1")
> * The CEOS Database: See http://database.eohandbook.com/database/missionindex.aspx (e.g.
"SPOT-5", "SeaSat")

Source: [CEOS OpenSearch Best Practice Document Version 1.1D3, page 29](http://ceos.org/document_management/Working_Groups/WGISS/Documents/CEOS-OPENSEARCH-BP-V1.1D3.pdf)

In the most recent version they have decided to go with the NASA document:
> OpenSearch servers supporting collection (or granule) searches based on satellite name are
recommended to pass the satellite name via the {eo:platform} search parameter defined in [OGC
13-026r8].
> To avoid name mismatches (e.g. "SPOT 5" versus "SPOT5" versus "SPOT-5" or "SEASAT 1"
versus "Seasat"), implementations are encouraged to support names as defined in the SKOS
description of satellite and missions is in the Global Change Master Directory (See skos:prefLabel
of the platform as defined in http://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.rdf).

Source: [CEOS OpenSearch Best Practice Document Version 1.2, page 32](http://ceos.org/document_management/Working_Groups/WGISS/Interest_Groups/OpenSearch/CEOS-OPENSEARCH-BP-V1.2.pdf)

**Comment by m-mohr** [comment]
Should we recommend to align platform (eo/sar) with https://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.json and instrument (eo/sar) with https://gcmdservices.gsfc.nasa.gov/static/kms/instruments/instruments.json?

**Comment by matthewhanson** [comment]
Related to new issue I posted #555

**Comment by m-mohr** [comment]
I think this will be somewhat obsolete once we have the sat:platform_international_designator defined in #894
