### ISSUE TITLE
Finalize Item and Asset JSON

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#24]
At the boulder sprint, we have a good stab at working through the Item and Asset JSON specs, including some [examples of how they would be applied to different cases](https://github.com/radiantearth/boulder-sprint/tree/master/specs/core-api). We need to discuss all of the details, including #22 and #23, and move all examples to be in line with the specification we have created.

**Comment by lossyrob** [comment]
There is a structure proposed [here](https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#item) and [here](https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#asset) - this is missing some core metadata that I think will be fleshed out once we start implementing examples. However as far as the elements of the STAC and the structure of the Items and Assets as far as linking and top level characteristics should be encapsulated there.

**Comment by cholmes** [comment]
Merged in #37
