### ISSUE TITLE
Categorical (landcover) bands

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#242]
For categorical (landcover) raster bands, each pixel value is usually associated by the provider with a color (RGB color string or a common name) and a human-readable string explainig the meaning of the value.

Example:
0, black, ocean
1, blue, freshwater lake
2, 0000dd, river
...
255, aabbcc, urban

This can be represented by list of object named, say CategoricalValue. Each object has an integer field for the pixel value and two string fields. The color field can be optional.

**Comment by m-mohr** [comment]
This should be covered by the new classification extension: https://github.com/stac-extensions/classification
