### ISSUE TITLE
Linking to specific versions of the spec

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#244]
Now that I am introducing STAC to openEO, it would be good to have stable links to specific versions of the API. Currently, it is only possible to link to master, but with a new versions these documents may disappear or change its location.

In openEO we generate the documentation based on branches and then have a stable version generated on GitHub pages, e.g. 
* version 0.3: https://open-eo.github.io/openeo-api/v/0.3.0/index.html
* version 0.0.2: https://open-eo.github.io/openeo-api/v/0.0.2/index.html

Maybe that's an option here as well.

**Comment by hgs-truthe01** [comment]
@cholmes has been tagging each release. Would a URL like this work for you?

https://github.com/radiantearth/stac-spec/blob/v0.5.1/api-spec/STAC-standalone.yaml

**Comment by m-mohr** [comment]
Oh, interesting. I wasn't aware that you could that easily link to source code of a released state - yes, that helps a lot, thanks!
