### ISSUE TITLE
Detailed Use Cases

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#246]
In our meetup today it came up that we all have use cases, and each one provides valuable information on how we want to use STAC.

Please post your use cases here, for eventual inclusion into the STAC repo.

cc @m-mohr @hgs-msmith @hgs-truthe01 @joshfix

**Comment by m-mohr** [comment]
We would like to use STAC for openEO.

openEO is about cloud-based processing of EO data based on a data-cube like view: You can select a dataset, send your processing instructions to a cloud provider and get a result, you don't need to know about items. The provider selects the right items for you. This means that there are not necessarily items/assets listed in our catalogs, but providers may choose to list them anyway and they can do so thanks to STAC. 

Currently, we are using the new dataset spec and several STAC extensions to describe our datasets (see the [API reference](https://open-eo.github.io/openeo-api/v/0.3.0/apireference/#tag/EO-Data-Discovery/paths/~1collections~1{name}/get)). As we don't require providers to list their items, all (useful) data needs to be described at the dataset level, e.g. extents, provider information, license, bands, EPSG code etc. On the other hand, Cloud cover would probably be not very useful. So there are still some issues to be solved.

cc @simonff

**Comment by simonff** [comment]
As far as Earth Engine is concerned, I'd like to see the data providers annotate their data holdings in a standard way to make it easier for us (and the community) to create automated tools for browsing datasets and mirroring data into EE.

**Comment by dlindenbaum** [comment]
SpaceNet Use Cases:

1. Represent a Cloud Based Area of Interest Data stack

In this case, I would like to use STAC to describe all the data available in an area of interest.  This would allow for easy documentation of all data available to a user in a given environment/ Geographic area of interest.  This would allow for easier data management  of data stacks that have multiple providers.


2.  Machine Learning Data stack   
I would like to use STAC as a basis for describing a computer vision based machine learning dataset.  This type of dataset would allow for easy creation / iteration on machine learning models for application against large amounts of raster data.  There are currently specifications for non spatial temporal datasets but they then won't translate back to the source material.
