### ISSUE TITLE
Update OpenAPI definition to catalog / dataset definition

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#257]
The OpenAPI definition still has the old Catalog definition, with keywords, provider, etc. See https://github.com/radiantearth/stac-spec/blob/dev/api-spec/definitions/STAC-standalone.yaml#L328 (though I'm not sure if that's where the spec is defined or if that file is built from others). 

It should be updated to be in line with what we have in dev for catalog. Could have the return example be a dataset, to show a fuller return. 

Should also try to communicate a bit more in that OpenAPI snippet, like that /stac can be a catalog that links to other catalogs, or a dataset definition, or even alternate 'views' in to the data.

**Comment by m-mohr** [comment]
Let's make this once we have #262 fully in. It's a bit of work to be done and I'd like to have that PR finalized first.

**Comment by cholmes** [comment]
Sure, no problem - I just wanted to be sure the issue was in so it's sure to get done.

**Comment by m-mohr** [comment]
I'm still waiting got #268 and #269 to get discussed and merged as these also require changes in the API.

**Comment by m-mohr** [comment]
Should be updated with PR #271 , but needs to be reviewed carefully due to the huge amount of changes.
