### ISSUE TITLE
Move static catalog and relevant examples from boulder-sprint repo.

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#26]
https://github.com/radiantearth/boulder-sprint/tree/master/specs/flat_file has lots of great info, it should be ported to this repo, and updated to fit with the latest decisions from #22, #23 and #24 as those are figured out. Would be great to preserve history, but not required.

**Comment by lossyrob** [comment]
Work for this is going on in the feature/add-flat-file-spec branch. @notthatbreezy is picking this up and completing the openapi spec and NAIP example.

**Comment by cholmes** [comment]
Done, in #37. @lossyrob's feature/add-flat-file-spec branch was incorporated there. Thanks!
