### ISSUE TITLE
Change asset name to title

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#263]
As discussed in #262: I would propose to change the asset field `name` to `title`. Currently it seems it is usually used for a title and not for an identifier. Name itself is ambigious and it is not really clear whether it should be a identifier or a title.

**Comment by cholmes** [comment]
+1

Let's get this change in asap.

**Comment by m-mohr** [comment]
PR #269 implements this.

**Comment by m-mohr** [comment]
Merged - closing this issue.
