### ISSUE TITLE
Define recommendations on schema validation for Items

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#264]
It'd be good to have a recommendation for an Item to optionally link in some way to its JSON schema and/or the extension schemas it complies with.

This should be totally optional, but would be good to help provide more meta-information. Likely would make sense to have a recommended slot at the dataset level. And also a way to easily refer to the extensions that an Item implements. 

Ideally this would be defined in WFS 3, so perhaps we can file an issue there too and look to them for leadership.

**Comment by m-mohr** [comment]
The proposal we have for "extensions supported" in #278 would allow this.

**Comment by m-mohr** [comment]
I think this is now available via extensions_supported.
