### ISSUE TITLE
description for links

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#283]
description would be a useful optional field for links. While it wouldn't be used for parents, children, and collections, a provider might want to add a description for links such as user manuals or related data.

**Comment by m-mohr** [comment]
We introduced titles for links in this release. Could this be enough or is there a need to add an additional description? Maybe just implement it and then we'll see whether it seems to be a good idea for adoption in 0.7 or not?

**Comment by matthewhanson** [comment]
Ah ok, title - I missed that. That's probably sufficient I think. I don't think a long description is needed, just some way to better specify what the link is if it's not a simple link to catalog, collection, or parent.
