### ISSUE TITLE
Further refine and describe eo:constellation

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#284]
*Split from a discussion in #282.*

I still don't really understand what the `eo:constellation` field should contain. How do I determine what to add there? We should clarify what this field is about, better describe it and maybe give rules and more examples.

An nice write-up from @matthewhanson in #282:
> I'm not completely sold on this field either.
>
> One of the most obvious use cases is Planet's Doves, since they are meant to operate together to get daily global coverage. A single Dove might have a unique identifier, the instrument is the same on all of them (but maybe not, perhaps some have NIR bands and others do not), but they all operate as a constellation.
> 
> With MODIS we have 2 platforms (Aqua, Terra) with the same instrument (MODIS). Does it help to tie the two platforms together as a constellation?
> 
> For VIIRS there will be multiple sats, all carrying the same VIIRS instrument.
> 
> For Landsat there are multiple platforms: Landsat-7, Landsat-8, which have different instruments (although 5 and 7 have the same ETM+ instrument). Is it helpful to be able to search the constellation of all Landsat sats regardless of platform or instrument? Maybe.
> 
> For Sentinel there are 2 platforms, soon to be 3, all with the same instrument....sort of. There actually are slight differences in some of the spectral band edges for at least a couple of the bands between the MSI on 2A and the MSI on 2B. So these maybe should be two different instruments. In which case it would be useful to search across all the Sentinel-2 platforms and eo:constellation would be a good way to do that.

**Comment by fredliporace** [comment]
For me this makes sense when you have the same instrument in distinct satellites with similar orbital characteristics and arranged in a way to improve the temporal resolution for acquisitions with the same (or very near) spectral/spatial characteristics. Sentinel 2 A/B and RapidEye are the examples that come to my mind.

**Comment by m-mohr** [comment]
Great, @fredliporace . Could you come up with a good description for the field? And a recommendation how to "construct" the value of the field?

**Comment by fredliporace** [comment]
@m-mohr will do. Since the milestone for this is 0.7 I'll work on that after completing the CBERS repository migration to 0.6.

For future reference [this](https://www.esa.int/Our_Activities/Observing_the_Earth/Copernicus/Sentinel-2/Satellite_constellation) is how ESA refers to Sentinel-2 as a constellation of two satellites.

**Comment by m-mohr** [comment]
@fredliporace The milestone was set by me more or less arbitarily, but now that we are heading for a 0.6 RC2, we could also improve it in that milestone. It's up to you.

**Comment by m-mohr** [comment]
This was actually tackled in 0.6. Now we need to check whether this is suitable and further refine in 0.7 if required.

**Comment by matthewhanson** [comment]
Re-reading what I wrote in #282  I think there are enough examples where the platform and instrument might vary but you want to group them together, and this is likely to be more common with more cubesats getting launched.

I'm going to close this, feel free to reopen if you think this needs further discussion.
