### ISSUE TITLE
Asset schema / Further refine adding additional metadata to the asset definition

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#289]
*Taken from the old catalog recommendations.*

**Asset definition**

It is of top priority to provide definitions of assets, so clients can know get some information as to 
what is actually contained in the data they are downloading. Assets should contain the metadata that is 
specific to the format of the asset. The asset must have some way to state its format. 

While assets in Catalog APIs can easily represent files that are generated on demand, a static
catalog should only list assets that already exist online. This increases the reliability and speed
of the catalog and makes it easier to fully duplicate or back-up a static catalog.

**Note:** 0.6.0 defines Media types for assets, to provide more information about what is to download, but there is likely
more work to be done to fully define the asset, so providers should feel free to experiment and give feedback on potential asset improvments.

There are a couple of ideas on how to define metadata for assets. Providers could either

* include a number of optional metadata fields directly in the asset that would provide additional definition for clients or
* include a field that specifies a URI to a (JSON) file that has the additional metadata.

When adding the data via a URI, all the needed metadata for a client would be in the product level definition,
which would mean a lot less repeating of fields. But clients would have to be a bit smarter to actually follow the links.
Though ideally clients would be able to cache and reuse product definitions, and hopefully there would be a small number
of canonical product definitions online, that all static catalogs using a particular provider would be able to reference.

**Comment by m-mohr** [comment]
Related to #153

**Comment by m-mohr** [comment]
Do we need to move anything from this old best practices to the new best practices, @cholmes ?

**Comment by cholmes** [comment]
Closed with #552
