### ISSUE TITLE
Update api spec to reflect general spec structure

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#297]
From #205 - 'Separate into api-spec.md and README.md (see Item spec)'

Right now it is just all in the readme. There are some bigger structural things that may make sense to do as well, like shifting from 'api' to 'search', and including the stac/ endpoint in the catalog section. But that should be discussed, and then the api doc build system would need some work.

**Comment by m-mohr** [comment]
Done with #432.
