### ISSUE TITLE
 Format all examples using the same style

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#298]
From #205 - this didn't quite get accomplished: 'Format all examples using the same style, e.g. by using https://jsonformatter.org/'

Would be good to do this before 0.6.0 final release. Is fine to do as it is no change to the spec. Would be great to also get a formatter for the examples and maybe json schemas as well in to continuous integration.

**Comment by m-mohr** [comment]
I think we should enable JSON linting for the examples and schemas in the CI rather than let the CI reformat the code automatically. There should be a script that lets contributors check it. This could be combined with validation in a single script for CI and standalone usage before PRing things.

**Comment by cholmes** [comment]
Cool, that approach makes good sense.

**Comment by scisco** [comment]
Will do this after the content and api are separated to their own repos.

**Comment by cholmes** [comment]
@scisco - we're split now, any chance you could tackle this in the next few weeks? Is in line with #704 - would be good to get everything clean for beta1

**Comment by m-mohr** [comment]
That's probably something we could easily do for 1.0.0 final, it's just polishing things up.

**Comment by scisco** [comment]
I can tackle it in the next few weeks. Although, Matthias suggests we should not do it at this point.

**Comment by m-mohr** [comment]
I'm just thinking that doing it now would lead to duplicate work as we'd need to check it now and would probably check it again for final.

**Comment by scisco** [comment]
yeah, it totally make sense.

**Comment by cholmes** [comment]
Cool, sounds good. I'll set this for 1.0.0-RC1, as that seems like the right time to do it.

**Comment by m-mohr** [comment]
I guess the best idea to do it together with #821? Maybe I can also include a small switch into stac-node-validator so that it's also linted during validation...

**Comment by cholmes** [comment]
Yeah, definitely makes sense to do this after or as part of #821, so we're not fixing a bunch of examples we may throw out.

**Comment by cholmes** [comment]
And yes, any tooling to help format and validate would be great to have.

**Comment by m-mohr** [comment]
Re styling, I'd say the default should probably be what JavaScripts `JSON.stringify(value, null, 2)` returns?! Then I could quickly implement it in node-validator and then we could probably also just do it whenever we want as it's done automatically. Give me a week-end... ;-)

**Comment by cholmes** [comment]
Yeah, that sounds good. I have no real preference on the style, just want something consistent, that is easy to apply. No rush on my end, I've got lots of tickets to take...

**Comment by m-mohr** [comment]
See PR #941

**Comment by m-mohr** [comment]
This is basically done.
