### ISSUE TITLE
Add schema responses to catalog api

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#30]
Add the mechanism to return the json schema for the returned data to the swagger API

**Comment by cholmes** [comment]
@joshfix - where did we end up with https://github.com/radiantearth/stac-spec/blob/dev/proposed/core-api-schema.yaml ? 

I think maybe we should wait on @lossyrob with the static catalog, to make sure things are in line, and I can't remember if we're doing a schema there. But seems like a sensible thing to have.

**Comment by joshfix** [comment]
@cholmes this was a contribution by Ryan. There was some discussion about how much schema info should be included in actual responses from the api, if any,  and I'm not entirely sure we had a consensus, but we left it with this. Basically if you want schema info, you need to hit the schema endpoint. There hasn't been any review of this document whatsoever, but I'm happy to wait and update this with what comes out of the static catalog schema.

Side note, why wouldn't we have a schema for the static catalog?

**Comment by osialr** [comment]
I put in the schema types as a starting point on discussion. However, I think JsonSchema can express a lot (all?) of what I was aiming for.  We could change that part to simply say "returns schema as  JsonSchema version X"

**Comment by cholmes** [comment]
Moving this to a 'future' milestone. With alignment with WFS this should likely just be a reference to how WFS does JSON schema, or does this with OpenAPI, but I'm not sure if that's locked in yet. 

cc @cportele - Is there a section of WFS spec yet on the openapi stuff you were talking about? And like the 'schema' extension? I think for STAC we'll pick just one way to do it.

**Comment by cportele** [comment]
@cholmes - The related schema issues are/were discussed here: 

* Schemas for features: https://github.com/opengeospatial/WFS_FES/issues/56;
* Schemas for the WFS responses: https://github.com/opengeospatial/WFS_FES/issues/58 (for XML schema, I know, not relevant for STAC). For JSON, the schema is in the OpenAPI definition.

**Comment by m-mohr** [comment]
Is this still relevant? WFS asks for an optional link only (see https://github.com/opengeospatial/WFS_FES/issues/236).

**Comment by matthewhanson** [comment]
I don't think this is relevant anymore. We should stick with whatever WFS does.

Closing.
