### ISSUE TITLE
change provider 'type' to 'role'

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#302]
Discussion on gitter seems to agree that 'role' is a bit more descriptive for the provider array.

**Comment by matthewhanson** [comment]
+1

**Comment by m-mohr** [comment]
Another question that was raised by @mojodna : How to specify the licensor. Therefore I propose to add a role licensor and make the type/role/roles an array. 

Example:
```
  "providers": [
    {
      "name": "European Union/ESA/Copernicus",
      "roles": [
        "producer",
        "licensor"
      ],
      "url": "https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi"
    }
  ],
```

Made a PR: #303.
