### ISSUE TITLE
Add Asset information about the use of the assets.

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#309]
> Relationship between the current document and the linked asset. See chapter "Relation types" for more information.

`rel` is currently implicit in the object key (e.g. `thumbnail`), but should also be included in individual Asset definitions, especially since they may be duplicated, e.g. multiple "analytic" sources.

This would help with #308.

If this is a good idea, I can put together a PR for it.

**Comment by m-mohr** [comment]
I think this is something we could add better in 0.7.0 and decide together with the discussion on asset dict vs. array and the proposed asset schemas in collections.

I think between release candidates we should try to not add too many new 'features'.

**Comment by cholmes** [comment]
Yeah, this does seem like a good idea to me, but similar to what @m-mohr mentions, it leaves me wondering again about array vs dict. Part of the appeal of the dict to me is that the key would be the relationship. So if we need another field that will be the same for most implementations then that's less appealing. I was imagining we would just discuss asset definition in 0.7.0, but I suppose it does make sense to revisit array vs dict for asset in that context. But I do think that will truly be the last time we can change this one.

I am switching this to 0.7.0, though I'm open to arguments it should be 0.6.0-RC2. But seems like we should think it through more thoroughly.

**Comment by matthewhanson** [comment]
I do not think it should be in 0.6.0-rc2. It's part of the larger discussion of asset definitions, which also includes the whole dict VS array chat.

I personally would like to see more examples beyond thumbnail for which a rel type would be used. Because otherwise I see the asset key as serving this purpose. 

I don't think multiple thumbnails is a great argument for it, because we still want to know which specific thumbnail to serve up automatically. Additional non-standard thumbnails can be specified as such via the key (e.g., thumbnail-1, or thumbnail-swir) as well as the title field.

**Comment by matthewhanson** [comment]
I don't think 'rel' type is what we after here.  I can see the need for describing something as a visual asset, or a thumbnail, or an analytic asset, or metadata, but that seems different that what 'rel' is after, and I wouldn't want people to go and use all of the IANA rel types here.

I perhaps see a related field, like "type" which would have an enumerated list:

- thumbnail
- visual
- preview
- analytic
- qa
- metadata

**Comment by m-mohr** [comment]
Agreed. Throughout the spec we usually use type for media types, so I would use another keyword. Maybe something like use or application makes more sense. Native speakers, please propose better words if there are any. ;)

**Comment by matthewhanson** [comment]
Ah yes, and this is an asset, so there is already 'type' in that same object.

I'm not sure what else makes sense: 'class' although that tends be used a lot and maybe not descriptive.  I think 'archetype' accurately describes what we are after here, but not sure people would like that.

**Comment by m-mohr** [comment]
I have never heard `archetype` in my life before, neither did my colleague. We're both not native speaker, so for us it would not be intuitive. That's why I proposed simple words as use or application.

**Comment by matthewhanson** [comment]
That's too bad, archetype is a great word to use here, but probably too obscure for non-native speakers.

Will think on it.

**Comment by cholmes** [comment]
Changed the name of this issue, and moved it to 0.9.0

**Comment by m-mohr** [comment]
Solved with #651
