### ISSUE TITLE
Consider z axis

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#35]
We should consider if height is also part of geometries in STAC, and either explicitly say it's not or make sure that an extension mechanism can handle it, or that it's just ok with geojson definitions.

**Comment by m-mohr** [comment]
I think that could be an important one if we want to cater for all domains especially such as meteorology.
For the datasets we specified a dimensions extension. I am not sure whether that really fulfills all needs yet. What about items?
I already heard voices within openEO that were not very comfortable with GeoJSON as it doesn't allow the z-axis to be specified.
Do we have any expert that we could consult regarding this?

**Comment by matthewhanson** [comment]
GeoJSON does allow for an optional 3rd dimension to allow for altitude @m-mohr and this will be needed for a point cloud extension cc @hobu

**Comment by m-mohr** [comment]
Oh, interesting, thanks for pointing that out. Never saw that in the wild yet, but you are certainly right I just looked it up directly in the spec/RFC.

**Comment by m-mohr** [comment]
The z-axis has been added to the dataset spec with #239. We should consider adding similar things to the item.

**Comment by matthewhanson** [comment]
There is no reason to not allow a 3rd dimension in the Item, and I think we do because it's a GeoJSON geometry which allows for it.
However, our description of Geometry and Bounding Box should be updated to say not just lat/lon, but lat/lon/<alttitude>

I'm moving this to 0.8.0 as it's just a clarification.

**Comment by m-mohr** [comment]
Agreed, we should also check the descriptions for spatial collection extents.
