### ISSUE TITLE
Additional temporal fields for Item specification

### ISSUE THREAD

**Issue by p3dr0** [radiantearth/stac-spec#351]
Please consider also the following temporal fields on the Item specification :

- published : The date (managed date) when the metadata item was published on the catalogue (equivalent to atom:published)
- created : The date (non-managed date) when the metadata item was originally created (equivalent to dct:created)
- updated : The date (managed date) when the metadata item was last modified (i.e. updated) in the catalogue (equivalent to atom:updated)
- issued ( or processing_date)  : The date (non-managed date) when the product referenced in the item was created (e.g. if post-processing or laboratory analysis is required, it might be different to the acquisition date) (equivalent to dct:issued)
- valid : The date (non-managed date) indicating the validity of the product referenced in the item (equivalent to dct:valid)
- available : The date (non-managed date) after which the product referenced in the item will likely not be published anymore (equivalent to dct:available). Reasons might be: 
1. the product belongs to a rolling dataset and is removed after a given retention period 
2. the product is expected to be replaced by a new one processed under a new processing baseline
3. the product has become obsolete and will be removed

All these fields are independent of the existent datetime property.
These could be added on the properties object or in a separated object or extension.

**Comment by m-mohr** [comment]
It feels this is more an extension than core Item properties. For some I see a good use case (available, updated), for some I am not sure yet what the benefit is in specifying these (published, created, issued). Are users really searching for the creation/... date of a metadata file?

**Comment by p3dr0** [comment]
Yes, in a network of resources scenario you will see different platforms harvesting the same data.
This is currently the case in Europe where sentinel data is published in several providers (commercial or institutional) with different ingestion time. 
Users (or platforms or services) query catalogues asking for new or updated products (not the same as acquisition date)

**Comment by m-mohr** [comment]
Thanks for the explanation. By the way, there's another issue requesting a file modification date: https://github.com/radiantearth/stac-spec/issues/241

**Comment by m-mohr** [comment]
Google currently uses some additional temporal fields in their collections, which we may want to consider, too:

> * gee:cadence - interval between each pair of images (eg, 1 month)
> * gee:revisit_interval - satellite revisit interval (eg, 5 days)
> * gee:climatological_interval - climatology reference period (eg, 30 years)

I guess they don't really suit in the Item specification, but are more related to collections. So we may need to split them into a separate issue.

**Comment by matthewhanson** [comment]
Discussed this at Sprint #4.  For now, we will add two new optional core fields to the Item:

- created_at: When the metadata Item was created
- updated_at: When the metadata Item was last updated

**Comment by m-mohr** [comment]
Agreed, but I think it would be better to call it `created` and `updated`, which is closer to other metadata standards.

**Comment by m-mohr** [comment]
We added created and updated to the Item spec as proposed by @p3dr0 . The other fields can be proposed as an extension.
