### ISSUE TITLE
Add Orbit field in the EO extension 

### ISSUE THREAD

**Issue by p3dr0** [radiantearth/stac-spec#354]
This field is defined as:

- orbit (or orbit_number) : number : A number identifying the acquisition orbit

Use cases of how orbit would be used to be added here.

**Comment by m-mohr** [comment]
In the [Copernicus Open Access Hub](https://scihub.copernicus.eu/) it is one of the primary fields for searching. So I'm +1 to add it to EO and SAR extension (and later put it in something like a sat extension, which also extracts platform, constellation, instrument etc.)

**Comment by p3dr0** [comment]
I remember using the relative orbits a while ago with ENVISAT MERIS and AATSR but now with Sentinel I mostly use orbit number and direction (ascending and descending)

**Comment by m-mohr** [comment]
We added absolute_orbit and pass_direction to the SAR extension, therefore I think this is solved?
