### ISSUE TITLE
Handle contact info and other collection level metadata with 'catalog' link?

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#36]
Originally we had 'contact' on a per item level. It could be good to at least have an option to refer back to the catalog for the contact info, so we don't have to repeat it each time.

Could be nice to have a convention to refer back to a catalog. Both as a recommendation in the links section, but also a way to specify a particular section of catalog level metadata, like contact, or license.

**Comment by m-mohr** [comment]
Who should be names as contact?
* The service hosting the data, e.g. Google? (I think this was the intention...)
* The organization that produces the original/raw data, e.g. ESA?
* The organization that produced derived data, e.g. VITO?

**Comment by m-mohr** [comment]
Is this solved by the dataset spec?

**Comment by m-mohr** [comment]
Will be solved by #262 .
