### ISSUE TITLE
Single-file STAC

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#385]
The results of a search only need to be a FeatureCollection, however for sat-search I wanted to be able to save the search results so they could be used later without having to make any more queries, so this means saving `collections` along with the `items`. 

This led me to define an [`Items` class in sat-stac](https://github.com/sat-utils/sat-stac/blob/master/satstac/items.py) and to come up with a format for how the search results should be stored, see here: https://raw.githubusercontent.com/sat-utils/sat-stac/master/test/items.json

This is a FeatureCollection with two additional top-level fields:

- `collections`: this is a list of all the collections (the complete collection JSON) the items are a part of
- `search`: optional, but this includes all the search parameters used to generate these results. As an example this is useful to be able to load the results then clip the resulting Items by the intersects polygon, if there is one.

This is basically a single file STAC catalog. The Items and Collections can be easily converted into a standard set of static STAC files, but is more portable and can be opened and viewed in viewers such as http://geojson.io and QGIS.

Additionally for some use cases, such as creating a small set of items derived from other STAC items, it may be much more convenient to work with these single file STACs.

Hierarchical links for a single file STAC aren't needed however. The assumption is that a single file STAC is local file and not something that is published so a self link doesn't make much sense. The root is the file itself, there are no sub-catalogs, and a collection need not be reference by a link but only by it's ID, as it is in the `collections` list.  Links  *could* be included in the file (such as in the case of search results), would be replaced by new links if the single file STAC were converted to a regular catalog.

Thoughts?

**Comment by m-mohr** [comment]
Sounds like a useful extension.

**Comment by cholmes** [comment]
Definitely sounds useful. I like that it's still a featurecollection, but adds in some more to it. Could you make a PR to make it an extension Matt? Could potentially evolve into core eventually, but let's start it as extension. 

And yeah, ideally we update the 'single item extension' to just use a construct like this.
