### ISSUE TITLE
Making the Commons extension Core as optional field in the collections

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#392]
As we are currently discussing making the collection field from the Commons extension core (see #384), I think we could make the whole Commons extension core as optional field for collections. It is used in many cases anyway, either to describe collections with fields that are usually used for items (but having no items, see GEE and multiple implementations for openEO) or to describe common fields of items (sat-api, sentinel-stac, landsat-stac). So we have 6 implementations, which basically makes the extension stable. It makes the spec IMHO a whole lot easier to understand as collections and commons are so closely related and both refer to each other so often. It would also bring us closer to the common metadata model, I think. Also, it makes validation easier.

**Comment by matthewhanson** [comment]
👍

**Comment by cholmes** [comment]
Yup, I'm +1 - thanks for humoring me on evolving it as an extension, but I agree that there's good implementation use of it. Ideally we should touch back on the idea of the 'common metadata model', which I think is taking this even further, saying all fields could serve as 'commons'. But I think just having the commons extension in core could be a happy medium that enables lots of reuse, but doesn't try to fit every 'collection' level thing to also be used in items. Though we do have to sort out the other way is the single item extension, but maybe #385 solves that for us? 

Happy for this to all move in to PR's so we can see how it all looks in practice, in the spec and in examples.

**Comment by m-mohr** [comment]
Great, I'll make a PR for #384 and this issue once things are a little less busy in the openEO project.

**Comment by m-mohr** [comment]
Thinking about moving it to 0.8.0 as this is also related to #413 / #416. Opinions?

**Comment by m-mohr** [comment]
Done.
