### ISSUE TITLE
Merging option

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#394]
We recently changed the behavior of sat-api as now we merge the Collection properties with the Item when we ingest a Catalog. The 2-pass search ended up being complicated and didn't work in all cases without a lot of special logic. So now what is returned from a search is the complete Item. 

I'm of mixed feeling about this as there are several problems:

- It increases the size of the output (mostly due to eo:bands)
- Updating properties in the Collection does not auto update all member Items
- Records cannot be directly converted to a STAC catalog without removing fields in the Collection
- I don't think returned Items are strictly STAC compliant, because the `Commons` property forbids defining properties that are in the Collection.

The advantages are:
- much simplified search logic (especially with Elasticsearch)
- what is returned is the complete Item so user doesn't have to fetch Collection
- If you search for a property that is in Collection, it's actually in the returned Item (it's weird to search for a property and then not have it in the returned Item).

For a PostGIS or other relational backend I think the searching would have been much easier.

On the backend it's fine if implementors want to store the complete Item, but if the Commons extension is used I don't think the default should be to return the whole Item. On the other hand, this can also be useful behavior.

So one possibility is to add in a new parameter to the API, `merge`, which would merge Collection properties with Item properties in the search results.

**Comment by cholmes** [comment]
Interesting. I like the idea of a 'merge' parameter, that merges the collection with the search results.  I think default should be that we just return the item, without adding in the collection.

**Comment by matthewhanson** [comment]
This is rendered obsolete because we are removing the Commons extension #762
