### ISSUE TITLE
Add field "metadata-modification-datetime"  in the "Item-Specification" properties 

### ISSUE THREAD

**Issue by arcostarusty** [radiantearth/stac-spec#395]
Hi,

I would propose to add a field "**metadata-modification-datetime**" in the **Item-Specification** properties object in order to allow tracking of metadata updates. 

Ideally also a field "metadata-hash" could be useful for validation and integrity verification of the Item.

Other suggestions?

**Comment by m-mohr** [comment]
Hi Armin, welcome to STAC. 

There is already an issue about adding additional temporal fields (including updated for the last metadata update), so maybe just add your support there: https://github.com/radiantearth/stac-spec/issues/351

We added a checksum extension in dev so in 0.7.0 the integrity verification will be possible. See: https://github.com/radiantearth/stac-spec/tree/dev/extensions/checksum

If that's tackling all your issues you may consider closing this issue? Thanks for contributing.

**Comment by arcostarusty** [comment]
Thanks for the quick reply.

Sorry I did oversee the already existing issue #351.

Ok I'll add there my suggestions if needed 

Thx

A.Costa

**Comment by m-mohr** [comment]
You could also just add a thumbs up reaction to the issue so that you show your support and we know a larger audience wants the features.
