### ISSUE TITLE
How to specify units / crs / trs

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#399]
Some extensions such as the SAR and data cube extensions use OGC URNs to specify units, crs and trs. I basically have no clue about these OGC URNs, but at the time of writing it seemed like the only authoritative source/standard to specify such things. Working with it though seems very confusing, for example I was looking for the URN for centimetre, but couldn't find any information on the web. So if it's to hard to use, we should consider another option, e.g. a mix of PROJ strings for crs, udunits for units and something else for trs. Has anybody information how to work with OGC URNs? How to find them? ...

Related extensions: SAR and Data Cube (maybe EO)

**Comment by davidraleigh** [comment]
I know the wkt's are long and messy, but they have an option for embedding your epsg code for units, projections and all the other details. I'm not familiar with the OGC URNs @m-mohr. Do you have any examples anywhere of the OGC URNs in use that I could look at?

**Comment by geospatial-jeff** [comment]
You can find examples of OGC URNs in the GML spatial reference description, [here](http://spatialreference.org/ref/epsg/wgs-84/gml/) is an example for WGS 84.

The URN takes the format `urn:ogc:def:<objectType>:EPSG::<code>`, where `objectType` is one of the values in the following table ([source](https://portal.opengeospatial.org/files/?artifact_id=30575)) and `code` is the standard EPSG code representing the given value.

![2009_objecttypes](https://user-images.githubusercontent.com/40916268/53132724-d41d4800-352d-11e9-8e67-5d4dbfe3a439.png)

The OGC URN for meters, for example, would be `urn:ogc:def:uom:EPSG::9001` while degrees would be `urn:ogc:def:uom:EPSG::9122`

**Comment by mkadunc** [comment]
Regarding finding the URNs - the 5th part of an OGC URN is *authority* - so to find what you're looking for you should probably look through that authority's register or specification.

e.g. for `cm`:
- you can look in EPSG https://www.epsg-registry.org/  and get `urn:ogc:def:uom:EPSG::1033` (OGC naming registry even gives you some info at http://www.opengis.net/def/uom/EPSG/0/1033)
- or you can look in UCUM https://ucum.nlm.nih.gov/ucum-lhc/demo.html and get `urn:ogc:def:uom:UCUM::cm`
- `OGC` authority doesn't have cm, but it does have metre - see http://defs.opengis.net/sissvoc/ogc-def/resource?uri=http://www.opengis.net/def/uom/OGC/1.0/
- the `SI` has some units, but only the base set

BTW: for units, the w3c "Spatial Data on the Web Best Practices" document has some recommendations https://www.w3.org/TR/sdw-bp/#c-unitofmeasure

**Comment by m-mohr** [comment]
Thank you for all answers, highly appreciated.

@davidraleigh We don't use WKT (or PROJ) for crs as STAC is aimed towards searching and nobody would ever search for WKT or PROJ string, I guess. That's why the EO extension only allows EPSG codes. Not sure  whether OGC URN are much better though.

@mkadunc Your list actually feels more like a reason against OGC URNs as there are multiple versions of a single unit. I still would like to have a central registry to look up the URNs... just tried to verify several URNs and I'm still not sure whether they are correct or not.
Will look into the W3 link, thanks.

**Comment by m-mohr** [comment]
So what we have now:

EO: 
* No units
* CRS as EPSG code

SAR: 
* Units as SI / UDUNITS
* No CRS

Data cube:
* Units as SI / UDUNITS
* CRS as EPSG code or PROJ definition
* TRS: ISO8601 compliant by default (Gregorian / UTC) otherwise free form string
* Other reference systems: Free form string

Point Cloud: 
* N/A
