### ISSUE TITLE
Absolute vs Relative links use cases

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#401]
We’ve talked about this a lot in other issues, with the main discussion currently happening in #373 . But we never had a clear articulation of the use cases driving each. I’d like us to get better at articulating those. I think in the future the main issue should start with use cases, but for this one I’ll just do this as a related issue.

So two main user stories:

* As a producer of static STAC catalogs, I often don’t know the final location that my catalog will be published online. I would like to make catalogs that can easily be moved to different locations, without having to rewrite absolute links in every file when I publish to the final location. 
* As a user who downloads or receives (in email, file passed, etc) a STAC Item and assets I would like to know the canonical online location that it came from, where I can access the data and metadata again.

And I think there is a couple of related user story that we’ve talked about:

* As a user of a STAC catalog I would like to use a copy of the catalog on my local machine and have it work without relying on any remote links.
* As a user I would like to be able to take a subset of an online catalog and use it locally or put it on another network, with minimal amounts of work.

And I have one more I’d like:

* As an implementer of the STAC specification I would like clear recommendations of when to use relative or absolute links.

Let me know if there are other user stories that people have in mind. Just put them in the comments, and I can incorporate them up here. We can also decide together the relative importance of the stories, and alternate ways to solve them (like in tooling). I do think the first user story is one we should prioritize. We can discuss our approach to these stories in #373

**Comment by m-mohr** [comment]
Even if there's an absolute link in the files, it could be restricted to certain authenticated users so it might not be as helpful in all cases.

**Comment by fredliporace** [comment]
I suggest:
 * As an implementer I'd like to crawl a static catalog for indexing or for conversion to a new STAC version

Maybe using numbered lists on the issue help us to reference the use cases within the comments.

**Comment by fredliporace** [comment]
Another one:

 * As an implementor I'd like to create an API service for a static catalog already in place.

I think that for this use case in particular id would be better (simpler) to use absolute links for both static and API.

**Comment by cholmes** [comment]
Awesome, thanks @fredliporace I added both in.

**Comment by m-mohr** [comment]
* As a implementor, I'd like to allow users to download a static catalog from an API.

That's the openEO use case where users process data on a back-end and the back-end offers it to download as STAC API (GET /stac) and the users in the end should have a static catalog on his machine.
