### ISSUE TITLE
Spec enhancements to support nicer URL's in STAC Browser and similar tools? 

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#403]
@mojodna is the expert on this, but I wanted to put up an issue to track it and hopefully get his thoughts.

STAC Browser used to have quite legible URL's, like https://iserv-stac.netlify.com/item/2014/06/27/IPR201406270630250061S03478E

But constructing those url's required traversing up the whole catalog tree, and so was quite slow.  The new stac browser implementation is much quicker, encoding the whole URL so no traversal is needed, but at the expense of legible URL's, like https://planet.stac.cloud/item/5k3UqPNLpDJMxoAfw1YUV9y9QsbZpgkBacBWwUJ9/3MxsQZbdxjScFVpNqiHrDSMjKgPQo9Uq1JYtn2CAwxwSj9F/HuwgeSATdb44aYX7WSCsDbh9RmKQG6FvYNWicrF6j51Kqqfg1AE2TmRv59g9W1bBcjF

If there is something we can recommend in the specification for catalogs to include a bit of info on the 'slug' or catalog structure, or some sidecar 'sitemap' type file that could be loaded, then that could be a good route. Those who can publish the extra info get nicer url's, but everyone gets stac browsers with nice performance.

**Comment by mojodna** [comment]
(The illegible URLs consist of base58-encoded path components, each of which is relative to the parent component. Ultimately, the first encoded path component is relative to a configured catalog root, ideally facilitating shorter components that can be fully resolved without needing to traverse a catalog tree.)

Catalog-specific, legible URLs were previously implemented by writing a custom `slugify` function that was aware of the path structure of the underlying catalog and could convert from STAC Browser components to catalog / item URLs. This may be generalizable (i.e. a common `slugify` implementation that does the above mapping), but it requires that catalogs' directory structures be consistent.

**Comment by mojodna** [comment]
#408 describes 2 modes (items within subdirectories with the same names, items adjacent to catalogs) that produce predictable URLs, so `slugify` functions should be possible for each.
