### ISSUE TITLE
Add look direction to SAR extension

### ISSUE THREAD

**Issue by walterggit** [radiantearth/stac-spec#404]
Please consider adding a "look_direction" parameter to the SAR extension to indicate the side of the imaging platform from which the imagery is collected.  This would have a value of either "right" or "left".

Radarsat-2 and ALOS-2 both offer either left or right look directions, and this is relevant information for searching for same-geometry sets of images for SAR interferometry and some other applications.

**Comment by cholmes** [comment]
Thanks for the input @walterggit! Are you actively working on putting radarsat-2 and alos-2 into STAC implementations? I'm not a SAR expert, but would be happy to add in anything that an online dataset in STAC needs. If you've not done it yet then hopefully some more SAR experts can sound in, and we can get it to a PR.

**Comment by walterggit** [comment]
@cholmes - I am not directly working on STAC implementations for SAR datasets, but will be working with SAR data downstream on a platform that will likely be using STAC, so am looking at this more from an end-user perspective ("what do I want to be able to search on").  I will be working with radarsat-2 data, I only mentioned alos-2 to point out that look direction is relevant for more than just radarsat-2 (both these platforms can be either right or left looking).

**Comment by cholmes** [comment]
Awesome - great to get the user perspective, especially on what to search on. If you can write up a description of the field that could go in to the spec I'd be happy to help make a PR if you're not comfortable with doing that. 

And can you share who is building the platform that will likely be using STAC? I'd be happy to try to get in touch with them (feel free to email me cholmes at radiant <dot> earth if you can share but not in a public forum.)

**Comment by walterggit** [comment]
@jeffnaus pointed me at the STAC spec.  

For the look direction parameter, I suggest the following description: "SAR antenna pointing direction relative to the flight trajectory of the satellite, either right or left", an interpretation consistent with http://www.asc-csa.gc.ca/eng/satellites/radarsat/radarsat-tableau.asp and with how I have most often seen the term used over the years.  However, it seems that there are inconsistent uses of the term "look direction"- ESA defines it as an angle in https://earth.esa.int/handbooks/asar/CNTR5-2.html , so we may want to consider whether another name might be better.  

In Radarsat-2 metadata, it is "antennaPointing" (https://mdacorporation.com/docs/default-source/technical-documents/geospatial-services/radarsat-2-product-format-definition.pdf?sfvrsn=4 ); in ALOS-2 metadata, it is "observation direction" (https://www.eorc.jaxa.jp/ALOS-2/en/doc/fdata/PALSAR-2_xx_Format_CEOS_E.pdf ).

**Comment by claxn** [comment]
Regarding S1 there is a `platformHeading`  parameter, which defines the orientation of the platform with respect to north.  As far as I know both S1 satellites are always right looking. In my opinion it would be good to define a metadata entry named `antenna_azimuth`, which is the clockwise angle between north and the antenna (This is more clear than `look direction`). For S1 it would result in `antenna_azimuth` = `platformHeading` + 90°.

**Comment by walterggit** [comment]
I agree that "look direction" is a bit unclear given the different interpretations that have been used for it.  However, as a search parameter for sar platforms that can look either right or left, I think it is more useful to know whether it is right or left looking than the exact angle.  I've never used the antenna azimuth angle or platform heading in a search- it is harder to compare angles, which may not match exactly, than a binary right-left looking comparison. 

I don't actually even see a platform heading parameter in the Radarsat-2 metadata (product.xml) for non-map products.  It can be computed if needed based on embedded orbit or tie point information, but that isn't completely trivial and is probably more work than a search indexer wants to do.

I would be okay with having antenna_azimuth as an optional parameter if others find it useful for their applications, but I do think that a simple (also optional) parameter to indicate right/left looking for platforms that offer both would be more useful.  It would not have to be named "look_direction", though I'm not sure what the best name for it would be (clock angle of +/-90 degrees? observation direction? antenna pointing direction?).  Unfortunately there doesn't seem to be a consistent term used.

**Comment by claxn** [comment]
@walterggit: I agree that in case of filtering SAR data sets an `antenna_azimuth` attribute is excessive. From your suggestions above, I would go for `observation_direction` to distinguish between left and right looking. If we agree on `antenna_azimuth` as an optional parameter, can't you use `antennaPointing` as `antenna_azimuth` for Radarsat-2 data?

**Comment by walterggit** [comment]
@claxn: antennaPointing in the Radarsat-2 metadata is set to Right/Left rather than an angle.  I have not found any angle in the non-map-product Radarsat-2 metadata that corresponds to either the platform heading or the antenna azimuth angle; we compute these from the orbit or tie point data if needed.  Radarsat-2 map products do have a satellite heading parameter.  

I agree that observation_direction sounds best for the left/right indicator name.

**Comment by claxn** [comment]
@walterggit: Ah okay, thanks for the clarification! Only specifying `observation_direction` and leave `antenna_azimuth` aside will do the job for all SAR data for the time being, I think.

**Comment by walterggit** [comment]
@claxn: That seems reasonable to me too.

**Comment by m-mohr** [comment]
Thanks! I'll make a PR for it and let you know once it is ready to be reviewed.

**Comment by m-mohr** [comment]
@walterggit @claxn You can review the new field at https://github.com/radiantearth/stac-spec/pull/425

**Comment by m-mohr** [comment]
Has been merged and will be part of the 0.7 release.
