### ISSUE TITLE
Add incidence_angle to SAR extension

### ISSUE THREAD

**Issue by walterggit** [radiantearth/stac-spec#405]
I would recommend including an “incidence_angle” option in the list of optional SAR parameters.  The incidence angle is often specified instead of the off-nadir (elevation) angle in SAR product metadata.  The two angles are related, but not the same owing to the earth's curvature.

**Comment by cholmes** [comment]
Thanks for the contribution @walterggit! Are you working on a SAR dataset in STAC that needs this? Like does sentinel-1? We still don't have any solid reference implementations for SAR extension, but I'd love to see one in soon. 

Or I'm happy to add this if more SAR experts sound in, but we have no one in our core STAC community who _really_ knows SAR. Or if you'd like to join and become that expert then you could make a Pull Request explaining this option in the spec.

**Comment by walterggit** [comment]
For a definition for incidence angle, you could use "The incidence angle is the angle defined by the incident radar beam and the vertical (normal) to the intercepting surface.  Measured in degrees (0-90)."  It would be good if this could be specified as a either a single value (assumed to be at scene center) or a two-value array, to allow storage of near-range and far-range incidence angles.

**Comment by cholmes** [comment]
Cool. If it needs to potentially be a two-value array then I think the way to do it is define it as an array, that can have one or two values.

The alternative would be to define two values - incidence_angle_center and incidence_angle_range or something like that. Are there cases where people would define both / be interested in both? Or is it better to just have one field?

**Comment by walterggit** [comment]
I've used both in different contexts, but it would probably be more consistent with the off-nadir angle spec to keep it as a single parameter.  You could support specification of up to all of them by allowing:
[center_inc_angle], or
[near_range_inc_angle,far_range_inc_angle], or
[near_range_inc_angle, center_inc_angle, far_range_inc_angle]

**Comment by cholmes** [comment]
@walterggit - I think we may be moving in the SAR extension to less use of the ranges. See #422 

And I think we're also wondering if off-nadir angle could just be a single value, or does it also need the ability to specify near and far ranges? I think it may make sense to have off-nadir and incidence angle both be more explicit, like have off_nadir_center and off_nadir_range.

Also I think the off-nadir example may just be an error? I too would expect it to have the first value be in between the 24.5 and 30. 

@walterggit - happy to take a recommendation on how to best specify these, like what has worked best to cover the range of sar metadata you've seen. We're still in 'proposal' stage to garner feedback from experts like you, so can change things around.

**Comment by walterggit** [comment]
@cholmes : I think having inc_angle_center, inc_angle_near_range and inc_angle_far_range as options would make sense.

**Comment by m-mohr** [comment]
I'd always try to reduce fields to a minimum to make sure things stay as lightweight as possible. So I'm wondering whether it would be enough to just specify the center like we also only define a center wavelength or so? Just want to make sure that we don't clutter the spec, but if you say all of them are very important, we can surely add them all, I guess.

**Comment by walterggit** [comment]
It's possible that just the center incidence angle would be enough for search purposes, especially since instrument_mode is available and would be associated with certain incidence angle ranges.  You could start with that and add the near/far range later if there is demand for it.

**Comment by m-mohr** [comment]
Thanks, that sounds good. I'll make a PR for it and let you know once there is a PR to review.

**Comment by m-mohr** [comment]
@walterggit @claxn You can review the new field at #426

**Comment by m-mohr** [comment]
Merged into dev and will be released as part of the 0.7 release. Thanks @walterggit and @claxn.
