### ISSUE TITLE
EO extension example not validating properly

### ISSUE THREAD

**Issue by jbants** [radiantearth/stac-spec#417]
I think the index object is missing an `href`, otherwise it's not valid with item definition for `assets`

EO example:
https://github.com/radiantearth/stac-spec/blob/612ee4fb4f979c049d2416e7f5374a5301b8a277/extensions/eo/example-landsat8.json#L238-L241

Item spec:
https://github.com/radiantearth/stac-spec/blob/612ee4fb4f979c049d2416e7f5374a5301b8a277/item-spec/json-schema/item.json#L102-L121

**Comment by cholmes** [comment]
Closed with #418
