### ISSUE TITLE
Reference WFS/WMTS representations of STAC Items

### ISSUE THREAD

**Issue by arthurgustin** [radiantearth/stac-spec#42]
Hello,
In our catalog response we embeded specific links for consuming WFS and WMTS

```
 "_links": {
                "panSharpenedWms": {
                    "href": "https://foo/bar/104527cc-6476-4605-ad45-f6f2a28f563c?SERVICE=WMS&REQUEST=GetCapabilities",
                    "name": "OTF PanSharpened",
                    "type": "WMS"
                },
                "panSharpenedWmts": {
                    "href": "https://foo/bar/104527cc-6476-4605-ad45-f6f2a28f563c/1.0.0/WMTSCapabilities.xml",
                    "name": "OTF PanSharpened",
                    "type": "WMTS"
                },
}
```

I don't know if it can be studied as part of the STAC spec, so I'm just writting down the idea and our use case.

**Comment by cholmes** [comment]
Hey @arthurgustin - apologies for the slow response, I need to better figure out my github notifications.

We definitely discussed it at the initial sprint in boulder. And the extensions group came up with some thoughts on it: https://github.com/radiantearth/boulder-sprint/tree/master/extensions

In particular see: 
https://github.com/radiantearth/boulder-sprint/blob/master/extensions/planet-search-results-ext.json?short_path=e3778b4

It has an osgeo:tms link - similar to WMTS.

I think there will definitely be STAC specs that reference WMS + WMTS. It's still 'to be determined' if we put those in 'links', in 'resources' or as fields (though fields make less sense to me). 

Can you share more about your catalog? Or ideally put info in https://github.com/radiantearth/catalog-implementor-survey as we're trying to have a good picture of the existing catalogs out there, and make sure that there's at least some way to meet everything people are trying to do - even if it's just making sure an extension mechanism works right.

Thanks for the issue though, it's definitely one that needs addressing, though I'm going to tweak the title a bit.

**Comment by guydou** [comment]
is there any update on this issue?

Where in STAC should I attach the WMS/WMTS links?

Thanks

P.S
The links in the @cholmes answer don't work 

Thanks

**Comment by matthewhanson** [comment]
I think additional distribution endpoints for an Item could go in either links or assets.  Maybe this should go in Best Practices @cholmes @m-mohr.

@m-mohr you labeled this as 'new extension' but I'm not sure what that new extension would be.  Links or Assets seem to be all that's needed here.

**Comment by m-mohr** [comment]
Initially, I meant #470, but the focus of the extension seems to have shifted a bit.

Still, you may need more than links for web service links. At least a rel type, I think. Maybe additional properties depending on the service.

**Comment by matthewhanson** [comment]
Perhaps, but there doesn't seem to be anything actionable here, can we close this issue?

**Comment by m-mohr** [comment]
Well, at least a recommendation how to link to them should be an outcome?!

**Comment by cholmes** [comment]
Closing this. We have all the structures here to do this. Could add some best practices, though hopefully more of this type of thing comes from ogc.
