### ISSUE TITLE
Avoid array fields in the SAR extension

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#422]
Yesterday, I tried to come up with a collection-level description for SAR data using the proposed extension for non-common fields, see #416 and #413. It was quite easy to do so until I reached the SAR fields defined as array of numbers. I had to define extents, e.g. range resolution would have been something like 10 to 50 meters and the azimuth resolution would have been something like 12 to 80 meters (just an arbitrary example). Unfortunately, it's not really possible to to so as the field was defined as array of numbers, see the current situation below. So I propose to change the array fields to single value properties as below in the proposal. I guess the proposal is also easier to be used in the API as it's easier to filter and query based on individual values as it is on arrays. Thoughts?

Related issue: https://github.com/radiantearth/stac-spec/issues/405

## Current situation

| Field Name            | Type               | Description                                                  |
| --------------------- | ------------------ | ------------------------------------------------------------ |
| sar:resolution        | [number]           | The maximum ability to distinguish two adjacent targets, in meters (m). The first element of the array is the range resolution, the second element is the azimuth resolution. |
| sar:pixel_spacing     | [number]           | The distance between adjacent pixels, in meters (m). The first element of the array is the range pixel spacing, the second element is the azimuth pixel spacing. Strongly RECOMMENDED to be specified for products of type `GRD`. |
| sar:looks             | [number]           | The number of groups of signal samples (looks). The first element of the array must be the number of range looks, the second element must be the number of azimuth looks, the optional third element is the equivalent number of looks (ENL). |

## Proposal

| Field Name            | Type               | Description                                                  |
| --------------------- | ------------------ | ------------------------------------------------------------ |
| sar:resolution_range        | number           | The range resolution, which is the maximum ability to distinguish two adjacent targets perpendicular to the flight path, in meters (m).  |
| sar:resolution_azimuth        | number           | The azimuth resolution, which is the maximum ability to distinguish two adjacent targets parallel to the flight path, in meters (m).  |
| sar:pixel_spacing_range     | number           | The range azimuth, which is the distance between adjacent pixels perpendicular to the flight path, in meters (m). Strongly RECOMMENDED to be specified for products of type `GRD`. |
| sar:pixel_spacing_azimuth     | number           | The azimuth pixel spacing, which is the distance between adjacent pixels parallel to the flight path, in meters (m). Strongly RECOMMENDED to be specified for products of type `GRD`. |
| sar:looks_range             | number           | Number of range looks, which is the number of groups of signal samples (looks) perpendicular to the flight path. |
| sar:looks_azimuth             | number           | Number of azimuth looks, which is the number of groups of signal samples (looks) parallel to the flight path. |
| sar:looks_equivalent_number             | number           | The equivalent number of looks (ENL). |

**Comment by cholmes** [comment]
I agree that filtering / querying would be more straightforward with your proposal. I definitely prefer the more explicit style, I don't know what the array adds, except making it so there are less overall fields? But I think for making it easier to understand your proposal makes a lot of sense.

**Comment by m-mohr** [comment]
I guess the only advantage of arrays is that it is nicely grouped and there are less fields (and the SAR extension has a lot of them).

**Comment by m-mohr** [comment]
Has been merged, closing.
