### ISSUE TITLE
Suggestions for remote sensing datasets

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#43]
Background: in the Google Earth Engine catalog, we have a number of remote sensing raster datasets updated daily.  Many of them are not observation results - they can also be, for example, global hourly climate model outputs with a pixel size of 0.1 degree, containing temperature, precipitation and other bands.

We have hit a number of pain points browsing catalogs on medium and large sites, so here are some things I wish catalogs included, with more important fields first.

1. Band type - observational, classification or bitmask. This is important for pyramiding during ingestion when one higher-level pixel is created from several low-level ones. Observational bands have continuous physical values that should be averaged during pyramiding. Classification bands (eg, forest/non-forest) usually contain integer values between 0 and N representing different land classes, and averaging them makes no sense. For the, we just pick the majority pixel value during pyramiding. Bitmask bands should just use random sampling.
2. Fill (nodata) value. It's sometimes specified in gdal metadata, but not always, and may even be wrong.
3. File modification date. Some providers regenerate files in-place several times.
4. Product version. Many providers release several versions of the same product, and it would be convenient to have a dedicated version field, rather than hunt for it in the title string.
5. Dedicated fields for band units (at least as a freeform string).
6. Band scale and offset. Even observation bands sometimes specify scale, and climate datasets use scale/offset a lot.
7. For categoric bands, it would be nice to encode the class values, names, and maybe desired colors. (Eg, value=0, class=Forest, color=00ff00; value=1, class=Water, color=0000ff)
8. Ditto for bitmask bands. They can have a complicated structure, and describing it needs a separate bug.

The rest of suggestions contain some fields we have added to our own dataset descriptions. They reflect the parameters that we think users often want to see in search results or use in queries. That is, I don't need them as much when ingesting data from other's catalogs, but I think I should provide them to improve user experience.

9. Product DOI and citation(s).
10. Per-band resolution (eg, 10 m or 0.25 degrees)
11. Instrument name. This is different from platform name - one platform (satellite) may have multiple instruments.
12. Product periodicity (eg, hourly or daily climate data) or revisit period (eg, 16 days for Landsat 8).
13. List of tags/keywords to help searching.

**Comment by cholmes** [comment]
Hey @simonff - apologies for the super slow response, I thought I had written back here. But I _really_ appreciate all this input. I believe _most_ of this feedback will be relevant for an 'Earth Observation Profile' of STAC, which I hope we can get to soon. cc @matthewhanson 

The core of STAC is quite flexible, so my hope is that when GEE implements STAC it would be easy to add those data fields. Initially as 'vendor fields', but perhaps do some as vendor fields and some as 'community fields' where we try to get a set of providers to offer up the same fields. And then some of the ones you proposed could make sense to be beyond just earth observation profiles, like the 'updated' field.

So I _hope_ that right now you could implement all those fields and be STAC compliant - would love to hear feedback on it. And then we can evolve as a community to get shared fields by everyone publishing their fields and making them accessible in the standard STAC manner.

thanks!

**Comment by m-mohr** [comment]
After a long time, we should revisit this and see where we are at the moment and open issues on individual suggestions to better be able to track and discuss them:

1 / 3 / 7 / 8 : Is not yet proposed, I think. Would you open issues for that @simonff ? I think 1 and 7 could be combined to a single issue.
2 / 5 / 6 / 12 : Is proposed as part of the dataset spec rework of the EO extension.
4 / 13 : Is proposed as part of the dataset spec.
10 / 11 : Seem to be already included in STAC.
9 : Is basically implemented by the scientific extension.

**Comment by simonff** [comment]
1 is covered by the pyramiding policy.  I'll open issues for 3, 7 and 8 (file date, category names/colors and bitmask descriptions)

**Comment by m-mohr** [comment]
So this issue can be closed in favor of the individual issues, right?

**Comment by simonff** [comment]
Yes, closing
