### ISSUE TITLE
Include link to /stac/search from /stac/ for STAC API's? 

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#430]
Right now if you go to a STAC API and hit the /stac/ endpoint you have no way to know if there is a /stac/search endpoing, afaik.

Should we specify a 'link' with something like rel=search? So you can navigate from the top level down to the search endpoint? 

I think we could make that link required for dynamic catalogs that support search. And a static catalog could also add it, if it knows that there is another endpoint that supports search. 

cc: @matthewhanson @joshfix @fredliporace @hgs-msmith

**Comment by m-mohr** [comment]
+1 Good idea!

**Comment by fredliporace** [comment]
I'm OK with that reference but my interpretation from the current spec is that /stac/search endpoint is mandatory and /stac is optional, so if you reach /stac/ endpoint the /stac/search should be available using the __same__ URI as prefix. That's how the current CBERS implementation works.

That referece makes more sense IMO for static catalogs which also support dynamic APIs. For instance, if you access the CBERS static catalog from https://s3.amazonaws.com/cbers-stac-0-6/catalog.json then it would be nice to have the reference to the search API, but if you access the same document through https://stac.amskepler.com/stac then I'd assume that the search endpoint is at https://stac.amskepler.com/stac/search.

**Comment by matthewhanson** [comment]
I'm all for this, it's nice to be able to see the capabilities and endpoints.
I think providers in general should make judicious use of links at the catalog level and include references to documentation, webpage about data, or any other relevant info.

**Comment by m-mohr** [comment]
> I'm OK with that reference but my interpretation from the current spec is that /stac/search endpoint is mandatory and /stac is optional, so if you reach /stac/ endpoint the /stac/search should be available using the **same** URI as prefix.

I'm implementing /stac and the WFS endpoints, but I'm not implementing /stac/search yet. That's always the issue with loosely coupled API endpoints and some being mandatory. People just ignore it if they don't need it, it's the same experience with the openEO API. We don't always have Items in openEO, only collections so the STAC API doesn't work well for us. So I like the approach with the link to tell what is available and what isn't. I would actually propose to remove the mandatory restriction from the API and just look for a search link.

**Comment by m-mohr** [comment]
I think I should wait for #432 to be merged so that I can base my changes on that massive PR.

**Comment by m-mohr** [comment]
PR is available for review: #441

**Comment by m-mohr** [comment]
Done.
