### ISSUE TITLE
Automate interactive API site generation and move to stacspec.org

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#434]
Right now our [online interactive API docs](https://app.swaggerhub.com/apis/cholmesgeo/STAC-standalone/) live at swaggerhub, and must be updated manually. We should automate the process, and move the output to stacspec.org instead of swaggerhub.

- [x] Find right tooling to generate the API website from the openapi docs.
- [x] Migrate output to stacspec.org/api
- [ ] Automate the build to automatically produce the website and deploy it to stacspec.org

**Comment by cholmes** [comment]
Done! Using redoc, and now available on https://stacspec.org/STAC-api.html

Didn't actually need to use continuous integration, the tool picks up the open api docs direct from the repo with javascript

**Comment by m-mohr** [comment]
Merging https://github.com/radiantearth/stac-site/pull/19 needs to be done after the 0.7 release, therefore re-opened.

**Comment by cholmes** [comment]
Closing, as radiantearth/stac-site#19 is merged.
