### ISSUE TITLE
Update UML model

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#444]
For 0.7.0, the UML model needs to be updated. collection was added to the item, properties was added to the collection.

**Comment by m-mohr** [comment]
I made a hotfix for it, adding in the collection field to items and adding properties to Collections (not linking to the properties entity though). Also updated the version number. This is a very rough fix until we may get a better version from @hgs-msmith.

By the way, which tool was used to generate this diagram? We should include the source file, if there's any, to the repo otherwise we need to fully redo or remove it in subsequent releases, I guess.

**Comment by cholmes** [comment]
TODO's: 

* Add properties field to collection
* Add collection field to item
* link rel = self should be changed to 0-1 (not required any longer)

**Comment by hgs-msmith** [comment]
Closed via PR #457
