### ISSUE TITLE
Update wfs sample api responses to be STAC relevant

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#454]
In the WFS 3 endpoints like /collections/{collectionId} in the openapi docs we just use their examples, which is 'buildings'. See like https://stacspec.org/STAC-ext-api.html#operation/describeCollection

We should use collections that actually make sense for STAC, so people don't get confused.

**Comment by m-mohr** [comment]
We should make sure we don't edit the WFS-core YAML file. Hacking it would make upgrading WFS hard, so changes to that should only be made in the STAC YAML files.

**Comment by m-mohr** [comment]
After backporting the WFS draft, I'd like to emphasis that I don't think it's a good idea to change things in the WFS spec. It will get lost each time we update WFS. We could do it maybe for a stable release, but not anytime soon. Also, I don't think the WFS examples are a big problem.
