### ISSUE TITLE
Update Collections and API to WFS 3 latest

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#472]
WFS 3 changed their collection definition a bit. We should update to align.

**Comment by m-mohr** [comment]
I'm taking this over, but will wait for an actual implementation into the spec until at least the OGC Hackathon was held.

**Comment by m-mohr** [comment]
Backporting WFS to STAC makes sense only around July as it's when they plan to release the next release candidate. Is that early enough for 0.8 or do we delay it for 0.9? @cholmes

**Comment by m-mohr** [comment]
see also https://github.com/opengeospatial/WFS_FES/issues/243

**Comment by m-mohr** [comment]
Draft 2 has been released 5 days ago: https://github.com/opengeospatial/WFS_FES/releases/tag/1.0.0-draft.2 - will make a PR very soon.

**Comment by m-mohr** [comment]
I saw that there are two new (optional) properties in their collections: 
* `itemType`: indicator about the type of the items in the collection (the default value is 'feature').
* `crs`: the list of coordinate reference systems (OGC URls) supported by the service (there's an additional crs in the spatial extent, too)

Those seem somewhat unrelated to STAC and backporting them to STAC Collections feels wrong. Should we ignore them?

Also, they have new optional properties in the links:
* `hreflang` language of the referenced document
* `length` not sure yet what this is about. length of the referenced document?

Should we also ignore them? I think not providing optional properties would be fine.

Other than that, we only need to change the structure of `extent` in STAC collection. 

There are probably some more changes in the API.

cc @cholmes

**Comment by m-mohr** [comment]
PR: #525 to update the API and backport `extent` to STAC collections.
