### ISSUE TITLE
Create documentation ItemCollection

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-spec#484]
Currently, ItemCollection is only documented in the openapi spec, and referenced in the API endpoint descriptions and Search Extension (both changes in PR now). This should have clear documentation on par with catalog-spec and item-spec. 

I think the correct description is "A GeoJSON FeatureCollection augmented with foreign members that contain values relevant to a STAC entity".  Should probably also update the Item spec with this language to make the relationship to GeoJSON clear. 

[https://tools.ietf.org/html/rfc7946#section-6]

**Comment by philvarner** [comment]
Also volunteering to do this, but I don't have permissions to assign it to myself.

**Comment by m-mohr** [comment]
I'm not sure whether I would add this on the same level as Item / Collection / Catalog as those are all used in both static and dynamic catalogs, but ItemCollection is only used in API. Therefore, I'd be in favor of giving it a prominent place in the API spec - or is ItemCollection also getting an equivalent in static catalogs?

I can assign you, if you'd like...

**Comment by matthewhanson** [comment]
While it is used only in the API right now, it would also serve as the basis for a single file STAC catalog, so I could see this getting its own definition at the root level. In fact by keeping it in the core, we keep consistency between the static and dynamic catalogs, it's just that best practices say that static catalogs should not link to 'items'.

**Comment by philvarner** [comment]
I have it written up as part of the search meta work, so I'll split it out and create a new PR to add it tonight or tomorrow.

**Comment by philvarner** [comment]
Created https://github.com/radiantearth/stac-spec/pull/487/files (after an accidental PR against master)

**Comment by m-mohr** [comment]
I'm a bit confused now as there are ItemCollection specifications in #482 (which is the right place to put it in my opinion) and #487.

I still disagree that this should be a core specification for now. It is only used in API for now and will probably get an extension that uses it, but in this case it just belongs in API + extension, but not in core as it is not a core entity used throughout the specs. If you don't use an extension, it's never used in static catalogs, only in dynamic. If it's a core spec we would have to explain it similarly to the other core specs, which I feel is confusing as it doesn't play a very central role. I would have a hard time explaining in presentations what ItemCollection is about and why it's an important core spec.

**Comment by joshfix** [comment]
To me it feels like Item and ItemCollection are inseparable, even if ItemCollection isn't used in static catalogs.  I'm not convinced that the litmus test for whether or not something belongs in the core is whether or not it's currently used in static catalogs.  I think if you can explain the Item spec, it would be very easy to explain the ItemCollection spec, even if you had to note that it's currently only used in the API spec + extensions.

**Comment by joshfix** [comment]
Just a thought, would it be weird to just add ItemCollection to the Item spec?  Just make it an optional parent/container of an item(s)?

**Comment by m-mohr** [comment]
Merged in #487.
