### ISSUE TITLE
SAR observation direction

### ISSUE THREAD

**Issue by jbants** [radiantearth/stac-spec#496]
Radarsat-2 can look both left and right. https://directory.eoportal.org/web/eoportal/satellite-missions/r/radarsat-2

Should observation_direction be a list of `['left'], ['right'], ['left', 'right']`?

@m-mohr

**Comment by matthewhanson** [comment]
I've been wondering about this...under what conditions would a user be interested in knowing what the observation direction is?  Is it something you would search on?  If so, why?

**Comment by jbants** [comment]
I imagine if someone is looking at linear features (agriculture rows, for example), observation angles will play an important role in identification since the transmitted beam will reflect differently if it is perpendicular to the linear feature vs parallel.

I think people would search on this. Ex. Give me all scenes over my agriculture plot with a right observation angle since it's easier to identify my rows this way.

**Comment by m-mohr** [comment]
Can Radarsat-2 can look both left and right per item? Or is it just per collection?

**Comment by jbants** [comment]
I believe it is at the item level.

**Comment by m-mohr** [comment]
Could you check that (any maybe provide a source for that information)? I want to make sure that we really have a use case for it before changing it.

**Comment by matthewhanson** [comment]
Not sure I'm following this here.  For one specific Item, the look direction will be either "right" or "left" right?   If it looks both right and left in one Item then your scene will contain assets in two different locations.

**Comment by jbants** [comment]
You guys are right. It would be on the collection level. 
The item can only have one observation angle.

**Comment by m-mohr** [comment]
Okay, good. Then this is covered by the summaries extension and no changes required.

Thanks, closing.
