### ISSUE TITLE
extended metadata rel for place to put additional metadata

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#498]
Would be nice to have for 0.8.0
Discussed on phone June 17, needs PR.

**Comment by m-mohr** [comment]
What was the conclusion? I can't remember it and who's responsible for the PR?

**Comment by m-mohr** [comment]
I think we moved away from this idea again. Primary use case was the projection extension, but seems we don't put it into a separate file. Also discussed this once again on the following phone call and it seemed to be not a very good idea as you don't know where to look for data. In extended or in "core"? So you need to request both files anyway so what's the point on separating?!
