### ISSUE TITLE
Use ID instead of name

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#499]
In eo:bands, and perhaps in other places, the "name" field should be renamed to "id", as name and common_name are too alike, and id is more descriptive.

Also, double check the rest of the spec to check consistency of the usage of the fields "name" and "id".

**Comment by m-mohr** [comment]
We use name in the following places:
* EO extension, in bands
* SAR extension, in bands
* Collections, in providers
* Label extension, several places.

I don't have strong feelings about name vs id in general, so I'm fine with either renaming to id or leaving it as it is.
* For bands, both name (as specific name) and common_name make sense, but id and common_name is fine, too. Renaming name in providers to id doesn't make sense.
* Organizations and persons have names, not ids (well, they have, but that's not what we want to have in that field). 
* Labels should probably follow the decision we come up with for the bands?

**Comment by philvarner** [comment]
+1 for id to make it clear that it's a unique identifier for the entity.

**Comment by joshfix** [comment]
Also +1 for using `id`

**Comment by m-mohr** [comment]
What I find quite misleading with renaming band name to band id, is that it currently can't be used as such in STAC. We have the eo:bands reference in the assets, but instead of using the id users have to specify the array index. Therefore, for me it doesn't really fell like an id.

**Comment by matthewhanson** [comment]
I agree that it doesn't feel like an ID.  I would have preferred to keep eo:bands as a dictionary and actually have the IDs as keys.

**Comment by matthewhanson** [comment]
We should resolve this for 0.8.0. 

I've changed my mind on this and agree with @m-mohr's comments. It should stay as name as id implies a unique identifier, but this isn't a key so cannot be guaranteed to be unique (even though it should be)

**Comment by m-mohr** [comment]
Did we agree on no changes? If not, please reopen. :-)
