### ISSUE TITLE
Using self-describing hashes for Checksum Extension

### ISSUE THREAD

**Issue by vmx** [radiantearth/stac-spec#503]
There's a project called [Multihash](https://github.com/multiformats/multihash) which specifies self-identifying hashes. With bundling the hash function directly with the hash, you wouldn't need to specify it within the JSON. So you would have a single field called `checksum` which contains the hash.

Example: Checksum for a text file with file content `test`.

| Algorithm               | Example                                                      |
| ------------------------ | ------------------------------------------------------------ |
| sha1 (160 bits)            | `1114a94a8fe5ccb19ba61c4c0873d391e987982fbbd3`                           |
| sha2 (256 bits)            | `12209f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08`                   |
| sha2 (256 bits truncated to 160 bits) | `12149f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b` |

**Comment by m-mohr** [comment]
This sounds very interesting, but how sustainable/stable is this initiative? Is anybody backing it for a longer time?

It seems there are efforts to make a IETF RFC from it at https://github.com/w3c-dvcg/multihash, which is good. Once that's done we could easily take it over, I guess.

**Comment by m-mohr** [comment]
I'll take this on soon. Question is: Do we replace the current extension with a new multihash extension?

**Comment by matthewhanson** [comment]
I think we can just replace the existing extension.

**Comment by vmx** [comment]
Sorry, I didn't follow this issue closely. There is still the plan to bring Multihash to the IETF (that effort just got rebooted).

**Comment by vmx** [comment]
Now I will follow it. So if you've any questions or there's any way to help, let me know :)

**Comment by m-mohr** [comment]
I you like, you could work on changing the checksum extension for 0.9, @vmx.
I thought about just deprecating the old fields and adding a new checksum:multihash field. In 1.0 we could them remove all the other fields.

**Comment by vmx** [comment]
@m-mohr Sounds good, I'll have a look next week.

**Comment by m-mohr** [comment]
Has been merged.
