### ISSUE TITLE
Change references from "WFS 3" to "OGC API - Features - Part 1: Core"

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-spec#512]
Not sure what the acronym for it is, but we should figure it out (OGCAPIFP1C?, lol).

Also mention that OGC API - Features - Part 1: Core was previously WFS 3.

I'm glad to make the changes, but I wanted some indication as to if we should do it or not first.

**Comment by m-mohr** [comment]
OGC still figures out the acronym. Until they made the first release under the new name, I'd leave it as it is. People know it still as WFS3 and OGC ist still working on the new names etc.

**Comment by m-mohr** [comment]
Will it be OAFeat 1.0?! 🤣 

See https://github.com/opengeospatial/oapi_common/issues/35#issuecomment-509598050
