### ISSUE TITLE
Absolute links in JSON schemas

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#528]
Currently, in many of the JSON schemas we reference external schemas as the Item JSON Schema. 

Example:
```
...
  "allOf": [
    {
      "$ref": "https://raw.githubusercontent.com/radiantearth/stac-spec/master/item-spec/json-schema/item.json#/definitions/core"
    },
    {
      "$ref": "#/definitions/datetime-range"
    }
...
```

The issue here is that you can't validate old versions or dev as the URL is set to master. So if master is updated, all old schemas may break. Also, I can't validate against recent changes in dev. Therefore, I'd propose to use relative links or any other solution that solves the issue.

What do you think, @jbants ?

**Comment by jbants** [comment]
Hey @m-mohr. Sorry been out for a couple days. I have a lookup table that I used to convert the master path into a path which uses the release tags. Ill double check the validator is working properly with this

**Comment by m-mohr** [comment]
Unfortunately, it got merged already without you having a look on it. So please double check whether it's working, otherwise we'd need to revert or find another solution.
