### ISSUE TITLE
GeoTiff media type

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#535]
As announced in https://github.com/opengeospatial/geotiff/issues/34#issuecomment-514078289, the official media type for GeoTiff will be `image/tiff; application=geotiff`. 

We should deprecate `image/vnd.stac.geotiff` and recommend the new one here: https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#media-types

The question is: What do we do with  `image/vnd.stac.geotiff; cloud-optimized=true`? That could be converted to `image/tiff; application=geotiff; cloud-optimized=true`, I guess?

**Comment by philvarner** [comment]
I think `image/vnd.stac.geotiff; cloud-optimized=true` was always wrong, since there's nothing vendor specific to STAC about geotiffs.  I say we completely forget about it.

I like `image/tiff; application=geotiff; cloud-optimized=true` well enough and would fully support that being the media type.  Another option would be `image/tiff; application=geotiff; cog=true`, simply because it's shorter.

**Comment by m-mohr** [comment]
> I think `image/vnd.stac.geotiff; cloud-optimized=true` was always wrong, since there's nothing vendor specific to STAC about geotiffs. I say we completely forget about it.

It was simply because there was nothing standardized. So we had to invent our own and had to specify a vendor (us). That's why STAC is in there. As I also found this wrong, I pushed the OGC GeoTiff guys to register one and they proposed the one I posted above.

> I like `image/tiff; application=geotiff; cloud-optimized=true` well enough and would fully support that being the media type. Another option would be `image/tiff; application=geotiff; cog=true`, simply because it's shorter.

I guess we should ask on the COG mailing list what they prefer. They may even come up with an official one.

**Comment by m-mohr** [comment]
Opened a thread on the COG mailing list: http://osgeo-org.1560.x6.nabble.com/Media-type-td5411498.html

**Comment by philvarner** [comment]
@m-mohr Sorry, that sounded more harsh than I meant it to be. I was trying to emphasize that it was chosen because there wasn't a better option, but there's no need to keep it around when a more standard option has emerged. Also, thanks for pushing OGC folks on this.

**Comment by p3dr0** [comment]
I would suggest the usage of the profile link relation
`
       image/tiff; profile=<URI-reference>
`
the value <URI-reference> to be defined (for example it could be http://geotiff.osgeo.org/ ) 
further reading at 
https://tools.ietf.org/html/rfc6906#section-3.1 
and check also 
https://ruben.verborgh.org/articles/fine-grained-content-negotiation/

**Comment by m-mohr** [comment]
@p3dr0 We are not going to define anything here, so you should direct your thought to the GeoTiff GitHub issue tracker and/or COG mailing list (links above). STAC would only take over whatever is standardized by the GeoTiff/COG communities.

**Comment by m-mohr** [comment]
I think we can delay this until STAC 0.9.0 as there's a very small chance IANA may not approve the suggestion by the OGC and there's no proposal yet on COGs.

**Comment by m-mohr** [comment]
The new media type has officially been adopted by OGC in the Geotiff 1.1 standard. We should add the media type in the item spec and deprecated the other media types.
