### ISSUE TITLE
Adding (content-)type to links

### ISSUE THREAD

**Issue by rouault** [radiantearth/stac-spec#54]
For consistency with WFS 3 links, it could be interesting to add a "type" property to links to describe the content-type.

So the liinks from https://github.com/radiantearth/stac-spec/blob/dev/static-catalog/examples/Planet/20170129_181030_0e1f_analytic.json would become:

```
"links": [
    { "rel": "self", "type": "application/json", "href": "http://cool-sat.com/catalog/CS3-20160503_132130_04/CS3-20160503_132130_04.json"},
    { "rel": "thumbnail", "type": "image/png", "href":"thumbnail.png"},
    { "rel": "catalog", "type": "application/json",  "href": "http://cool-sat.com/catalog/"},
    { "rel": "acquisition",  "type": "application/json", "href": "http://cool-sat.com/catalog/acquisitions/20160503_56"}
]
```

Advantages: possibiliity to add alternate representations for the same resource
Drawbacks: may make client life harder to determine "unique" resources. In particular for list of items.

e.g
```
    { "rel": "catalog", "type": "application/json",  "href": "http://itemA.json"},
    { "rel": "catalog", "type": "text/html",  "href": "http://itemA.html"},
    { "rel": "catalog", "type": "application/json",  "href": "http://itemB.json"},
    { "rel": "catalog", "type": "text/html",  "href": "http://itemB.html"},
```

So perhaps not such a good idea to have multiple representations. Or perhaps provide them as rel:alternate in the itemXXXX.json file ?

**Comment by cholmes** [comment]
Where's the section on WFS links? I'm definitely interested in consistency with them. And picked this style of rel links so that type could be possible. Does WFS require that all links have a type?

I'm not sure if there will be many cases with the 'rel' + type being the same. Hrm, except for if we do a 'source' and like a mosaic could have multiple 'source' files it refers to. Though what's the use case for the client to figure out the unique resources?

**Comment by joshfix** [comment]
FYI we do have a type property for links, it's just not required.  See the swagger spec:

https://github.com/radiantearth/stac-spec/blob/dev/api-spec/spec.yaml#L200-L215

**Comment by cholmes** [comment]
Setting this for 0.6.0 - as I think there's growing need for this. I'm looking more at 'assets', but I think it'd be good for links too. 

I think we also need to figure out types and 'sub-types', like tiff / geotiff, and then 'cloud optimized geotiff'. 

It may next sense to enumerate the link and asset 'keys' so people know what the good options are (tif vs tiff vs geotiff).

**Comment by m-mohr** [comment]
Just for completeness and as "inspiration":
WPS 1.0 has a proposal on non-existing mime types/content types: http://www.opengis.net/doc/wps1.0-best-practice-dp - section 6.
I am not suggestion to use it though, IMO it looks rather odd...

It might also be useful to add a title to the links as discussed in #81.

**Comment by mojodna** [comment]
Some WMS/WCS servers seem to use `image/geotiff` (and variants, see https://lists.osgeo.org/pipermail/gdal-dev/2006-April/008487.html) even it it's not standardized.

My inclination would be for something along the lines of:

`image/geotiff; cloud-optimized=true; type=byte`

Or, if we wanted to be strict about it:

`image/tiff; georeferenced=true; cloud-optimized=true; type=byte`

(This is highly relevant to STAC as it covers types other than COGs, but may actually belong in COG discussions.)

**Comment by jeffnaus** [comment]
Sprint-3-static

We want to support this.
We want to support our custom times which is 
image/geotiff (lets get this really registered)
image/geotiff+cog

For other types we generally recommend that use standard mime types.  including
the vendor prefix.
example: vnd.digitalglobe/til

**Comment by m-mohr** [comment]
Type and title are both available now for assets and links.
