### ISSUE TITLE
Update `stac_version` in all examples to be 0.8.0

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#543]
As the dev branch is the future 0.8.0, all the examples containing stac_version should be updated from 0.7.0 to be ready for a release.

**Comment by m-mohr** [comment]
Another ToDo before releasing is to update the UML diagram.

**Comment by m-mohr** [comment]
Made the PR for the version numbers, but draw.io semms hard to update. Could you take a stab, @hgs-msmith ?
