### ISSUE TITLE
Make license and providers consistent between Collection and Item

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#544]
Looking through the master-dev comparison I came across this addition by @mojodna 
https://github.com/radiantearth/stac-spec/commit/6c2dd82ca4db772ece19a6f2d494ad9f7f1f30d9#diff-f172c5ad070035133e672354409185fcR79

It says:

---
###
**license** and **provider** should be defined at the Collection level if possible (as either
common properties or Collection fields). Item-level definition of these fields will override
Collection `properties`. If none are defined, the Collection's `license` and `providers` fields
will be assumed to apply to related Items.
###
---

However, license and provider are given as Item properties, and at the top level of the Collection.  But here we have this odd behavior where it doesn't work like any other Item properties, as it can be used to override a top level property in the Collection.

It's also the only case where we allow overriding Collection level properties.  If we want to actually be able to override the Collection, then these should be moved out of the Item properties to the top level.

However, instead I think we should just remove license and providers from the Collection, then it can be specified as a Collection property.

**Comment by cholmes** [comment]
Decided to not remove license and providers from Collection, but to remove some ambiguity - being explicit about setting it to 'various' if multiple licenses are in the collection.
