### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#545]
New PRs have a checkbox for updating the CHANGELOG, so the most recent merges are included in it, but the older commits are not. 

I compared the branches but could only go back 250 commits to May 9th.  Will have to take another pass looking at the older commits.  

Here's an initial pass at changes.

---

## Added
- Label extension added with additional fields for describing labeled data, such as used for training data or from the output of a classification
- Timestamp fields added to `Item`: `created` and `updated` to refer to the datetime the metadata file was created or updated.
- Added Search Metadata API extension which adds fields to a response from a STAC API such as the number of items found and how many were returned.
- ItemCollection class added to spec that is a GeoJSON FeatureCollection of Items, such as what would be returned from a search. Located in item directory.
- `in` operator added to the query extension (to check if value is in a list of values)

## Changed
- Numerous typos, clarification and general word-smithing
- The API intersects parameter now accepts a GeoJSON Geometry (any type) *instead* of a GeoJSON Feature.
- `time` API parameter changed to `datetime` (changed in WFS3)
- Clarification on `include` and `exclude` parameters in the field extension and notes on default values.
- API queries should contain either `bbox` or `intersects`.

**Comment by m-mohr** [comment]
Done.
