### ISSUE TITLE
Remove prefix for datetime range extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#556]
As we approach a 1.0 release I feel that we need to start moving away from extension prefixes for some extensions that end up being used by multiple other extensions. These seem to be more core to me, and while they could remain extensions by removing the prefix it brings them closer to being able to make them core in the future without as many problems with backward compatibility.

The Datetime range extension is one such extension. 

- The dtr prefix is redundant with the field names already having 'datetime' in the name. 
- DTR is used by SAR, is certainly applicable to EO, it would be used in mosaics as well as drone imagery and LiDAR. In fact any type of sensor at all has a non zero collection time so it's theoretically applicable to any sensor collected data.

It may make sense for a core field, but I think the first step is at least removing the prefix for it.

**Comment by m-mohr** [comment]
I have no strong opinion in this issue, but would like to mention that extensions are useful to better model dependencies between fields. For example, the two fields in datetime-range are required and both need to be available. We can't model that very well as core fields as we can't require them. So users could just use one of the fields and that's not very helpful. So leaning towards more extensions, but fine to remove prefixes.

**Comment by matthewhanson** [comment]
Excellent point. Keeping it as an extension makes sense, but without a prefix.

**Comment by m-mohr** [comment]
Prefix: I think we should invest more thoughts around dates/times in general (see #351) and then align what we came up with.

**Comment by matthewhanson** [comment]
I'm not sure how the proposed fields in #351 are related to these datetimes though. Those all have to do with datetime of access/creation/update times of the metadata record, this is for the actual datetime of the data.

**Comment by m-mohr** [comment]
I just want to make sure we don't need to change things again once we may decide to introduce fields proposed in #351 and come up with something different there. For example, all metadata related temporal fields get a prefix and data related don't or the other way round or...

**Comment by cholmes** [comment]
Yeah, I think we should have a set of 'core extensions', that don't need the prefix, but aren't in the core spec. It's perhaps a final level of maturity, to have the extension dropped.

Scheduling this for 0.9.0

**Comment by m-mohr** [comment]
Done, see PR #p638
