### ISSUE TITLE
revision field for Collections and Items

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#557]
We currently have a 'version' field in Collections, but nothing equivalent in Items.  See #501 for some discussion on versioning.

NASA uses the term 'revision' here, which is an update to the metadata record. This could mean it points to new versioned assets, or some properties in the metadata has changed...something is different.

From a provenance standpoint this is becomes more complicated because we want to keep all previous versions but only surface the most recent of any record during a search or browsing. This means some thought in how versioning would work for static catalogs, and how an API would default to the most recent record but allow retrieval of any past record. However those are related but tangential issues. The first step is at least having a field indicating the version of the record. Since 'version' is a bit of an overloaded term I feel that 'revision' is a bit more descriptive.

Changes:
- add `revision` field to Items
- replace 'version' field in Collections to 'revision'

**Comment by m-mohr** [comment]
For the sake of compatibility I'd stick with version as it's already used in Collections and the closer we get to 1.0, the less I'd like change the specs. But if a majority prefers Revision, I'm fine with that. The two keywords are mostly interchangeable and don't have major pros or cons.

**Comment by matthewhanson** [comment]
I'm fine with sticking with 'version', we'll just want to use the same for Collections and Items.

**Comment by hgs-truthe01** [comment]
I think this relates to #534

**Comment by m-mohr** [comment]
To continue the discussion from the call: Why should the field be top-level and not just in properties? @matthewhanson

**Comment by matthewhanson** [comment]
I think it belongs in the top level because the version would be used alongside `id`.  The unique key for any record would need to reference the `id` and the `version`.  So it seems like those belong side by side (for the `collection` it is already at the top-level).

There's still a lot to discuss - such as how multiple versions are stored in a static catalog, and how does the API work.  The API should, by default, return the most recent version of any record, but you should be able to link to any specific revision by specifying the `id` and `version`.

**Comment by m-mohr** [comment]
In collections, we don't have properties or something similar so everything is top-level. Otherwise I'd probably have put it not on the top-level there.

Do we have enough time to discuss all the other issues for 0.8 or should we move this to 0.9?

**Comment by matthewhanson** [comment]
This has come up again recently and it's starting to be a bit of a problem as without a way to handle versions the default approach is to overwrite previous versions which makes data provenance impossible.

I'm fine with version in properties, it's actually more useful there I think because you can put it in collection properties indicating all items in a collection are the same version which is fairly common to reprocess an entire collection at once and create a new revision.

**Comment by m-mohr** [comment]
So is there anything that holds us back to add such a field to the item?

**Comment by m-mohr** [comment]
@hgs-truthe01 I don't really understand how the ETag changes would work for static catalogs. Maybe something to discuss at the sprint?

**Comment by hgs-truthe01** [comment]
@m-mohr I think you are right that as defined it doesn't solve the problem. I forgot that the Spec side of things doesn't include anything in the document, but for our implementation we added a top level field to store the revision. So I think you are right that it is a good topic for the sprint.

**Comment by matthewhanson** [comment]
Nothing holds us back, but just adding the `version` to Items doesn't completely solve the issue as we need to define the API behavior for multiple versions, and also how it works with static catalogs.

I do think this is a super important topic to figure out at the sprint, as it's required by most of the use cases I see.

**Comment by scisco** [comment]
I think my PR solves the version issue: https://github.com/radiantearth/stac-spec/pull/635
