### ISSUE TITLE
`self` links should always be absolute URLs

### ISSUE THREAD

**Issue by alkamin** [radiantearth/stac-spec#56]
This change had unanimous agreement. This would allow all other relative links to be clearly resolved. While it may make moving catalogs slightly more involved, we feel it is a reasonable burden that results in a more easily navigable catalog.

**Comment by cholmes** [comment]
We should probably clarify what a 'root' link means in STAC API, and what it should point at.

**Comment by cholmes** [comment]
So this is all up to date for `self` links. I think still need to double check for `root`, but I think I'm just going to change this issue to self only, and then we need to do a bit more work in general on defining how root works, especially in context of stac api stuff.
