### ISSUE TITLE
Where to put extension fields in collections? 

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#560]
So, we are now getting more extensions to the collection spec. @matthewhanson proposed Asset Schema and I'm about to propose to extend the Scientific extension to also cover Collections (and Catalogs?). Where to put the new fields? In Items we have properties, but properties are used by the commons feature. So should they all be on the top level?

**Comment by matthewhanson** [comment]
I'm not keen in getting the top-level all cluttered.  But if we do put it at the top level they could at least go under a single field.  Like with assets there is a single top level field called "asset" like in Items. For scientific would you be ok with a top level field called "scientific"?

**Comment by m-mohr** [comment]
I'm not a fan of a single field as it would make the spec different for Item and Collections, but I guess it should just be the same? I don't really see a problem to put them top-level though. 
I'd like to use properties for collection extensions only as we do for items, but then we'd need to rename commons to something else (I never found properties very descriptive anyway). `item_properties`? `common_properties`? `commons`?

**Comment by matthewhanson** [comment]
I agree `properties` isn't a great name, but I think it's best to use the same name as what they are in the Items. 

I'm just not a big fan of clutter, esp at the top level, when things could be categorized. 

Does WFS provide any guidance for adding fields to collections?

**Comment by m-mohr** [comment]
No, I don't think so, but not 100% sure either and if I recall correctly @cportele said they haven't thought about extensions very much yet.

Would make a section such as extended make sense? Although I don't think we would add very much fields to the top level and I'm also not overly concerned about cluttering the root level.

Putting it in properties would make validation easier. I don't see a good reason why properties should be the same in collections. What are your thoughts behind that, @matthewhanson?

**Comment by m-mohr** [comment]
So as the scientific extension adds to the top-level for now, I'd say there's nothing more to do for 0.8 and we can move this issue to a future release.

**Comment by m-mohr** [comment]
We leave this up to the author of an extension.
