### ISSUE TITLE
Scientific extension for Collections

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#561]
The Scientific extension is not usable in Collections, but I think in most cases DOIs and citations are available for Collections and not so often for Items. Therefore, I would propose to extend the Scientific extension to also cover Collections. Maybe even Catalogs?

I'll make a PR once we have consensus on #560.

**Comment by matthewhanson** [comment]
I agree, they do make more sense with Collections. I don't see the need for catalogs.

In a way though, why would this not belong in properties as part of commons?  If it's a DOI and citation for a collection of data it really does apply to all Items doesn't it?

**Comment by m-mohr** [comment]
Yeah, in most cases it should. Doesn't work if you have different citations/DOIs per Item and one for the whole collection.

I never looked at `properties` this way. I always looked at it from the Item perspective where you just put common things in collections. Your comment is the other way round. We specify something in the collection and it's automatically available for Items... It's technically not really different, but more a thing in my head that I haven't thought about too much. Maybe there's also room for improvement in describing the property field with this in mind.

**Comment by matthewhanson** [comment]
I don't see those things as all that different.   

But I could also see putting it at the top level of Collections as well.

**Comment by cholmes** [comment]
I see value in putting it at the top level of Collections. Don't think it should be in Catalog though. Collections to me is useful metadata about the set of data, like what should be harvested by a CSW, while Catalog is just a structure.
