### ISSUE TITLE
Update the UML

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#566]
We should have an updated UML diagram for 0.8.0 release, or else just not include it.

**Comment by m-mohr** [comment]
The UML was updated. The only things missing are the details about the Spatial Extent Object, the Temporal Extent Object (in Collections) and the Stats Object (in Catalogs/Collections). Not sure how strict we should be, I'd be also fine to leave it as it is, but if you have the time @hgs-msmith then that would be something you could improve.

Leaving this open for a 0.8.0 to check whether we had the time to update after the RC.
