### ISSUE TITLE
Label Extension: Overview property should be list

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#584]
Similar to #578, the `label:overview` property is an object that applies to a  single `label:property`; since there can be several `label:overviews` if there are multiple properties, the spec needs to allow for multiple overviews.

This indicates that the `label:overview` property should be renamed to `label:overviews`, to indicate that the value is a list.

**Comment by lossyrob** [comment]
Pluralization of `overviews` related to #586

**Comment by cholmes** [comment]
This looks merged. Closing
