### ISSUE TITLE
Pluralization of properties that are lists

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#586]
This issue is in particular about two properties in Collections, but speaks to a general best practice that should be used throughout the spec.

In collections, the `extent` object has a properties `bbox` and `interval`. The singular nature of those property names indicates that there is a single bbox and interval; however, the properties are a lists of bboxes and a list of intervals, respectively.

I propose that any property that has a list value should have a pluralized name. So this:

```
  "extent": {
    "spatial": {
      "bbox": [
        [
          39.28919876472999,
          -5.878778696206506,
          39.356865475223195,
          -5.722212794937691
        ]
      ]
    },
    "temporal": {
      "interval": [
        [
          "2016-08-28T00:00:00Z",
          null
        ]
      ]
    }
  }
```

should actually be:

```
  "extent": {
    "spatial": {
      "bboxes": [
        [
          39.28919876472999,
          -5.878778696206506,
          39.356865475223195,
          -5.722212794937691
        ]
      ]
    },
    "temporal": {
      "intervals": [
        [
          "2016-08-28T00:00:00Z",
          null
        ]
      ]
    }
  }
```

**Comment by m-mohr** [comment]
We inherit your example from WFS. We can't change it or we would loose WFS compatibility. Therefore I'm strongly in favor of not applying the proposed changes.

**Comment by lossyrob** [comment]
@m-mohr that makes sense, thanks for the clarification - I agree if that's what WFS wants, that's what we'll need to keep.

For something like the `label:overview` property mentioned in #584, would it make sense to modify the pluralization as this is not part of WFS? In general, would it make sense to keep pluralization consistent _unless_ it breaks from WFS?

**Comment by cholmes** [comment]
We probably could have suggested a change to WFS, but they've just locked in 1.0.0, so we're probably set with it. 

I'm cool with keeping pluralization consistent unless it breaks from WFS.

**Comment by m-mohr** [comment]
Agreed. Are there more places to change except for the label extension?

**Comment by m-mohr** [comment]
Should we change it to be pluralized before the 0.8 release?

**Comment by matthewhanson** [comment]
I would be for changing it to be consistent before 0.8.0 final release unless it breaks from WFS.

**Comment by lossyrob** [comment]
Me too. Let me try to fire off a PR today.
