### ISSUE TITLE
bbox in GET request v0.7

### ISSUE THREAD

**Issue by mzaglia** [radiantearth/stac-spec#587]
Should the bbox in the query parameters of a GET request be between []?

**Comment by aznan2** [comment]
OGC API - Features does not use brackets:
http://docs.opengeospatial.org/DRAFTS/17-069r1.html#_parameter_bbox

> Example 5. The bounding box of the New Zealand Exclusive Economic Zone
The bounding box of the New Zealand Exclusive Economic Zone in WGS 84 (from 160.6°E to 170°W and from 55.95°S to 25.89°S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.

**Comment by m-mohr** [comment]
Fixed in STAC API v0.9.
