### ISSUE TITLE
Could STAC 'license' property be implemented using OAPI-F rel:license link ?

### ISSUE THREAD

**Issue by rouault** [radiantearth/stac-spec#603]
There's a small overlap between STAC mandatory 'license' property and the OAPI-F rel:license mechanism. 
"Example 4. Feature collections response document" of http://docs.opengeospatial.org/is/17-069r3/17-069r3.html shows in collection description the following links
```
      { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
          "rel": "license", "type": "text/html",
          "title": "CC0-1.0" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
          "rel": "license", "type": "application/rdf+xml",
          "title": "CC0-1.0" }
```
That mechanism could probably be used in replacement of STAC 'license' property field. The only difference is that when using the links mechanism a href is mandatory, whereas STAC 'license' is equivalent to the "title" field of the OAPIF link

**Comment by m-mohr** [comment]
STAC also allows links with rel=license. Such a link is required if the license field is set to "proprietary" and optional otherwise. The license field is an addition to OAF  as we found the license (at least in Collections) to be one of the most important fields. Without license you can't use the data. So I think STAC is compatible with OAF here.

**Comment by rouault** [comment]
Thanks. I overlooked the longer explanation in https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md  . My point that was formally you wouldn't need to add an extra field, but you could put an additional requirement over OAF to make a rel=license link compulsory. But I don't think further action is needed as the relationship between both has been considered when establishing STAC spec.

**Comment by m-mohr** [comment]
@rouault Reason mainly was that we can more easily require and validate a license field, but validating that a link with rel=license is available and has a (only in this case required) title in a consistent format (SPDX) is somewhat complex and not easy to do or understand. Also, if a separate required field is available, users are more likely to fill it.
