### ISSUE TITLE
Deprecate collections and/or items?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#615]
In openEO we have added a boolean field `deprecated` to the Collections to indicate outdated/deprecated collections. If the field is set to true, a link with relation type `successor-version` can be added to the `links` and refers to the collection that can be used instead.

Is that something that is also interesting for other people? If yes, we could add it for collections and/or items to either the core or as an extension.

**Comment by matthewhanson** [comment]
It does seem useful. We still really need a version in the Item though.

**Comment by m-mohr** [comment]
Just wondering whether deprecated and version could simply be an Item extension?
For collections: It currently has version in the core, deprecated would be on the same level?!

**Comment by matthewhanson** [comment]
I think `version` is definitely a core field, and it's long overdue.   It goes hand in hand with `id`, as without it you can only define a new version by giving it a new `id` which is definitely not the behavior you want when versioning.

**Comment by m-mohr** [comment]
To be added as an extension.
