### ISSUE TITLE
Inconsistent schema file names

### ISSUE THREAD

**Issue by simonkassel** [radiantearth/stac-spec#618]
There seems to be some inconsistency around how the schema files are named. The base STAC objects have schema files that match the name of the object (e.g. [catalog.json](https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/json-schema/catalog.json)) while the extensions seem to all be named schema.json. This is causing an error when trying to validate with [jsonschema](https://pypi.org/project/jsonschema/) because the ID's (e.g. in the [EO extension schema](https://github.com/radiantearth/stac-spec/blob/4cd7df0fbadb94e7fc48e8d54abc5ffda9ce896a/extensions/eo/json-schema/schema.json#L3)) aren't matching name of the files. 

Is there a reason that this is the case? 

I have been using [these modified schemas](https://github.com/simonkassel/stac-spec/tree/sk/refactor-extension-schemas) in the interim.

**Comment by lossyrob** [comment]
It seems to me that using `jsonschema` directly in the CircleCI against the examples might be the right way to go. `stac-validator` does more general validation against core objects AFAIK, and doing something more concrete for each case would probably be pretty straightforward.

**Comment by m-mohr** [comment]
Good question, PR #622 should help to fix the issue, right? @simonkassel 

Nevertheless, we should think about distinct naming?! @jbants 

In the long run we need to set up the CI so that schemas and examples are checked, see #445. @lossyrob

**Comment by m-mohr** [comment]
Should be solved for 0.8.1 with PR #622

**Comment by jbants** [comment]
I'll make an issue for updating CircleCI with `jsonschema` directly @lossyrob
