### ISSUE TITLE
Update CircleCI to use jsonschema directly

### ISSUE THREAD

**Issue by jbants** [radiantearth/stac-spec#623]
Use `jsonschema` directly instead of worrying about linking and specific error

**Comment by lossyrob** [comment]
Feel free to crib some code from here if it's useful https://github.com/azavea/pystac/blob/develop/tests/utils.py#L122

**Comment by m-mohr** [comment]
I think this is OBE. #834 has everything we need and is just waiting on the examples being valid. We need to get #874 in at least or do #821.
