### ISSUE TITLE
Inconsistent extension schema format

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#624]
There are inconsistencies in how the schemas inherit other requirements, e.g. an Item schema not inheriting the Item schema as a requirement. 

For example, in EO, there is a `allOf` ref to Item, as well as internal definitions:

https://github.com/radiantearth/stac-spec/blob/master/extensions/eo/json-schema/schema.json#L6

In the label extension, we don't have that same `allOf` structure:

https://github.com/radiantearth/stac-spec/blob/master/extensions/label/schema.json

We've seen that this means a validation against a label item schema can be incorrect, as it does not also validate that it is an Item.

**Comment by lossyrob** [comment]
I'd also recommend that as part of this, we maintain consistency in the extensions of placement for and naming of the schema file. To follow the schemas of the core objects, extensions should:

- Place their schema in a folder under the extension called `json_schema`
- Be named with the extension and the object the are extending, e.g.: `eo-item.json`, `label-item.json`

**Comment by m-mohr** [comment]
The reason for the inconsistencies is simple. We don't have anybody who is the main instance to maintain the JSON schemas and people writing extensions do the schema often just as a side project without really knowing what they are doing as we also don't have any guidelines for that. So yes, fully agreeing with you. PRs are welcome.

**Comment by lossyrob** [comment]
Great, thanks @m-mohr. My colleague @simonkassel fixed a few of these in the branch he mentioned in #618, and we are planning on fixing the rest as well.

**Comment by m-mohr** [comment]
@lossyrob One thing I forgot: Please check back with @jbants regarding the restructuring. I think he renamed all extension schema files to schema.json at some point so that it works better with STAC validator. Not sure how much the validator relies on the structure.

**Comment by matthewhanson** [comment]
I'm all for this, along with any sort of documentation/guidelines.  What I've done in the past when writing an extension is use another extension's schema as a template, fiddle with it a bit to generate some sort of Frankenstein schema that doesn't work, then @m-mohr goes and fixes it.

**Comment by m-mohr** [comment]
Yeah, JSON Schema can be tricky at times. I'm usually using https://www.jsonschemavalidator.net/ to check the schemas against the examples when writing them.

**Comment by lossyrob** [comment]
With https://github.com/radiantearth/stac-spec/issues/623 it should make ensuring extension schemas are correct as a necessary part of merging PRs.

@jbants I had some ideas on how to implement that, and want to touch base about the schema filenames. Will you be at the sprint? Maybe something we can hammer out in DC.

**Comment by jbants** [comment]
@lossyrob Yup, I'll be there. Lets chat then.

**Comment by m-mohr** [comment]
The original issue has been fixed in issue #828.

**Comment by m-mohr** [comment]
And the other issue is tracked in #835
