### ISSUE TITLE
Update STAC API to align with WFS 3

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#65]
One of the major decisions made last week in ft. collins was to make it so STAC API is compliant with WFS 3.0. See [stac wfs discussion](https://github.com/radiantearth/community-sprints/blob/master/03072018-ft-collins-co/notes/wfs-stac.md) and the [stac api breakout group notes](https://github.com/radiantearth/community-sprints/blob/master/03072018-ft-collins-co/notes/stac-api.md). 

This will mean that the OpenAPI document will be an 'example' like the WFS openapi stuff, and we'll need to specify STAC as a set of extensions to WFS. So the narrative / guide will likely need to expand.

- [x] Update the openapi document with path changes [api-spec/](https://github.com/radiantearth/stac-spec/tree/dev/api-spec) (progress [here](https://github.com/radiantearth/stac-spec/pull/55/commits/f2f3975739d53c34c86543e5637201b6bffa23de))
- [x] Update api-spec narrative document describing how STAC is now a WFS
- [x] Specify the STAC API search extension to wfs ```/search/stac```
- [x] Articulate how one could have multiple 'collections' with schemas or just a single schemaless items collection
- [ ] Explain how to do 'content extensions' in STAC that do cross collection search on commonly defined fields.

**Comment by matthewhanson** [comment]
WRT /search/stac endpoint

Would STAC core technically be an extension to WFS?

Does WFS specify search extensions like this?   I was just wondering why isn't the STAC search endpoint just /search.  Is it because it's going to diverge from the WFS search endpoint parameters?

**Comment by cholmes** [comment]
We originally just had as /stac endpoint, but the WFS group expressed interest in doing a /search endpoint, and requested we do /stac under it. But yeah, the idea was to have stac core technically be an extension to WFS, and yes, the /stac would let us diverge from WFS search endpoint parameters.

**Comment by cholmes** [comment]
Didn't quite get to the last bullet point, but I think it's close enough to call this done.
