### ISSUE TITLE
Create diagram for viewing/sun geometry angles in view extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#653]
Working on creating a diagram clarifying the angles used in the view extension (#644 )

- view_angle
- incidence_angle
- azimuth_angle
- sun_azimuth_angle
- sun_elevation_angle

**Comment by cholmes** [comment]
To move to view extension

**Comment by m-mohr** [comment]
I've migrated it to https://github.com/stac-extensions/view/issues/2
