### ISSUE TITLE
EPSG code

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#654]
We talked about the EPSG code in the `eo` extension, as it clearly is not specific to `eo` and seems odd to be there and not be in `sar` for instance (or in `pointcloud`) when it is equally applicable to any geospatial data.

It was also brought up that the projection could change per asset as well.

So what should we do with the EPSG code?

**Comment by m-mohr** [comment]
Well, in theory it fits very well in the Proj extension: #485 
That said, the Proj extension may have too many complex fields to be core although epsg code could be core.

**Comment by matthewhanson** [comment]
Sure, it makes sense in that extension, but should it be in core?  And if in core, how do we reconcile how it can vary by asset?

I'm not convinced that it belongs at all, as I'm not sure of the use case where people are searching on it.

**Comment by m-mohr** [comment]
Oh, you are thinking about removing it at all? Or more about making it asset specific?

**Comment by matthewhanson** [comment]
I'm not proposing anything at the moment, wanted to see what other people thought about it, but yes I am wondering if it could just be removed, and people who want more specific proj info can use the proj extension.

**Comment by m-mohr** [comment]
> I am wondering if it could just be removed, and people who want more specific proj info can use the proj extension.

Sounds very reasonable to me.

**Comment by matthewhanson** [comment]
We decided this could be removed from EO and belongs in the PROJ extension - #485
