### ISSUE TITLE
Combining eo:bands into assets

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#656]
The original thinking for a separate eo:bands field for spectral data was that we could define the bands on the sensor, then reference those from the assets so that we would not have to repeat information when a band is used in more than one asset.   So we have an asset:

```
        "B2": {
            "type": "image/x.geotiff",
            "eo:bands": [
                1
            ],
            "title": "Band 2 (blue)"
        },
```

Then our bands property is:
```
        "eo:bands": [
            {
                "name": "B1",
                "common_name": "coastal",
                "gsd": 30,
                "center_wavelength": 0.44,
                "full_width_half_max": 0.02
            },
            {
                "name": "B2",
                "common_name": "blue",
                "gsd": 30,
                "center_wavelength": 0.48,
                "full_width_half_max": 0.06
            }
     ]
```

However a few things have happened since then. 

1. We now have an asset definition as a way to provide Asset information at the collection level
2. the realization that 'gsd' in eo:bands is really a characteristic of an asset, not a band. We can get around this by adding in another band with a different gsd, but then we are really not reusing bands like originally intended
3. it seems that in practice, it isn't common to have bands referenced in multiple assets

One option that can greatly simplify this is to just put the eo:bands info in the asset, so:
```
    "B2": {
        "title": "Band 2 (blue)",
        "type": "image/x.geotiff",
        "eo:bands": [
            {
                "common_name": "coastal",
                "gsd": 30,
                "center_wavelength": 0.44,
                "full_width_half_max": 0.02
            }
        ]
    },
```

This avoids the entire referencing back to another array to find out what's in the asset.  And the spectral band info is still at the Collection level, but consolidated so easier for humans.

The drawback is that the asset info is duplicated at the Item level the way we have things right now, unless we allow for partially described assets at the Item level (e.g., just href, and requires deep merge with asset definition to get the whole thing).

**Comment by m-mohr** [comment]
Sorry, I don't get it. Why is gsd still at the item level if it is asset specific? How is the relation between asset-level and item-level bands? Why is the band name missing from the asset-level band? Would I be allowed to also use other fields at the asset-level? Maybe a full item example would help...

**Comment by m-mohr** [comment]
Related PR, which had some discussions and was closed: https://github.com/radiantearth/stac-spec/pull/270

**Comment by matthewhanson** [comment]
GSD is still at the Item level because it represents the best possible resolution across all bands for the Item. This change wouldn't affect that at all.

Leaving out band name was just an oversight. 

Nothing here requires the use of an asset definition. 

I'm not even convinced myself bands should be folded up into asset, but I thought it was worth discussing.  The problem that needs to be solved, and that the current behavior is not modeling well, is that `eo:gsd`, and `sar:data_type` and `sar:units` from the `sar` extension are not attributes of spectral bands (eo) and data_type and units are absolutely not properties of polarization.   What that leads to is having to duplicate certain bands with just slightly tweaked variables.

If we just moved resolution into the assets that would also solve the problem. The question about adding in other attributes is a good one, and this is really what @hgs-truthe01 has always been pushing for with the common metadata model, so that you could define any attributes at any level.
