### ISSUE TITLE
instrument extension?

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#657]
As discussed in #644 , the `platform`, `instrument` would be duplicated between `sat` and `aerial` extensions.

One alternative is to create another extension, called something like `instrument` that describes the names of the pieces that make up a data collected from instruments.

One might have:
- platform - REQUIRED string
- instruments - REQUIRED [string]
- constellation - a group of platforms meant to be used together
- campaign, or mission - to describe a specific data collection.  Note that 'mission' is applicable to satellites as well, as most will have calibration periods or specific tasking for a certain mission.

**Comment by m-mohr** [comment]
This sounds reasonable. Another idea would be to have very common fields such as these live alongside the item spec. Chris wants easy to read docs and I think we could also split non-required items fields and very commonly used fields as platform, instrument, ... and for example datetime_start/end together with title, updated, etc. into a categorized list of "core" fields in a separate document. I think this would make it much easier to find the fields you need. If we split up too much, it is maybe too many extensions to go through...

**Comment by m-mohr** [comment]
Merged with #658, but will finally be solved with #659 .
