### ISSUE TITLE
Rename asset extension and consider promoting to core collection properties

### ISSUE THREAD

**Issue by anayeaye** [radiantearth/stac-spec#661]
This issue is a placeholder for a discussion at STAC Sprint 5 regarding the asset extension. Asset is implemented in collection properties and allows users to discover the types of assets that can be searched for in a collection's items--such as individual geotiff bands.

1. The extension should be renamed something like `asset_definitions` for clarity.
2. The new asset `role` field used to explain the roles/purpose of the asset should be added to object fields alongside `type` and `title`. 
3. The extension should be considered for promotion to a core collection property.

**Comment by anayeaye** [comment]
#663

**Comment by anayeaye** [comment]
This issue is only related to the links above if we will also include `role` and `description` in the `asset_definition` object fields.

**Comment by m-mohr** [comment]
Point 2 is part of PR #677.

**Comment by m-mohr** [comment]
1. Is fine for me. What does this exactly include though? Also renaming the field name? Just the extension title? Or the folder?
2. Point 2 has been solved with PR #677.
3. I think it doesn't meed the criteria yet and I'd leave it as extension for now. Can be reconsidered for 1.0, I think.

**Comment by anayeaye** [comment]
1. I think this is solved now, the extension rename to Asset Definition that is still stored in the 'asset' folder seems right.
2. Agreed.
3. Sounds right.

So I guess this issue is resolved unless we want to leave it open for 1.0 discussion.

**Comment by cholmes** [comment]
What remains open for 1.0? Whether to promote it to core collection properties?

**Comment by cholmes** [comment]
Moving to beta2, as I think we'd want some feedback in beta1 and see how widely it gets used.

**Comment by matthewhanson** [comment]
The asset definition extension has been renamed to `item-assets` and the field name is now called "item_assets" - see #787 .

I agree that it probably belongs in core - but let's leave it as an ext for beta1.
Closing this issue since the renaming happened, and we can open new issues for promoting extensions to core for beta2 or final.
