### ISSUE TITLE
Add `description` to asset

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#663]
In the SAR extension sar:bands is really used to describe characteristics of different assets due to processing or collection configuration.

In that there was `description`, which seems more general than just SAR for assets in general.  Especially with an asset definition, `description` seems like it may be useful to better describe what an asset is beyond the title.

**Comment by m-mohr** [comment]
Asset descriptions could indeed be useful, although such descriptions could probably also live in the item description.

**Comment by ucalyptus** [comment]
Can I be assigned this? @anayeaye  @matthewhanson
