### ISSUE TITLE
Unclear what to do for proprietary license with no url

### ISSUE THREAD

**Issue by jisantuc** [radiantearth/stac-spec#664]
Per the collection spec, `license` is:

> REQUIRED. Collection's license(s) as a SPDX License identifier or expression. Alternatively, use proprietary if the license is not on the SPDX license list or various if multiple licenses apply. In these two cases links to the license texts SHOULD be added, see the license link relation type.

In the proprietary case, I `SHOULD` add a link to the license. But sometimes I don't have a link. Sometimes I'm just making a catalog and don't want to license it with a permissive license (e.g. I'm making a catalog out of data that someone else owns that I can't license in any particular way), but I also have no idea where a link for a proprietary license would be.

I'm proposing an additional option for `license`, which is `unlicensed`, and then a revision:

> Collection's license(s) as a SPDX License identifier or expression. Alternatively, use proprietary if the license is not on the SPDX license list or various if multiple licenses apply. In these two cases links to the license texts MUST be added, see the license link relation type. Alternatively, use unlicensed if no SPDX License applies to the collection and you cannot provide a link to a license.

This could also include a link to GitHub's [Choosing a License](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license) docs to help people understand the trade-offs of licensing/permissively licensing/not licensing catalogs, though I'm not sure if the same rules apply for software and data catalogs.

**Comment by m-mohr** [comment]
Thanks for the thoughts, but I don't agree with them.

1. "unlicensed" would imply that the owner never chose a license, but what you indeed want to tell is that you don't know the license.
2. IMHO unlicensed data/code/whatever is not useful at all. If you don't know the license, you can't use it without getting in trouble. So the data is not of any use for the user.
3. I don't think a specification is the right place to educate the user how to license. That's maybe something for a best practice, but not for a spec. We also don't teach user how to write a good description etc.

If there's really a case where you don't know the license, I'd say simply use "proprietary" and don't provide a link (it's only "SHOULD" in the spec, not "MUST"). That indicates the user needs to look himself for a license.

Out of curiosity, why would someone make a catalog for data where he doesn't even know whether somebody can actually use it? Is the data you are speaking about a public dataset? Really curious what it is...

**Comment by jisantuc** [comment]
Defensively, if I have some client data lying around that I need to make a STAC out of for testing or to ship to them, but I'm leary of it wandering off by accident (I can think of several non-malicious ways this can happen), I may be unable to attach a license. I know that I can use it, but I don't know that anyone else can. `proprietary` with no link says "there is a license that is attached to this data, it's non-standard, and I can't tell you the terms." I don't think that covers my current case, where I'm cheaply producing a STAC that I want to communicate has no license attached in case it wanders off, but that I'm planning to destroy afterward.

I'm happy with `unknown`, though I think `unlicensed` also communicates that "you have not been given any explicit permission to use these data".

I disagree that this spec in particular shouldn't educate users about how to choose a license. To the extent that the point of STAC is making data exchange easier, we should also help people to ensure that they're licensing the data in a way that facilitates (or doesn't) that sharing in ways that accord with their intents.

**Comment by m-mohr** [comment]
We made the field required by intention as we want catalogs to be licensed and useful. Unlicensed data is not very useful and I'm strictly against weakening this by allowing "unknown" (or not requiring the field). I wouldn't like to propagate such options in the spec. To find a solution for you, I'd probably just go with `proprietary` (or `various` if you prefer that) and link to a file that just states what you said: "I don't know the license, don't use the data until you got permission by the author of the data."

**Comment by jisantuc** [comment]
If that's the recommendation, then the `SHOULD` should be upgraded to a `MUST`

**Comment by matthewhanson** [comment]
I see how there is a need to indicate that the data is basically private. We already know of companies using STAC internally and they are not distributing it. It's basically for Internal Use Only, but most companies are not putting together a license for internal data.  

So I think `proprietary` doesn't work, but I'm also not sure unknown or unlicensed captures what this is.   What about something like `private`, or `internal`?  This indicates that the data is private/internal to a company and is not intended for distribution.

**Comment by jisantuc** [comment]
Either of those would also work. I think the equivocation around `proprietary` ("this is mine" vs. "there's a special license that I can't show you") is where the confusion comes in, and `private` / `internal` would both do a better job forcing `proprietary` to pick a side imo

**Comment by matthewhanson** [comment]
I think private would imply (but should also be stated) that the data is private to the organizations given in the `providers` array.

**Comment by m-mohr** [comment]
Discussion during today's telco: "proprietary" without link means "private". We need to explicitly mention this in the spec.
