### ISSUE TITLE
Explain Catalog and Collection differences

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#667]
It seems that for some the differences between catalogs and collections are not clear. We should explain it better in the spec. So this is just a ToDo issue for me to explain it in the spec before 1.0.

Edit: Depends on #678.

**Comment by cholmes** [comment]
@m-mohr I could probably take this on if you can give me an idea of where people were confuse.

**Comment by m-mohr** [comment]
Oh, I'm just trying to remember the exact issues. I think the question to answer is: When to use Catalogs? When to use Collections? I don't think this is easy to explain, but here are some thoughts....

Other organizations call collections as follows (based on a [CEOS document](http://ceos.org/ourwork/workinggroups/wgiss/access/opensearch/)): dataset series (ESA, ISO 19115), collection (CNES, NASA), dataset (JAXA), product (JAXA).

That's what we also mean by collections, so examples are Sentinel-2, Landsat-7, ... (more examples from non-sattelite collections). It's what data providers publish as group of granules from a satellite, from a distinct drone project in the rain forest or so.
In general all STAC items (e.g. a Sentinel-2 scene) should belong to a STAC collection.

Catalogs are basically just used for two things:
* Split overly large collections into groups (similar to what you explained in #687).
* Group collections into a catalog of collections (i.e. as entry point).
* (Could also be used as replacement for a collection if you don't want to provide the additional metadata a collection requires.)

Collections ARE catalogs, with additional metadata.

Catalogs have a set of basic fields (stac_*, id, title, description, links). Collections are much more specific, they hold metadata so that you can actually find suitable collections for your work. You can't properly search for them. So in principle use collections for what you want user to find, catalogs just for (internal) structuring. That's nothing a user really cares about.

(I could imagine a STAC search engine that just works on collections first, we have something similar in the pipeline for openEO. Then you may better find suitable items to work with after selecting some collections. That's similar to the two-step search in OpenSearch, I think.)

**Comment by m-mohr** [comment]
I feel like this may actually be placed here: https://github.com/radiantearth/stac-spec#in-this-repository (or at least that section should be improved, too). Is probably also related to #696 - The catalog-overview.md introduced in #772 may be better suited at the top-level if collections got added. It's actually kind of strange that the catalog overview doesn't mention collections at all, probably because the document is older than the collection spec.

**Comment by brianbancroft** [comment]
@m-mohr sorry that I missed this.

Yes this does help a lot!
