### ISSUE TITLE
Define the branching / PR / changes 'process'

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#67]
As the spec stabilizes a bit we should document a process for how a new version is made and how the community reaches consensus on how a suggestion gets incorporated.  

cc @jeffnaus - you said you could help on this one.

**Comment by cholmes** [comment]
Thanks to @scisco for pushing on this, plus @m-mohr and @matthewhanson for pushing for reviewers. 

I'll try to write this up, I think it's important we have for 0.6.0. If anyone else does want to take a crack at it feel free to assign to yourself and go for it. 

We've got the CI in place now, but it probably needs a bit more validation of examples. And we've set a policy that two people have to review any PR's. 

That's probably the core, just need to write up a bit more on it, and how we're treating master / dev. Plus how we give out reviewer / write access. Was an idea to designate some people 'committers' who have the power to merge, and a broader 'reviewers' who can +1. Github can't control that, but we can also just give write access to both and tell people their role.

**Comment by m-mohr** [comment]
I think I mentioned another issue in #167: How do we make sure we always update all the version numbers hidden in lots of files?

**Comment by cholmes** [comment]
Good thought. I guess we could try some fancy thing with CircleCI? Have it automatically check that they're all the same? 

Or the manual way would be to have a 'release checklist', that has all the steps to update versions, merge to master, make a 'release' on github, make the release notes, etc. Which we should do anyways as part of this.

**Comment by matthewhanson** [comment]
anything left to add here @cholmes or can this be closed?  CI is covered by #199

**Comment by cholmes** [comment]
Yeah, I have a branch with changes I want to merge in, but need to finish it. Will do it for 0.6.0

**Comment by cholmes** [comment]
Closed with #320
