### ISSUE TITLE
Clarify usage of Commons extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#671]
Add text to clarify how and when to use Commons extensions. 

Commons extension makes more sense for static catalogs, and perhaps should also be mentioned in best practices.

For API, the API really should(?) always return the complete Item, including common properties.

Also make note from Commons extension that for describing a Collection the `summaries` extension is probably better suited than Commons (although both could be used - the Commons properties then just end up being the fields in summaries that hold a single value)

**Comment by m-mohr** [comment]
Has been solved with PR #677.
