### ISSUE TITLE
Check Catalog Definitions & Catalog Types

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#678]
1. There's a chapter about [Catalog Definitions](https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md#catalog-definitions) in the Catalog spec. It seems outdated and needs some love. 
  Especially the following part needs to be discussed. I think on the last sprint we said that these relations are not allowed, but the catalog spec mentions them:
  > Item -> Catalog (example: an item may point to a catalog to describe a set of derived assets, where it may be desirable to have the origin asset as a "parent", such as NDVI generated from RGB/IR)
  > Item -> Item (example: this relationship may be used to describe a 1-1 parent-child relationship, such as a single derived item from one parent item)

2. Also, there's the chapter [Catalog Types](https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md#catalog-types), which doesn't really fit in the spec. The [design overview](https://github.com/radiantearth/stac-spec#design-overview) tackles most of it and I think the chapters can be merged so that the types can be removed from the catalog spec.

**Comment by m-mohr** [comment]
PR #677 tackles part 2.

**Comment by cholmes** [comment]
Yeah, I think we can just remove Item -> Catalog and Item -> Item. Those relationships described should be handled by 'rel' links. 

I think the rest of the document looks ok?

**Comment by m-mohr** [comment]
Okay, i'll remove those two.

In general, the whole document is a bit strange IMHO as it explains the idea behind STAC, but for me it feels the actual specification file should only talk about the actual catalog file and how to structure it. 
All the more general stuff should be explained centrally, I think. Either in the catalog readme or even on the front page or so.

**Comment by cholmes** [comment]
I see your point. I think it's valuable to have that overview - but perhaps we just split this out into catalog-spec.md (the description of the file) and catalog-overview.md (or something like that), where we discuss the idea behind stac and what a full fledged catalog is. I think we need that somewhere in the spec.

**Comment by m-mohr** [comment]
@cholmes will create a new issue.
