### ISSUE TITLE
Move Item Recommendations to Best Practices?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#681]
There's a section "Recommendations" at the end of the Item spec. Wouldn't those things make more sense in the best practices? 

cc @cholmes

**Comment by matthewhanson** [comment]
Agree to put these in one place

**Comment by cholmes** [comment]
Yeah, I think it makes sense to put all recommendations in one place, in best practices.

Reading the metadata linking section though, I think we should be sure to mention a couple key things in the main item spec:

1) The item spec is the core set of fields, and most any real world implementation will add in their own fields, either from extensions or defining their own. In my quick read of the main spec we don't really say that - we just start talking about the required fields. I think it'd probably be good to flesh out a bit more in best practices on how to pick the right fields (like first check extensions for reuse, make schemas for your own defined data, etc)
2) The focus of STAC is on search - I think we should also say that in the main item spec.

In best practices we can make the point that you can reference a metadata document as an asset.
