### ISSUE TITLE
Moving eo:gsd into assets (remove eo:gsd)

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#690]
In working session, we discussed #685 and #656 , but could not come to a decision except we agreed that eo:gsd is not an attribute of spectral bands, since it can change due to processing. 

Instead, `eo:gsd` belongs in the assets as an array to indicate the resolution of each band in the asset.

At the Item level, eo:gsd should either be changed to an array (to include all potential resolutions from all items), or removed.

Optionally, we could add a `eo:best_gsd` or similar to the Item to contain a single number, the lowest GSD possible across all assets.

**Comment by m-mohr** [comment]
My question is how we define which fields are allowed in assets. Should it be all (common metadata model) or just a subset? How to determine, which are suitable and could be useful in other use cases?

Also, all things in assets can't be summarized in "collection-only" use-cases using the collection summaries. Therefore, I think it should also be defined on the item-level, but that would basically be a summary again. So do we allow "summaries" for all asset-level metadata we add?

I think having a field best_gsd is a bit flawed as it pushes an implementation detail to the spec. If an implementation needs the best gsd resolution for easier searching, it should be added during index creation of the back-end by simply using the smallest gsd value from the gsd summary if available (or the assets).

**Comment by matthewhanson** [comment]
Discussed in call:
- remove gsd from eo:bands

**Comment by m-mohr** [comment]
See PR #703
