### ISSUE TITLE
Make single file STAC catalogs like actual Catalogs

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#691]
The Single File STAC extension:
https://github.com/radiantearth/stac-spec/tree/master/extensions/single-file-stac

only contains Collections and Items. It's not an actual Catalog because it has none of the catalog fields:
https://github.com/radiantearth/stac-spec/blob/dev/catalog-spec/catalog-spec.md#catalog-fields

I recommend:
- renaming the "Single File STAC" extension to "Self-contained STAC"...it need not be a file after all, it's just JSON.
- Making a Self-contained STAC an actual STAC catalog with all the normal required and optional fields, and it is also
  - a FeatureCollection, where the features are Items
  - there is a collections field that is an array of collections
  - optional search object representing this catalog is the result of a search

**Comment by m-mohr** [comment]
1. I think renaming it makes sense.
2. What's the benefit? A SFS is currently extending the ItemCollection spec, right? And now it should also extend Catalog? How do we handle conflicts? Are the stac_version/extensions fields inherited from catalog or ItemCollection? They allow different values...

**Comment by matthewhanson** [comment]
The benefit of combining catalog metadata into a self-contained STAC is that it then really is a complete STAC catalog. I don't see any conflicts:

1 - The self-contained STAC is a catalog with all the normal fields, including stac_extensions which apply to the Catalog.
2 - It is also a FeatureCollection which means it has a 'type' field and a 'features' field
3 - the 'features' field is the list of items, where each one is complete
4 - there is an additional field called collections, where each Collection is a complete collection, also with stac_version, etc. that applied to that collection


I think this might conflict with ItemCollection now, I'll have to take a look.

**Comment by matthewhanson** [comment]
Still need to work out the issue of conflicting definitions of ItemCollection and Catalog, as this would be an amalgam of the two. Pushing to 1.0
