### ISSUE TITLE
Published/Created/Updated dates

### ISSUE THREAD

**Issue by palmerj** [radiantearth/stac-spec#693]
I'm interested in item/collection properties for:

- Created Date time | When the collection/item data was created
- Published Date time | When the collection/item data was published

Would there be a community appetite if I proposed an extension for this?

**Comment by m-mohr** [comment]
Related issue: #351

**Comment by cholmes** [comment]
Just working on my Planet STAC mapping, and we have updated and published (in addition to 'acquired', which maps to STAC datetime). Would be nice to use a shared definition for these for sure.  

So @palmerj - a proposal for these would be great, and I'd try them out in my Planet stuff and give feedback. I'm not sure of your difference between created and published, but happy to see the full proposal. Actually looks like #351 lays out differences and cites other works, so would be good to be aligned with that.

**Comment by matthewhanson** [comment]
We have added `created` and `updated`, meaning when the metadata was first created, and when it was last updated.  They are in the common metadata for Items:
https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md

In using these however I do wish the terms were a bit more clear.  `created` and `updated` imply to me a True/False, or Yes/No.    `created_at` and `updated_at` may be better, or `created_datetime` and `updated_datetime` to be explicit.

**Comment by m-mohr** [comment]
> In using these however I do wish the terms were a bit more clear. `created` and `updated` imply to me a True/False, or Yes/No. `created_at` and `updated_at` may be better, or `created_datetime` and `updated_datetime` to be explicit.

I disagree. I don't find them confusing and they are aligned with many other standards, e.g. Dublin Core and DCAT, which also just use the verb without any suffix. Although, they use these terms usually to specify dates about the data (i.e. assets) and not the metadata. That's something we may need to change. I guess it could be an option to rename them to metadata_created or so and leave created to the actual creation time of the data itself. Although a single date for multiple assets may be a bit problematic?!

**Comment by palmerj** [comment]
> So @palmerj - a proposal for these would be great, and I'd try them out in my Planet stuff and give feedback. I'm not sure of your difference between created and published, but happy to see the full proposal. Actually looks like #351 lays out differences and cites other works, so would be good to be aligned with that.

Thanks @cholmes. I'm on holiday for the next month, but when I return I will put a proposal together, as well as for #150 (Needed for our full use case).

> I guess it could be an option to rename them to metadata_created or so and leave created to the actual creation time of the data itself.

@m-mohr I like this idea.

**Comment by davidraleigh** [comment]
Just adding in my ideas about this from what we've had for protobuf. For a while now we've been using `observed`, `processed`, and `updated` (where `observed` maps to the `datetime` field)
https://github.com/nearspacelabs/stac-client-python#stac-item-comparison

I sort of like `processed` rather than `created` because creation may suggest the moment the data was collected by the sensor(s). Whereas `processed` suggests something about the data's current state. We had the `updated` property because we liked that from WFS3.

**Comment by cholmes** [comment]
@palmerj - any movement on this? We need it at Planet too, and I'm setting some time aside next week to work on it. Would be happy to start with your proposal, or we can take a crack at one.

**Comment by palmerj** [comment]
Hi @cholmes sorry really busy this week. If you want to take a crack now that would be great. Otherwise I can take a look from next Wednesday

**Comment by matthewhanson** [comment]
We currently have these properties:
- created: when the metadata record was generated
- updated: when the metadata record was last updated
- datetime: when the observation occured
- start_datetime: when the observation started (optional)
- end_datetime: when the observation ended (optional)

Proposed have been a `published` datetime and a `processed` datetime. We discussed this at the STAC mtg and the consensus was that the `created` and `published` date were effectively the same thing.  The difference between when a metadata record was created vs when it was "published" (made available in a catalog) doesn't seem to be an important enough distinction.

Likewise a `created` datetime and a `processed` datetime seem to also be effectively the same, since the metadata record would probably be generated at the time of processing.

**Comment by palmerj** [comment]
Hi @matthewhanson we were mostly interested in the published datetime (when the user sees the data) of the data. That is usually very different that the observation creation time. OK with the other logic

**Comment by m-mohr** [comment]
I'm wondering: If you update the metadata, so you also update a "published" field? Or would someone may need a "first_published" and "last_published" analogue to created and updated?

**Comment by palmerj** [comment]
> I'm wondering: If you update the metadata, so you also update a "published" field? Or would someone may need a "first_published" and "last_published" analogue to created and updated?

Yes interesting thought. like the idea of first and last published. I guess if you are updating the data published and created data, then by implications the metadata date also need to change.

**Comment by p3dr0** [comment]
they are two different dates, as mentioned in #351 

> published : The date (managed date) when the metadata item was published on the catalogue (equivalent to atom:published)
> 
> updated : The date (managed date) when the metadata item was last modified (i.e. updated) in the catalogue (equivalent to atom:updated)

and both must be available in the catalogue

**Comment by cholmes** [comment]
@palmerj - The current definition of 'created' in the [commond metadata section of the spec](https://github.com/radiantearth/stac-spec/blob/v0.9.0/item-spec/common-metadata.md#metadata) is: 'Creation date and time of the metadata file. This is NOT the timestamp the asset was created.' So in my reading, and talking to Matt, it's really what you and I think of as 'published'. 

@p3dr0 - we do have updated, and the above definition of created corresponds to 'published'. Fully agree they both need to be there. In #351 I don't quite understand the 'created' - 'when the metadata item was originally created'. In the satellite world is that the acquisition time? Or is it some notion that you might create a record before publishing it? I want to understand the case where you'd have created, published and acquisition time. I do think we should have 3 'main' ones (acquired/datetime + updated / published/created), in stac common metadata, and perhaps an extension that gives more options (including valid, available, issued).

I was getting comfortable with using 'created' to replace Planet's 'published'. But it sounds like it is confusing many of us. Perhaps we should just rename the STAC 'created' to 'published'? I worry that  'created', 'updated' and 'datetime' will more lead people to think of created as acquired, or something else.

**Comment by cholmes** [comment]
Ok, must made a PR at #763 to propose 'published'. Just want to keep this discussion moving and reach a conclusion. 

As I think about it more I like 'published' because it is less confusing when it's just next to 'datetime' (our main default field). I worry that if we have 'created' and 'datetime' that people will think that 'created' means 'acquired' (which is what our generic 'datetime' means).

**Comment by palmerj** [comment]
Thanks @cholmes. I'm not thinking about the creation date of the asset, rather of the date that the data was published (added to the catalog) for user consumption. In the lifecycle of our data, we have: collect -> store -> publish for use. In many cases, the data is collected/capture many months before it is released to users. 

> I was getting comfortable with using 'created' to replace Planet's 'published'. But it sounds like it is confusing many of us. Perhaps we should just rename the STAC 'created' to 'published'? I worry that 'created', 'updated' and 'datetime' will more lead people to think of created as acquired, or something else.

For me that sounds ok. For our use case, our users don't need the "metadata record" created date, we need the date when the metadata+data is published  for user consumption, along with the created/updated date of the asset. Another thing that might be useful alongside this is some history of the publishing - but that's a more exotic extension.

**Comment by m-mohr** [comment]
Maybe we should do something like a timeline and check what is available, needs to be added and could be useful... Something like:

1. Data captured -> `datetime` (and `start_datetime` / `end_datetime`)
2. Data stored -> N/A
3. Data updated -> N/A
4. Data published -> N/A
5. Metadata created -> currently: `created` / later: N/A
6. Metadata updated -> `updated`
7. Metadata published -> currently: N/A / later: `published`

**Comment by cholmes** [comment]
Yeah, I think the timeline is quite useful. It could be good to articulate the exhaustive list and make an 'extension' that has all the options that one might want. And then Common Metadata would have the two most used - updated and either created or published, with a recommendation to use it for most cases. 

I think your list does highlight the confusion at least for me - what does it mean to have metadata 'created' but not 'published'? I suppose that could be when an image comes from the satellite (data first modified / stored) and it gets a row in a table? But we're not 'creating' a metadata record until we publish it. 

I think at Planet we also use 'updated' for modifications of both the metadata and the data. But I'd prefer to just use one 'updated'.

> last_* equals first_* if it has only be published/modified once. Is last_* more useful than first_*?

First is definitely the useful thing for Planet users. They want to know when there is new information in the catalog that they can download, and want that to be stable.

**Comment by m-mohr** [comment]
Yeah, metadata created / updated / published is a bit difficult, but I just came up with all I could imagine at the time of writing. Now I realize there's actually different phases of publication you may have... something like published internally (could be simply `created`) and publicly (could be simply `published`) or so. It's really up to how organizations work with their data. I guess this is something to survey across providers a bit before coming up with a specification...

**Comment by m-mohr** [comment]
Based on this issue and #351, temporal fields could be named like this:

1. Data capture start -> `start_datetime`
1. Data capture center -> `datetime`
1. Data capture end -> `end_datetime`
1. Data first modified (stored) -> `assets_created`
1. Data last modified -> `assets_updated`
1. Data first published ->`assets_published`
1. Data last published -> N/A, may be captured with assets_updated?!
1. Data valid until -> `assets_valid`
1. Data unpublished -> `assets_available`
1. Metadata first modified (created) -> `created`
1. Metadata last modified -> `updated`
1. Metadata first published -> `published`
1. Metadata last published -> N/A, may be captured with updated?!
1. Metadata valid -> `valid`
1. Metadata unpublished -> `available`

Is that something we could agree on? I don't want to add all this fields now, but we may just open a new issue with this proposal and then link users from the common metadata to the new issue and then add fields to core once we see them being adopted. For now that could be updated, created and/or published being core? @cholmes

**Comment by cholmes** [comment]
Yeah, I had been thinking along similar lines as you 'another idea' - using 'updated' at the asset level to communicate the data changed. 

I think we don't _need_ to take action on this immediately - updated and created seemed to meet most user cases. I suppose an extension that specified published, valid and available could be good at some point, as well as explaining how these can apply at item or asset level.

**Comment by m-mohr** [comment]
Assigned this to myself, I'd like to work on this on Wed.

**Comment by m-mohr** [comment]
See PR #693
