### ISSUE TITLE
Data Use Constraints/Rights Property

### ISSUE THREAD

**Issue by palmerj** [radiantearth/stac-spec#694]
Following on from #133, would the community be open to adding another item/collection property for data use constraints? 

This would support defining restrictions and legal prerequisites for using the dataset. These include any use constraints applied to assure the protection of privacy or intellectual property, and any special restrictions or limitations on using the dataset.

The main use cases for us as defining dataset specific restrictions over the top of the standard licences. e.g not to be used for offical navigation purposes or defining legal boundaries etc.

**Comment by m-mohr** [comment]
I think such constraints should be part of the license(s).

**Comment by palmerj** [comment]
Doesn't always work this way. In many cases people adopt existing licences and then add additional permissions, warranties, disclaimers. This is done a lot for creative commons licences for example.

**Comment by matthewhanson** [comment]
@palmerj could this be handled by using "various" as the license (see https://github.com/radiantearth/stac-spec/blob/dev/collection-spec/collection-spec.md#collection-fields) and providing multiple links with a role type of license? (see https://github.com/radiantearth/stac-spec/blob/dev/collection-spec/collection-spec.md#relation-types). Or do you think there's some information not captured here?

**Comment by matthewhanson** [comment]
Maybe this calls for additional possible 'rel' types for things such as permission, warranties, disclaimers? Are there any existing IANA 'rel' types that make sense?
https://www.iana.org/assignments/link-relations/link-relations.xhtml

**Comment by m-mohr** [comment]
IMHO a "common" license with additional custom restrictions is basically a separate new license derived from another license. CC with additional restrictions is not really CC any longer. So strictly speaking, it would be license set to "proprietary" and a link to the derived license text.

**Comment by palmerj** [comment]
Depends on your view of what is proprietary, but yes it is it's not strictly CC anymore. Still this is case in real world applications, and in these cases there are no links to reference.

**Comment by m-mohr** [comment]
Exactly, proprietary for me is any license that is not on the SPDX license list and any derivate from CC is obviously not on that list.
For static catalogs, you could create a file with your additional restrictions in your catalog and link to it. If you host an API, you can usually create an endpoint returning your license.
I think we discussed having license texts in STAC once at STAC sprint 3, but as far as I remember the mein outcome was that we don't want license texts in the STAC files as it's nothing you'd search on and usually it's better to link to your public licensing information. Also, free-text fields are always a pain as you never know what is in there and people use them for so many different things that they are not so useful in the end.

**Comment by palmerj** [comment]
Ok, I think you have twisted my arm. However, I would say the use of "proprietary" label seems misleading for my applications. We are technically using a slightly modified version of the CC-BY license which the users to freely copy, modify, and distribute the data as long as the data is not used for specific regulated navigation purposes (we have other products for that). IMHO when I think about a proprietary license, it will likely restrict the user from modifying or redistributing the data at all, or it will cost money to use.

**Comment by m-mohr** [comment]
Indeed, proprietary can be somewhat misleading. I hope clients expose the title of the link with rel type `license` instead of proprietary so that one gets around that misunderstanding.
