### ISSUE TITLE
Include CBERS-4 MUX example

### ISSUE THREAD

**Issue by fredliporace** [radiantearth/stac-spec#70]
Hi @cholmes , I'll start working on a CBERS example to be included into the repo, as the first pass of generating a static catalog based on the current CBERS on AWS content.

Opening this to discuss the implementation.

Those who are interested in the dataset may obtain more information in https://github.com/fredliporace/cbers-on-aws

**Comment by cholmes** [comment]
That'd be awesome @fredliporace! Though hold off for a bit, as we're in the midst of shifting some core fields. The dev branch should have an _almost_ up to date json schema (except time stamp needs to be udpated), but it doesn't have the updated samples yet. I'm hoping to do that this week. Also cc @matthewhanson who is working on an Earth Observation profile, which will be relevant to share more fields past just the core.

**Comment by cholmes** [comment]
See https://github.com/radiantearth/stac-spec/milestone/3 for the issues that are settling in soon.

**Comment by matthewhanson** [comment]
@fredliporace I'm working on the EO profile/extension now, I'll have a PR up by tomorrow, then I think it's a good time to have examples of actual data (as @cholmes said, the EO profile will make the examples more relevant).  I'll be able to provide some for landsat-8 and sentinel-2.

**Comment by fredliporace** [comment]
@matthewhanson @cholmes OK, I'm already working on an exercise to generate a CBERS-4 MUX Item using the current spec, it seems to me that an adaptation to the new spec will be then easier.

The mapping between CBERS-4 MUX metadata and STAC seems to be straightforward. The only question that occurs to me at this point is how to deal with the multiple CBERS-4 payloads, 4 cameras with distinct features. In that particular sense CBERS is different from LS8(*)/S2.

Anyway, I'll review that considering the new spec/profiles as soon as they are available.

(*) LS8 OLI/TIRS are distinct cameras but generate data 'in tandem' and with similar geometric characteristics/coverage, which is not the case for CBERS-4.

**Comment by matthewhanson** [comment]
@fredliporace That sounds like the right approach to me. The different CBERS-4 instruments would be different collections, or products, see #63

**Comment by fredliporace** [comment]
Implementation in #77

**Comment by cholmes** [comment]
I think we didn't quite get this finished for 0.4.0. I'm happy to merge in before a 0.5.0 'release' since it's just an example in the core stac repo.

**Comment by fredliporace** [comment]
Changing issue scope, see #98

**Comment by fredliporace** [comment]
Duplicate of #98
