### ISSUE TITLE
Add item properties composition document

### ISSUE THREAD

**Issue by joshfix** [radiantearth/stac-spec#715]
Item properties can be composed from required core properties found in the item spec, optional common properties found in the common metadata document, and any number of extensions from the extensions directory at the root level.  It seems like a bit of a hunt -- you have to know where to go to find all of the info/options if you're trying to piece together a collection.

I proposed restructuring the spec so that all item property definitions/specifications (including extensions) were grouped together under the item spec, but there were concerns because there are extensions that belong to both the item spec and the collection spec.  This would result in having multiple extension directories  and may also be confusing.

Current proposal is to create a new document that lives under the item spec that details how to compose properties and provides links to core, common, and extensions that can be used.

**Comment by m-mohr** [comment]
We started improving it a bit here: https://github.com/radiantearth/stac-spec/pull/712#discussion_r364639913

**Comment by m-mohr** [comment]
What else needs to be done here, @joshfix ?

**Comment by joshfix** [comment]
I think it's probably good.  At least the item spec now links to common metadata, extensions, etc.
