### ISSUE TITLE
API spec documentation, examples, and 0.9.0 changelog confusion re:pagination

### ISSUE THREAD

**Issue by joshfix** [radiantearth/stac-spec#716]
I'm working my way through the changelog to update Staccato and found something quite confusing before I really dug in and figured out what was going on.  Under `Changed`, there is an entry:
```
Removed "next" from the search metadata and query parameter, added POST body and headers to the links for paging support
```
There is a nearly identical entry under removed.  There is nothing under added.  The api spec markdown doesn’t address the new way in which pagination is supposed work.  I happened to find the explanation in “examples.md”.  In addition, there are other entries in that examples document that seem to be the official definition/description of aspects of the API.  I'm thinking we should move those instructions/definitions/descriptions to api-spec.md and the examples should just have titles, potentially brief descriptions, and the actual example.

Then maybe we can remove the “Changed” entry and add an entry to “Added” that includes a link the the spec that explains the new way pagination is supposed to work? 

Side note, I originally was looking for these changes in the item collection spec, as these links belong to an item collection, but the item collection spec makes no mention of it.  Took me a minute to realize it was under the api-spec.  However, also missing in the api spec markdown is a table describing the custom links object -- I had to sift through the yaml to find the exact definitions of the fields.

**Comment by joshfix** [comment]
Looking into this a bit deeper, I don't see a way to pass a token to GET the next set of results any more since the `next` search parameter has been removed:

https://github.com/radiantearth/stac-spec/blob/master/api-spec/STAC.yaml#L150-L154

The [examples document](https://github.com/radiantearth/stac-spec/blob/master/api-spec/examples.md#paging) shows the next link having the parameter `?page=2`, but `page` isn't a valid search parameter.  

It also seems extremely vague exactly how the new header system is supposed to work for POST.  It's probably in the yaml, but we don't have a good description of possible header names, header values, and no examples using headers in a subsequent request (actually no examples at all of subsequent requests).

Finally, there appear to be other lingering instances of using the next parameter in various places:  https://github.com/radiantearth/stac-spec/blob/master/api-spec/STAC.yaml#L1543

**Comment by m-mohr** [comment]
> Looking into this a bit deeper, I don't see a way to pass a token to GET the next set of results any more since the `next` search parameter has been removed:
> 
> https://github.com/radiantearth/stac-spec/blob/master/api-spec/STAC.yaml#L150-L154
> 
> The [examples document](https://github.com/radiantearth/stac-spec/blob/master/api-spec/examples.md#paging) shows the next link having the parameter `?page=2`, but `page` isn't a valid search parameter.
> 
> It also seems extremely vague exactly how the new header system is supposed to work for POST. It's probably in the yaml, but we don't have a good description of possible header names, header values, and no examples using headers in a subsequent request (actually no examples at all of subsequent requests).

The thing is, you can use whatever you like. Use any parameter or header, just provide it as link with rel = next. 

In general, I agree we should add a section describing this in detail to the API spec.

**Comment by joshfix** [comment]
> The thing is, you can use whatever you like. Use any parameter or header, just provide it as link with rel = next.

So use whatever header names you like?  I'm not clear on the "use any parameter" part.  GET parameters have to be explicitly defined, and I don't see any parameter defined that will let me pass in my next token in a subsequent GET request.

**Comment by m-mohr** [comment]
@joshfix Only your implementation knows what you need for pagination, whether it's a header, body or parameter. Let's say you want to use pageToken. You specify that in the next link, for example: `{ href: "http://exam.ple/api?pageToken=asdf", rel: "next" }`. Then your implementation can read the pageToken. Clients just follow the next link. If a header or method is specified, they also need to take care of that. It's basically Hypermedia, where you don't specify any API, but just follow links.

**Comment by joshfix** [comment]
Ah, makes much better sense.  Definitely think we have some documentation improvements that need to be made here.  I can take a stab at this next week.
