### ISSUE TITLE
Drop repo

### ISSUE THREAD

**Issue by jskulavi** [radiantearth/stac-spec#72]
This repo is redundant.  It should be dropped in favor of www.openstreetmap.org and other APIs such as mapbox.com, https://market.trimbledata.com 💯

**Comment by cholmes** [comment]
I'm not sure how we could replace this repo with one of those API's. 

OpenStreetMap is an API for feature data, not imagery assets, and afaik there's no way to use it to refer to an image online and then search for it. 

Mapbox.com has a number of API's, but none do search of imagery. The tilesets and datasets api's are perhaps the closest match, but they are more about returning particular datasets in a single account, they don't offer cross account search - like searching for all of the imagery that people have uploaded to mapbox. The rest of their API's are more about styling, directions, geocoding, etc. I do really like the MapBox API's, and they sent some people to the last in person meeting, and are interested in using the spec to consume satellite imagery.

I hadn't seen the trimbledata market API, it definitely looks the most similar. I'm not sure how we would just adopt it. The point of this repository is for various vendors to come together to figure out what's in common between their approaches. I'll reach out to trimble as it would be great for them to collaborate on a more standard API with us. 

Vendors like Planet, DigitalGlobe, Boundless, Azavea, Google, Amazon, etc. are all coming together to collaborate on achieving interoperability on imagery search between their different ways of doing things. If there is another effort underway that is aiming at the same goals it would definitely be great to combine efforts.
