### ISSUE TITLE
Add new metadata key on the specification

### ISSUE THREAD

**Issue by rmmariano** [radiantearth/stac-spec#721]
Hello everyone,

I was looking for a way of inserting metadata on the 0.7.0 version of STAC, such as limit and page in order to do pagination, however I did not find anything to help me on the specification. If this resource exists on the documentation, please tell me.

How I did not find this resource on the specification, I would like to suggest it on the STAC standard officially.

For example, if you all access [/collections](https://sat-api.developmentseed.org/collections) route on the Development Seed STAC, you will get the available collections with a "meta" key, where there are metadata, such as page, limit, found and returned, for example:

```
{
  "meta": {
    "page": 1,
    "limit": 10,
    "found": 2,
    "returned": 2
  },
  "collections": [
    {
      "id": "landsat-8-l1",
      "title": "Landsat 8 L1",
      "description": "Landat 8 imagery radiometrically...",
      "version": "0.1.0",
      "stac_version": "0.6.0",
      ...
    },
    ...
  ]
}
```

I'm developing one STAC service and I use this metadata tag. I believe this would be a great improvement you all could add to STAC specification. This "meta" key could be an optional key and not mandatory, for example.

Thank you in advance.

Best Regards,
Rodrigo

**Comment by m-mohr** [comment]
For STAC 0.7 it seems we haven't specified it (i.e. it was not supported at that time). So in 0.7 your are probably stuck with that, except you adopt a proprietary extensions like Development Seed did. For STAC 0.9 it is available here: https://github.com/radiantearth/stac-spec/tree/v0.9.0-rc1/api-spec/extensions/context and I guess it's best to switch to that version?!

**Comment by rmmariano** [comment]
Which proprietary extension have Development Seed adopted?
I'm going to talk with my team related to switch to STAC 0.9.
Thank you for your useful hints.

**Comment by m-mohr** [comment]
Proprietary in the sense that they added their own custom fields which are not standardized publicly. 

We leave the technical details of pagination open to implementors so in many cases there are no page numbers, but other things like tokens or offset values or so.
