### ISSUE TITLE
Change sortby parameter in GET requests

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#727]
Over at Gitter we discussed that the `|` separator between field name and sort direction (asc, desc) doesn't work well as it's not encoded in some Browsers. So @matthewhanson @joshfix and me thought about reusing the structure (+/- and field name) from the fields extension. 

`-` is descending
`+` is ascending
No prefix defaults to ascending as it's the default in most DBMS (or we require +/-)

**Comment by joshfix** [comment]
This is a silly little nuance, but I do remember somebody having an issue with this method defaulting to ascending.  I think an (easier?  more convenient?) way of thinking about this is that we aren't actually defaulting the order to ascending, but instead, the user is implying the plus sign by not explicitly specifying it, the same way that `$5` it's implied/assumed to be `+$5 and not `-$5`.  

Again, super nuanced, but by not providing a sign, we are simply inferring that the sign is "+" and not specifically defaulting the sort order to ascending, even though that is the net result.

**Comment by m-mohr** [comment]
Fine for me. :-)
