### ISSUE TITLE
Can items belong to multiple collections?

### ISSUE THREAD

**Issue by beck3905** [radiantearth/stac-spec#741]
Currently the item spec has the `collection` field which is a string.  Could this be a list instead?  It seems possible that an item could and should belong to multiple collections.

**Comment by m-mohr** [comment]
No, that's not possible at the moment. Indeed, there's theoretically the possibility to add two collection links, but the collection field doesn't allow a list of values. Just making it a list is not just that as it would/could lead to conflicts with the commons extension. What do you think @matthewhanson ?

**Comment by cholmes** [comment]
I'm inclined to say that there are others ways to model this with the current structure, and that it keeps clients a lot simpler if they don't have to check multiple collection links and try to interpret what that means. Like it seems to imply multiple inheritance potentially, which may be useful, but also is a lot more complicated.

I'd say if the desire is to represent the same 'thing' in multiple collections then you could just have two items that have a relation to each other, that says 'this item in another collection is the same as me'.  Or if the important thing is for an item to link to two collection json files then you can have one be the collection field, and then add a 'link' to the other collection that should be used. 

I could be convinced if there's really clear use cases that really require this, but if it's just a desire to have a single item included in multiple containers then I'd say just use links and propose an extension.

**Comment by matthewhanson** [comment]
The use of the 'Commons extension really makes this a major headache, as it means you would have to consider inheritance from multiple items.

However, we are discussing removing the Commons extension, which makes this much easier. But I agree with @cholmes I'm not sure if there's a real need for this.

**Comment by m-mohr** [comment]
If Commons goes away, I guess the only issue to make it more flexible is to make the `collection` property in the Item an array (or remove it altogether and use the link references somehow).

**Comment by matthewhanson** [comment]
A common query on Items is to find all Items belonging to a certain collection. This is more difficult if the server must parse the entire links array to find collections....and it's also not guaranteed that the collection link includes the collection ID - you'd have to follow the link to get the collection ID.

**Comment by m-mohr** [comment]
So Commons has been removed, but now there's the Item Asset extension. How do we proceed? Should we allow multiple collections in the collections field?

**Comment by pomadchin** [comment]
We also had a need in having items that belong to multiple collections. It ended up being a [STAC Layer / Group Extension](https://github.com/azavea/stac4s/tree/master/docs/stac-spec/extensions/layer) which adds a separate concept of 'layers': groups of items the belong to different collections. Each layer can also have a summary about all items that belong to it. 

How much it makes sense to push this idea towards being an extension rather than being a change in the collections relationship? 

To make it work, STAC API would only have to implement a query extension. However, to request layer 'summaries', it would be neccesary to implement [STAC API Layer Extension](https://github.com/azavea/stac4s/tree/master/docs/stac-api-spec/extensions/layer).

**Comment by pomadchin** [comment]
During the STAC sprint we talked a bit about the Layer Extension and about items belonging to multiple collections; 
The conclusion was that probably we don't need it (both: layer extension and items with multiple collections), but what can be an option is the [Aggregation extension](https://github.com/radiantearth/stac-api-spec/pull/36), where the result of the aggregation can be represented as a collection.

/cc @matthewhanson @m-mohr

**Comment by m-mohr** [comment]
Conclusion: We discussed that in the Python room today and came to the conclusion that this is likely not needed. You can have multiple collections referring to a single item, but you always have a just a single collection you inherit from. If you want to do aggregations, we need to come up with API aggregation functionality and will work on that tomorrow. If you create new/dynamic collections on top of existing items, then you can't change the item anyway. So closing this.
