### ISSUE TITLE
Split off API into new repo

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#747]
Split off api-spec folder into a new repo: https://github.com/radiantearth/stac-api-spec
which can then be versioned separately.

**Comment by matthewhanson** [comment]
PR has been merged to remove api-spec.

Leaving issue open as still need to update all links/references in repo

**Comment by m-mohr** [comment]
- [x] Update all links
- [ ] Move API recommendations from STAC best practices to API best practices (e.g, parts of "Versioning for Catalogs")
- [ ] ...

**Comment by matthewhanson** [comment]
The split has been done, opening up new issue for moving API recommendations out of here to stac-api-spec
