### ISSUE TITLE
Create OpenAPI document for core stac spec

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#750]
It'd be useful to have an OpenAPI document that shows the core 'browse' catalog functionality in this repository, to give another view of how it can be implemented. Should ideally enable both 'collection only' examples, as well as 'item' ones, that are just linked to with 'child' links, not implementing /items and /search endpoints.

**Comment by m-mohr** [comment]
A browseable catalog is mostly Hypermedia links and thus OpenAPI is not really suitable for this. OpenAPI needs fixed paths, but browseable catalogs don't have that. For Hypermedia stuff an option could be JSON Hyper-Schema or so...

**Comment by cholmes** [comment]
Ok, will just close this then.
