### ISSUE TITLE
"grids" extension

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#756]
There is a PR open for a "grids" extension: #688 , but there was no corresponding issue.

The grids extension is meant to provide information on the size in pixels and geolocation for each asset:
For each asset:
- the size of the 2 or 3-dimensional array stored within the file, as reported by rasterio or GDAL
- the "geo-transform" array - a 6 element array indicating the top left native pixel coordinate and coefficients for x and y in each of the 2 dimensions.

While this metadata is not used for searching on, it can be useful as it provides information that is otherwise only available by opening and reading the header of each asset. This can be a significant overhead cost when reading lots of files.

**Comment by matthewhanson** [comment]
This extension is only going to be useful if used in conjunction with the `proj` extension, as that provides data on the native projection that the geo-transform units are provided in.

I don't find the name `grids` very helpful in determining the purpose of this extension.  I would propose either renaming it to something more descriptive such as `geo`, or better yet to combine it with the `proj` extension, since it must be used with that extension and thematically fits in with it.

**Comment by matthewhanson** [comment]
cc @abhijeetkumarga @alexgleith @cholmes

**Comment by alexgleith** [comment]
Hey @matthewhanson, I have no problem with merging it in with the `proj` extension.

I don't think `geo` is any better than `grids`, though.

**Comment by cholmes** [comment]
I agree that geo is no better than grids. And my first reaction is that
merging with proj also makes sense, but want to think on it a bit more.

**Comment by matthewhanson** [comment]
Just a note that most of the discussion here is within the PR #688 

@Kirill888 @alexgleith 

We discussed and will be proposing #760 , which will allow STAC assets to override properties that are described at the Item level.   Also agree that the grids extension is better merging with proj.

So now, the new fields from the grids extension become simpler, just two new fields to be added to an Item:

```
proj:shape
proj:transform
```

Then, by using the asset specific metadata option from #760 you can override `proj:shape` and `proj:transform` at the asset level.  In the case of Sentinel where there are 3 different transforms used due to different resolutions, we would define the most common one in Item properties (the 6 20m bands), then would override those for the 4 10m bands and the 3 60m bands (only 2 for L2 data since B10 is not included in L2).  

This does mean some redundant information, but it is a small number of bytes and we didn't feel it was worth the added complexity.

thoughts?

**Comment by Kirill888** [comment]
@matthewhanson sounds good to me.

**Comment by matthewhanson** [comment]
This has been changed, and merged, to add fields to the proj extension rather than a new `grids` extension.
