### ISSUE TITLE
provide merged JSON/YAML schema

### ISSUE THREAD

**Issue by tomkralidis** [radiantearth/stac-spec#759]
Currently, JSON schemas are available for each specification (catalog, collection, item).

Would it be valuable to have an "all-in-one" JSON (and/or YAML?) schema to be able to point to from an application?

**Comment by m-mohr** [comment]
I could provide a small node script based on https://github.com/APIDevTools/json-schema-ref-parser that combines them with a cli command. Would also be useful for creating the schemas, I guess.

**Comment by m-mohr** [comment]
In the json node validator, I'm using a very simple json schema to combine them: https://github.com/m-mohr/stac-node-validator/blob/master/core.json 
Then the tool above resolves the refs.
I'm not exactly sure how valuable it is to provide this from our side though. It wouldn't contain extensions.

**Comment by m-mohr** [comment]
Demand doesn't seem to be very high, at least nobody else sounded in. Thus, I'm closing for now. Please sound in here if you still find this useful and we may reconsider it.
