### ISSUE TITLE
Asset specific metadata

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#760]
A few of us had a quick discussion today relating to asset specific metadata: the ability to specify fields that are Item properties on a per asset basis.

It's discussed here in the context of the proposed "grids" extension:
https://github.com/radiantearth/stac-spec/pull/688#issuecomment-609910006
but could apply to other fields as well.

We concluded this was a good feature to have, with the following notes:
- properties defined at the asset level should always be first defined at the Item level. The asset field, if present, overrides the Item field for that asset
- make clear that fields defined per asset will not be searchable....users will search on the Item properties so that should be some sort of "nominal" value
- recommendation should include a short list of fields this may make sense for, e.g., grids extension, gsd
- otherwise, providers should think carefully on whether or not they should be doing this, or if what they really need is separate Items for this data

did I miss anything @m-mohr @cholmes @anayeaye ?

**Comment by m-mohr** [comment]
This seems mostly complete, although it doesn't clearly state how the related between asset-level metadata and common metadata + extension fields is. There's a potential conflict between the "title" fields, should be mentioned at least. Also, what's the take on things like eo:bands that differs between properties and asset level? I think that needs some thoughts and explanation. And then we probably need to clarify that the asset extension can also inherit the "added" fields.

**Comment by m-mohr** [comment]
We just had a use case where we have to put the "datetime" field into the assets (i.e. export of a single band time series), which IMHO is reasonable to do although STAC Items are more modeled for single datetimes. And that makes me think of #613 again. ;-)

**Comment by matthewhanson** [comment]
closed with #788
