### ISSUE TITLE
PR Checklist: Add checkbox for dev/master

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#768]
We often get PRs for master instead of dev, which is in most cases wrong. I guess it could be a good idea to add another entry to the PR checklist that reminds the user to make PRs against dev. Something like...

> - [ ] I based and made my changes towards the `dev` branch (master is usually only applicable for new versions).

(Please propose something better.)

**Comment by cholmes** [comment]
Ah, great idea. I can take this on and refine the text.
