### ISSUE TITLE
Thumbnails for Collections?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#778]
Anyone has a good idea how we could incorporate thumbnails for collections? We have them for items, but we have some cases where we want to directly give some examples for collections. 

Two way I could see here:
1. Add a link to a thumbnail with rel type [`preview`](https://www.iana.org/assignments/link-relations/link-relations.xhtml) and image type `image/jpeg` (or gif/png). Currently clients don't recognize this so I'd propose to add it to the Collection [Relation Types](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#relation-types).
    **Pro**: This is possible without a real spec change.
    **Con**: It's different from how items do previews.
2. Use the asset extension and add a `href`. This is also how we try to incorporate collection-level assets in #713. Based on this, define thumbnails as in the item spec.
    **Pro**: Is aligned with Item spec.
    **Con**: Needs a spec change (asset extension) and basically introduces collection-level assets.

Other options? Opinions?

**Comment by matthewhanson** [comment]
I think if it were only for thumbnails then having it as a link would be good, but if we have a use for other collection level assets, such as using the Zarr format, then thumbnails should be specified as assets to be like collections.
