### ISSUE TITLE
Better define what should go in 'provider' field

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#78]
The 'provider' field is so loose as to not be so useful. We should improve that incrementally, and also figure out the long term plan.

In the short term that means picking a definition, either the organization providing or the sensor/instrument, and then having all the examples be consistent (right now we have 'landsat' and 'planet' in the examples, which aren't really the same level). We should then update the spec narrative to be clearer.

In the long term should perhaps figure out some way to enumerate the options, so we don't have 'landsat', 'landsat8', 'usgs', 'nasa', etc all representing the same data.

This came up in #75

**Comment by matthewhanson** [comment]
I think the most useful field for provider would be a URL, preferably to a page about the dataset, but at least would contact contact information.

**Comment by matthewhanson** [comment]
Oh, and I think "provider" should be who is actually providing this specific data. Derived data would be provided by whoever created it (and ideally the record would include provenance about the original source, which would have it's own provider field)

**Comment by m-mohr** [comment]
What is a provider actually?
* The service hosting the data, e.g. Amazon S3? (saw this in a catalog example)
* The organization that produces the data, e.g. ESA? (saw this in an item example)

If you want to have both, I'd suggest using different names or it will be quite confusing.

**Comment by m-mohr** [comment]
In addition, I'd like to mention that there are inconsistencies between the provider field in the catalog spec and the provider field in the item spec.

Items define it to be a "Provider name" as string.

Catalogs don't have a clear specification, but the example shows an object with three properties:
* scheme  (No further spec, what is expected to be inside?)
* region (No further spec, what is expected to be inside?)
* requesterPays (No further spec. Should probably be a boolean value, but the example shows incorrectly a string with value true: `"requesterPays": "true"`)

**Comment by cholmes** [comment]
This should probably wait for dataset spec to flesh out. But does seem like it'd be useful to have a single value to search on at the Item level. But we need to decide what that value is and put it down clearly in the spec.

**Comment by m-mohr** [comment]
So in the dataset we will probably have multiple providers (name + url) and a host. 

For Items we may just go with the last provider in the chain and put in provider_name (and provider_url? or is this going to be in the links similar to the license?)

**Comment by m-mohr** [comment]
Fixed by #262. Provider is in the dataset now and was removed from items.
