### ISSUE TITLE
Move API recommendations to stac-api-spec

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#782]
Move API recommendations from STAC best practices to best practices in stac-api-spec (e.g, parts of "Versioning for Catalogs")

**Comment by cholmes** [comment]
Maybe I'm missing it, but I don't see much at all that should be moved. The versioning extension does refer to STAC API, but it's just saying it's sharing the mechanisms. There is also reference to 'dynamic catalogs', but to me STAC API is 'search', and one can implement a catalog as an API. So we talk about that in the best practices, but I think that's appropriate. 

I'm going to close the issue, but feel free to re-open if I miss something. I did throw in a few more links in #772
