### ISSUE TITLE
Cleanup Item asset specific metadata, add to best practices

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#789]
The recent PR #788 that adds in the ability to define Item properties for individual assets includes potential use cases and language that is better off under Best Practices.

**Comment by m-mohr** [comment]
Should also tackle https://github.com/radiantearth/stac-spec/pull/788#discussion_r417642024

**Comment by cholmes** [comment]
Ok, just made PR #790 - but I wasn't quite clear on what the action is from the comment on 788 that you mentioned @m-mohr ? If you explain it a bit more in the ticket I can add it in, I just felt like I didn't have the full context and wasn't sure if the stuff to link to has landed?

**Comment by m-mohr** [comment]
Nevermind, I think it will be part of a separate PR from @matthewhanson that will establish behavior in the asset defintion extension to export "larger" properties like eo:bands into the asset definition of a collection.
