### ISSUE TITLE
Update EO examples to be consistent with coming EO profile

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#79]
We have a few different examples, from landsat, planet, cbers, etc that all share common fields, but right now the definitions are all over the place. 

I don't think we need a full EO profile for the 0.4.0 release, but it'd be good to at least have the samples be consistent with one another and point to where we're going. If we can get to a full EO profile in the release that'd be great too.

**Comment by matthewhanson** [comment]
I'm working on the EO profile today, and will at least hit the updated Landsat example today as well to go along with it.

**Comment by matthewhanson** [comment]
@cholmes PR added for an initial EO extension
https://github.com/radiantearth/stac-spec/pull/80

**Comment by cholmes** [comment]
I think this is mostly there, though would be good to flesh out the 'collection' stuff on some a bit more. To really do this we probably need #94 (or at least I do).
