### ISSUE TITLE
Move itemcollection spec to stac-api-spec?

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#791]
In the [itemcollection spec](https://github.com/radiantearth/stac-spec/blob/v0.9.0/item-spec/itemcollection-spec.md) we say:

>The same ItemCollection definition is currently only used by the /search endpoint. The search endpoint enables dynamic queries, for example selecting all Items in Hawaii on June 3, 2015, but the results they return are an ItemCollection of Items.

I think it makes sense to remove it from stac-spec core and just put it in stac-api-spec repo? I'm not that has more implications though.

**Comment by m-mohr** [comment]
It's also used by the Single File STAC extension though...

**Comment by cholmes** [comment]
Hmmm... That is a reason to keep I suppose.

I could see just defining it in sat-api-spec and then referencing it from the extension. If that extension gets wide adoption then migrates to core I could see bringing it back in. 

So slight preference to do that (or even just define it in the collection). It just reads weird right now to have something in the core item spec folder that isn't used by any of the other core specs. And I just prefer to keep the core as tight as possible. But I don't feel that strongly, just wanted to bring it up.

**Comment by m-mohr** [comment]
See #484 for some historical context. I agree that it makes more sense in API spec, but other people obviously disagreed.

**Comment by cholmes** [comment]
Duplicate of #810, closing this one.
