### ISSUE TITLE
data coverage percentage

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#803]
Sentinel has a percent data coverage, representing the total amount of the scene that has data, this can be a very useful property for any data that has been cut into tiles as it can be used to filter out scenes that are just small pieces of data.  (for instance if you only want scenes that cover the entire tile).

I'd propose a new field, `data_coverage` or similar.  It is applicable to EO data, but also SAR as well as potentially any raster data.  I think it might be best suited under the Item common properties.

**Comment by m-mohr** [comment]
Sounds useful, may even work for data cubes in a slightly different way. Naming should be aligned with cloud_cover, if possible in a meaningful way.

**Comment by m-mohr** [comment]
Is that something that would somehow also suit into the file extension?

**Comment by PowerChell** [comment]
Discussion can continue here: https://github.com/stac-extensions/raster/issues/39
