### ISSUE TITLE
Refine the collection concept

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#81]
See discussion in #63 

Should contain the information about a set of Items that share metadata and assets. 

Should include the collection level metadata so the Items don't have to repeat so much. 

Should include the json-schema to validate (or probably a link to it?)

May be the spot we put DCAT type metadata.

**Comment by cholmes** [comment]
Not sure yet how this fits in vis a vis the catalog.json. A catalog is the entry point to crawl a set of data. And I think a catalog could be heterogenous - could have multiple collections in it.

**Comment by cholmes** [comment]
Thanks for all the feedback @m-mohr! 

Lots of good little detail here, but first the big picture:

I think we (STAC + Open-EO) should jointly define an 'EO Collection Metadata' json spec. Ideally with collaboration with opensearch EO profile as well. This should describe the specific properties to describe a collection of EO data. While also recommending other standards for more generic metadata, like [DCAT](https://www.w3.org/TR/vocab-dcat/). It's important for STAC so that we don't have to repeat the same information over and over again in each Item (and indeed can use Matt's 'merge' concept to produce fuller metadata records). And it's clearly important for Open-EO. It should also be useful for those who might want to do like a Catalog of all STAC collections - they could crawl the collection info. 

I think we should also aim to align with WFS 3.0. Talking to the editors it sounds like the 'collections' metadata can be pretty flexible. See like http://geo.kralidis.ca/pygeoapi/collections/lakes (specified in [feature collections metadata](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_feature_collections_metadata). It has the temporal and spatial extents there, and could expand for the other eo features.

**Comment by cholmes** [comment]
As for some more detailed thoughts:

1) Yes, I definitely want to somehow merge 'collection' and 'catalog' - that's bugged me since we put it out, but I still don't have a clear picture exactly how to do it. As I also want to bring 'static stac' and 'stac api' closer together, and the latter doesn't have a 'catalog' concept. I think it should likely just be one main 'collection metadata' thing that contains most of the metadata. And 'catalogs' turn to mostly sets of 'links', and one could have a 'root catalog' that combines the two functions. I do think we need to think about static catalogs that are heteroegenous though - containing data from different collections.

2) As above I think we should just define the 'collection' metadata, though have things like 'license' share meaning and options/definitions between the two.

3) Makes sense to kill them, I think those were a bit lost in the transition from Matt to me. I do like the idea of using 'title' a lot. I've been thinking about making HTML pages from the stac JSON, and having link titles would be useful in some cases.

4) As you've noticed that catalog definition is pretty poorly thought out. Needs a lot stronger definition, as I think combination with other stuff. I'll try to finish my thinking on catalog vs collection vs wfs feature collection metadata and write up a proposal.

5) I'd be open to having it in properties, though I think it is just the 'join' case - in general I think bands should be at the collection / catalog level.

6) Good point - should work to explain that more. I think there's decent logic behind where each go, but it's not super explained (a lot is a desire to keep 'properties' as flat so it works well in existing geo software). Where is geometry in properties? That sounds like a bug to me.

7) We do have the notion that specific 'profiles' could define more times. But I think in this case we just want a temporal extent for the collection / catalog level. WFS has defined a temporal extent for feature collection metadata, and I think we should just use that: https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_feature_collections_metadata (particularly in example 4: "extent": {
        "spatial": [ 7.01, 50.63, 7.22, 50.78 ],
        "temporal": [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ]
      }

8. I don't think we've really speced this, but the idea was to use a link with something like 'rel=source'. Though we were thinking about it more at the item level, less at the collection level.

**Comment by m-mohr** [comment]
Thanks a lot for your comments and explanations! I'll need some more time to go through them.

I just wanted to write down the information related to the potential bug identified in (6) regarding the geometry: The collection spec itself mentions the geometry at the properties level: https://github.com/radiantearth/stac-spec/blob/master/extensions/stac-collection-spec.md#using-a-collection

**Comment by m-mohr** [comment]
Sorry for the late reply and thanks again for your answers and the willingness to work on a EO Collection Metadata JSON spec, which we both can benefit from. We've talked about in on Gitter already a little bit, but I'm still not completely sure how this should be incorporated with STAC. You said:

> Oh, the idea is a full separate 'spec', not just a separate profile. It'd be like a 'microspec', hopefully just a couple pages with a json schema, that is just about EO collection level fields. Then the stac eo profile and open-eo would both 'use' it.
> So a unified approach for sure, just that we'd both reference a single document, instead of trying to shoehorn one in to the other. We can 'incubate' it in STAC EO profile - I'm just saying the goal should be a small 'eo collection metadata' spec/schema.

I think it makes sense to re-use the EO profile, but I'm not sure how a separate microspec could be bundled with STAC. Wouldn't it duplicate the catalog/collection in STAC or would that be replaced somehow? I could also imagine to have it still in STAC. Overall I am already pretty happy with it, but it surely needs some minor adjustments to be able to use it just for collection discovery only (i.e. make assets optional). 

* Incorporating OpenSearch EO is a good idea and I fully support it. We probably need to wait for the new OpenSearch version including JSON encoding, see #16.
* To some extent, DCAT looks similar to STAC and it could be its own profile for STAC actually. 
* WFS3 looks promising, but I couldn't find much information on extensibility yet and I don't like how they "named" their API endpoints. `/search/stac` already is a bit strange. That's not very important though. I still need dig depper regarding WFS3 and get more involved there. I'm curious about time plans, too.


1. and 2. I agree with you.
3. Should we open a separate issue for this?
4. Great. Can't wait to read it. 
5. It would be in line with GeoJSON, I think. Having it consistently in properties sounds reasonable to me, but it's probably also a matter of taste. 
6. Regarding the potential bug: The collection spec itself mentions the geometry at the properties level: https://github.com/radiantearth/stac-spec/blob/master/extensions/stac-collection-spec.md#using-a-collection
7. Sounds reasonable. There was also this discussion with Matt regarding ranges, which might influence this.
8. There is a rel type called `convertedFrom`, which is probably what we are looking for. Having it on the item level also makes it applicable for collections. Usually a collection of items is processed with the same processes and therefore it is shared by many items and can be at the collection level, too. Correct me if I'm wrong.

I'm probably not able to immensely bring this forward in the next two months, but maybe we can at least discuss the initial direction and get into details in July/August or so. I'll have a lot of time then to bring this forward.

**Comment by cholmes** [comment]
Progress on this with https://github.com/radiantearth/stac-spec/pull/116 but I think we still need a bit more work, so moving to 0.6.0 and keeping open.

**Comment by m-mohr** [comment]
I think this is solved or discussed in other issues (#194, #174, ...), I'd close it.
