### ISSUE TITLE
Explain summaries more

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#820]
Whenever I read the summaries section I'm always a bit unsure how to actually use them. It doesn't feel like quite enough information in the spec. 

I think having them more prominent in the examples would help, and a good best practices section as well.

**Comment by m-mohr** [comment]
What exactly is missing for you? What should be covered in a best practice? There's already a bit on what to include and what not.

**Comment by m-mohr** [comment]
I need a response so that I can work on it for beta.2. Otherwise I have to move it to the next release. @cholmes

**Comment by m-mohr** [comment]
@cholmes This has been addressed with #985 or is there anything missing?

**Comment by cholmes** [comment]
Nope, nothing missing - was just waiting for that one to close. Thanks!
