### ISSUE TITLE
Refresh Examples 

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#821]
Our examples have been added somewhat haphazardly, and many are just updated with a new construct without really thinking about what the show as a whole. 

We should look over all the examples, and figure out the right mix of ones that tell a coherent story. It'd be nice if some of them were more 'real', and/or if we used some consistent items / collections / catalogs. We should also be sure most all the constructs we talk about our represented in the examples in some way. 

We could also consider a full self-contained collection that is a real stac catalog but can live in github, that shows how all the pieces come together.

**Comment by m-mohr** [comment]
I fully support this. When working on the EO example fixes for #829, some were really confusing.

**Comment by scottyhq** [comment]
Would be nice to verify href URLs are valid. As a particular case https://github.com/radiantearth/stac-spec/blob/master/item-spec/examples/landsat8-sample.json could be updated to point to a valid level-1 collection path such as https://landsat-pds.s3.amazonaws.com/c1/L8/139/045/LC08_L1TP_139045_20170304_20170316_01_T1/index.html from https://docs.opendata.aws/landsat-pds/readme.html. I could create PR for that specific example, just filling it out by hand?
