### ISSUE TITLE
Use h4 instead of bold in table explanations?

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#822]
One of my minor annoyances when using the spec is that I'll want to refer to a particular section but it's done in bold and there's no hyperlink. 

The latest was summaries - I have to say: 'go to https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#collection-fields and scroll down'.

We could consider just using the smallest markdown heading, so we get an automatic hyperlink.

**Comment by m-mohr** [comment]
Linking to the description below is also not ideal:
1. It only covers things with a description below the table
2. It doesn't cover the "formal" data type description

I feel like linking to the collection fields fine, but on my screen I see it directly with the link, not sure about smaller screens.

**Comment by cholmes** [comment]
This is changed to must have as it's now in an inconsistent state, as h4's were added in #942 so it could link better.
