### ISSUE TITLE
Issues with eo:bands

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#823]
With 1.0.0-beta.1 we removed commons and allowed eo:bands to be in
1. Item properties
2. Assets
3. Collection Item Assets Extension
4. (Summaries)

There are a couple of problems we need to address:
1. I think we could improve the documentation about this in the EO extension. Although the Item Asset object describes the behavior for eo:bands in assets in general, it is not mentioned at all in the EO extension README.
2. ~To make it even worse, the EO extension has a completely outdated chapter on eo:bands references: https://github.com/radiantearth/stac-spec/tree/master/extensions/eo#associating-assets-with-bands This needs to be removed completely.~ Fixed with #827
3. The [EO example](https://github.com/radiantearth/stac-spec/blob/dev/extensions/eo/examples/example-landsat8.json) and others are also still refering to the old index-based bands.
4. The [Item Fields](https://github.com/radiantearth/stac-spec/tree/dev/extensions/eo#item-fields) (and the schema) list eo:bands as required. This is not correct as it is not required there any longer, it could be in assets. We need to think about how to require eo:bands in either Item fields, Assets or the extension. This is likely quite hard to express in JSON Schema. Having #795 in mind makes it even more complex.

Unfortunately, we forgot about eo:bands changes in #788 completely and I find this a substantial issue in beta.1 so I think we shouldn't leave this unfixed and released in this state for too long.

**Comment by matthewhanson** [comment]
1. I agree documentation could be improved, although I think a lot of this is best practices. eo:bands goes as a list of objects in properties, but any Item property can be used in assets to override it, allowing one to define the bands for each asset within the asset and no references. This part should probably be explained in the EO extenion.

For the sentinel catalog, https://1tqdbvsut9.execute-api.us-west-2.amazonaws.com/v0 I then used the item-assets extension to define a lot of the asset fields, including eo:bands.   At the item level though I did not define the same fields as they aren't required.   I think this bit could use some explaining in Best Practices.

2. Yeah, this just need to be deleted entirely, don't see any other issue.

3. Ah, that stinks, I thought I had gone through all the examples.  I think the EO example should remove it from Item properties and define them at the asset level, as that would be the most common way to do it.

4. No idea how to do this in JSON schema

I can try and issue an initial PR for this in the next couple days unless you have time to hit it before then.

**Comment by m-mohr** [comment]
I tried my best on point 3 (examples) and made some other minor changes. I also removed the requirement for eo:bands (point 4), but didn't had any clue how to require it correctly, so it's optional for now. We should discuss later how we handle requirements with Item Asset Definition...

@matthewhanson Could you give point 1 (docs) a try? I'm running out of time...
