### ISSUE TITLE
Relation between Single File STAC and Collections

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#824]
For me it is not quite clear how the relation between Single File STAC and Collections is. Currently, SFS extends a Catalog and Collections is a Catalog, but at the same time there's a collections field in the Catalog.

From a "Single Item with Collection" use case, I'd find it pretty sweet to just add the collection fields to the top-level in a SFS and not populate the collections array. I'm not sure whether that's allowed and I think should be clarified.

Edit: The Collection JSON Schema doesn't allow it.

**Comment by matthewhanson** [comment]
The top-level in a SFS is basically the "root" catalog, and all the Collections in the catalog are in the `collections` array and all the Items in the catalog are in the `Features` array.

You can't just have collection fields in the top-level because your SFS might have Items from multiple Collections.

**Comment by m-mohr** [comment]
Yes, I know that this is generally the case, but I'm looking at a use case with just one collection and then I asked myself whether I could just extend the Catalog to be a Collection like in "STAC core". It just doesn't say anything about it and should be clarified quickly.

**Comment by m-mohr** [comment]
The underlying question really is: Is a Collection Extension automatically also a Catalog extension?
This is related to #826.

**Comment by m-mohr** [comment]
> Is a Catalog Extension automatically also a Collection extension?

It is, see JSON Schemas.
