### ISSUE TITLE
Update UML for 1.0.0 final release

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#831]
The UML diagram is still in 0.9.0 state, which is fine for a beta release, but should be updated for the 1.0.0 final release.

**Comment by cholmes** [comment]
Are there updates needed since rc.1? We got changes in with https://github.com/radiantearth/stac-spec/pull/1051 

What remains on this one?

**Comment by cholmes** [comment]
@matthewhanson made some final updates to this (like removing summaries) in #1134
