### ISSUE TITLE
Tiled Assets extension split/clarification

### ISSUE THREAD

**Issue by joshfix** [radiantearth/stac-spec#839]
I'm going to write this from the perspective of my Staccato implementation :). In general, Staccato defines extensions as interfaces in Java, so that concrete collections, items, properties etc can be composed from any combination of extensions.

When created the Tiled Asset extension, I found the documentation very confusing -- it took me a bit of time to determine that the extension is comprised of 3 different parts:  "Item, Collection and Catalog properties", "Item properties", and "Item fields".  Each of these sections in the README begin immediately with a table of properties/fields and not with a description/explanation.  At first glance, I thought the `tile:tile_matrix_set_links` definition under "Item properties" was the target definition of the `tiles:tile_matrix_sets` definition under "Item, Collection, and Catalog properties".

Once I realized they were different, I realized it didn't make sense to create a single interface for all 3 sections -- if I want items to provide the field `asset_templates`, I would need that in it's own interface so that Items doesn't attempt to provide implementations for the fields/functions from the other sections of the extension.  There are also other important differences; the first two sections use the prefix "tiles" for the field names but asset_templates does not.

The final comment on this extension is, it makes it difficult to name the 3 sections 
programmatically.  I decided to use 3 separate interfaces to provide support for this extension.  I clearly would not want to name any interface or class anything like `TiledAssetsItemCollectionAndCatalogProperties`, so instead I used the names of the single fields each section defines:  `TiledAssetsSets`, `TiledAssetsLinks`, and `TileAssetsTemplates`.  This makes for cleaner names, but is far from optimal.  If the fields for "Item, Collection, and Catalog properties" ever change or cease to include tile matrix sets, the name `TiledAssetsSets` ceases to make sense.

Having a single identifier for this extension ("tiled-assets") may also be confusing.  If an item provided both `tiles:tile_matrix_sets` and `asset_templates` fields, there would only be a single entry in extensions for "tiled-assets", but that doesn't tell you if you are providing one of those fields or both.  Similarly, if you had a collection that provided tile matrix sets and items that provided asset templates, both places would list the "tiled-assets" extension, but it would be impossible to determine what was actually being provided and confusing because it provides different things in different places.

It feels like this should be broken up into 3 separate extensions, or have the README very distinctly define these as an extension with 3 different modules or aspects.  Each section should then have it's own title, identifier, prefix, etc.

**Comment by m-mohr** [comment]
Looking at it again after some time, I had a very similar experience.
cc @constantinius

**Comment by m-mohr** [comment]
Extension has been moved: https://github.com/stac-extensions/tiled-assets

This issue will be tracked here: https://github.com/stac-extensions/tiled-assets/issues/1
