### ISSUE TITLE
Empty Geometries?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#843]
@abarton-airbus wrote on Gitter:

> Hello. My organization has implemented a STAC compliant catalog. We've come across an edge case that feels unclear in regards to compliance: STAC Items with an empty geometry don't have a clear definition for bbox.
>
> As noted by the spec (and its reference, https://tools.ietf.org/html/rfc7946#section-5), "The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries,.." An empty geometry would have 0 dimensions or bbox = []. However, this does not meet the schema definition (https://raw.githubusercontent.com/radiantearth/stac-spec/v1.0.0-beta.1/item-spec/json-schema/item.json).
> 
> It feels like this edge case may not be addressed? Suggestions?

My answer was:
> I'm not 100% sure we enforce this in the spec, but I'm pretty sure it was meant to be that STAC Items are not allowed to have an empty geometries.

We should check that and adopt wording if necessary.

Related: https://github.com/radiantearth/stac-spec/issues/367

**Comment by cholmes** [comment]
+1 - to me geometry required is key. But yes, let's make sure it's clear in spec / schema.

**Comment by abarton-airbus** [comment]
I'd just clarify that technically this use case is produced when a geometry is provided, it's just an empty geometry. So perhaps the spec/schema needs to not only require geometries, but require they are not empty.

**Comment by cholmes** [comment]
Gotcha, thanks @abarton-airbus - that's a great clarification to be sure we have in the spec. Thanks for flagging it.

**Comment by cholmes** [comment]
So in my mind the 'contract' of STAC is to ensure that everything has space and time. So I lean towards saying that an Item without a geometry (or set to empty) is not actually STAC compliant, but that we should allow non-geometry 'Items' in a catalog, but a STAC validator should only check those that have geometries. 

But that was more in response to people who want STAC to be their catalog for everything. I do think this use case is a bit different, it is things that are geospatial but aren't yet processed for their exact location. 

In the case of  near real time / level 1 products that aren't yet ground locked it does seem like it'd be valuable for a user to have the bounding box that reflects the satellite ephemeris if possible. But I can see that sometimes that isn't possible.

I think I still lean towards how @m-mohr tackled this. Matthias - do you use the same STAC structure but just change the media type? Or is it just an alternate JSON representation? And do you think that is ok, or would it be better for you if that's STAC with an empty geometry?

The fact that geometries aren't required in GeoJSON does make me a bit more open to allowing empty geometries in STAC. So if @m-mohr @abarton-airbus and @ycespb all think that just fixing the bounds to also allow empty geometries then I think I'm cool with it. I looked at OGC API - Features and they didn't seem to say anything about it, I'll try to ask them.

I do think we should add a best practices section on this use case though, that its intended for things that will eventually be geospatial. It does make me wonder if it'd be useful to add some metadata (start as an extension) about the state of processing. To better communicate that an Item is created but needs additional processing or user input to be 'done'. Planet definitely has needs for something like that.

**Comment by pvgenuchten** [comment]
From a wider metadata perspective, iso19115 for example allows to indicate an area by name, without specific coordinates. For example an area name without defined boundaries. But also consider relative positions, such as 'at the back of my car'.

**Comment by m-mohr** [comment]
> Matthias - do you use the same STAC structure but just change the media type? Or is it just an alternate JSON representation? And do you think that is ok, or would it be better for you if that's STAC with an empty geometry?

I don't use this approach yet, that was just an idea some time ago. In openEO, we just have a single STAC Item at the moment per processing result, thus it's either valid STAC or invalid depending on geometry/bbox being null or not. So broadening this up would actually make all valid (and I'd not use null but empty arrays).

> So if @m-mohr @abarton-airbus and @ycespb all think that just fixing the bounds to also allow empty geometries then I think I'm cool with it.

I think it's fine to allow empty geometry/bbox. We should quickly mention it in the Item spec for clients, but not promote it much and recommend against it and then elaborate on it a bit more in best practices.

> It does make me wonder if it'd be useful to add some metadata (start as an extension) about the state of processing. To better communicate that an Item is created but needs additional processing or user input to be 'done'. Planet definitely has needs for something like that.

For me processing is always finished, but users may add the missing info later. What exactly would you add to that extension? I can't think of very much you could do there in a more general manner.

**Comment by jjrom** [comment]
I agree that it is a bit awkward to have a STAC item without a geometry. However, since the GeoJSON specification allows for null geometry (see https://tools.ietf.org/html/rfc7946#section-3.2), there is no reason that a STAC item without geometry should be invalid.

> A Feature object has a member with the name "geometry".  The value
> of the geometry member SHALL be either a Geometry object as 
> defined above or, in the case that the Feature is unlocated, a JSON null value

Additionally, I have been working with the French Space Agency to set up a STAC endpoint to a bunch of collections. Some of these collections contains Level 1 (i.e. unlocated) satellite images so we definitively need that STAC allows null geometry :)

**Comment by m-mohr** [comment]
So if we stick with requiring bbox and geometry to encourage giving spatial information, they would be set to:
```
geometry: null,
bbox: []
```
Is that correct and valid to the GeoJSON spec?`

Actions for the spec would be:
- Allow null for geometry
- Allow empty bbox

**Comment by m-mohr** [comment]
The JSON Schema for GeoJSON doesn't allow empty bboxes (minItems: 4). So the proposal from above won't work as bbox is required in STAC and that is unlikely to change. So we can't really have an empty geometry. Thoughts? Ideas?

**Comment by cholmes** [comment]
Ok, so @m-mohr and I were all set to make this happen, but then realized that the empty bbox isn't valid according to the geojson schemas - https://geojson.org/schema/Feature.json. I even wrote up most of what the 'best practice' section would look like: https://github.com/radiantearth/stac-spec/blob/null-geometry-clarification/best-practices.md#null-geometries

That brought me back to the other route, of having 'items' that aren't quite STAC, but are allowed to have no geometry or bbox. See #848 for my proposal. I'm not set on it, and I'm curious if it'll work for you @abarton-airbus @ycespb and @m-mohr  It feels a bit cleaner to me, and I think it could still be used with unrectified imagery - if there's an approximate bounds use that, if not then just use an 'unlocated item', which isn't STAC-compliant, but still a valid part of the catalog.

**Comment by jjrom** [comment]
@cholmes Having a different type for regular/unlocated items will lead to implementation issue. For instance, if you have a mix of located and unlocated items in the same collection/catalog, you need to explicitly retrieve the geometry of each item to check if it is located or not to produce different links rel="item" entry.
The GeoJSON specification indicates that the bbox property is optional but should not be empty if set (see https://tools.ietf.org/html/rfc7946#page-6)

> A GeoJSON object MAY have a "bbox" member, the value of which MUST
> be a bounding box array

From the GeoJSON specification, an unlocated feature should then have no "bbox" property and a null "geometry".

Why not follow the same approach for STAC item i.e. force a bbox to be a valid array if set, and not bbox if the item is unlocated ?

**Comment by m-mohr** [comment]
I checked the PR and it doesn't work for us that way as each Item is standalone and not necessarily linked to from a catalog yet. Thus we would just erase any STAC reference from the docs as we don't always provide a STAC compliant item then.

I understand both sides. On the one hand the desire to enforce spatio-temporal whenever possible and have a bbox for searching, but on the other hands to cater for those edge cases.

So making bbox optional is not enough. At the very least we should require it whenever a geometry is given (which GeoJSON doesn't enforce). I'm personally fine with allowing (1) geometry: null, bbox not set and (2) geometry set and bbox required, but I can understand the other side that doesn't want to weaken STAC by lowering the spatio-temporal requirements too much.

**Comment by cholmes** [comment]
If we can have our schemas make bbox required as long as the geometry is non-null then I think I'm ok with the null geometry solution. 

Though I think it may still make sense to describe the alternate mimetype path (using application/json when there isn't a geometry) as a recommendation, especially for the second set of cases, when someone just wants to use STAC for 'everything' that they already catalog.

**Comment by m-mohr** [comment]
First Point: Yes, we can make that in JSON Schema.

Second Point: If the items follow the null geometry approach, they are still STAC and GeoJSON so I'm not sure what exactly could be offered as application/json then?

**Comment by cholmes** [comment]
Ah, that's true on the second point. Will think about an alternate approach.

**Comment by m-mohr** [comment]
Just wondering what the actual use case for those "other" items are? Why do they need to be a STAC Item is they can't follow most of the structure needed to be an actual item? Could theses just be exposed via collection assets instead of items?

**Comment by cholmes** [comment]
I'm pretty far from the use case, but I believe they tended to be more 'items' than collections. But it's a good note to add that it's an option.

We discussed on the call 6-23-2020, and decided to go the route with bbox not required if the geometry is null. @m-mohr will do the schema changes, and I'll work on the write up.

**Comment by m-mohr** [comment]
@abarton-airbus and @ycespb, have you an unlocated Item we could add as an example to the spec? The unrectified L1 data would be a nice example, I think.

**Comment by TomAugspurger** [comment]
Can someone double-check my understanding of null geometries? IIUC, this should be a valid Item, since it has a null geometry but does have a bbox:

```json
{
  "stac_version": "1.0.0",
  "stac_extensions": [],
  "type": "Feature",
  "id": "id",
  "bbox": [1, 2, 3, 4],
  "geometry": null,
  "properties": {
    "datetime": "2020-12-11T22:38:32.125000Z"
  },
  "links": [],
  "assets": {}
}
```

Using pystac, I get an error during validation:

```pytb
ValidationError: None is not of type 'object'

Failed validating 'type' in schema[0]:
    {'properties': {'bbox': {'items': {'type': 'number'},
                             'minItems': 4,
                             'type': 'array'},
                    'coordinates': {'items': {'type': 'number'},
                                    'minItems': 2,
                                    'type': 'array'},
                    'type': {'enum': ['Point'], 'type': 'string'}},
     'required': ['type', 'coordinates'],
     'title': 'GeoJSON Point',
     'type': 'object'}

On instance:
    None
```

Does that look like an issue with the jsonschema?

**Comment by m-mohr** [comment]
I think the result here was that you can either provide geometry + bbox or null geometry and no bbox. At least that's what the schema looks like.

**Comment by TomAugspurger** [comment]
Ah, sorry! I read "REQUIRED if geometry is not null" from https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md backwards. Thanks!

Right, I should be able to use the bbox (if any) as the geometry. Thanks.
