### ISSUE TITLE
Negative view:sun_elevation value support (Night Shots)

### ISSUE THREAD

**Issue by erickskb** [radiantearth/stac-spec#853]
The current spec has `view:sun_elevation` defined as:
The angle from the tangent of the scene center point to the sun. Measured from the horizon in degrees (0-90).

At Maxar Technologies negative values are used for night shots. Validation on the equivalent `view:sun_elevation` field is -90 to 90.

A negative sun elevation value helps users identify that the image is a night shot, which can help with filtering depending on use case, as well as potential radiometric algorithms that are sensitive to energy return intensity.

Based on the current `view:sun_elevation` validation, the current STAC spec doesn't support the idea of night shots without creating a custom extension and modifying the `view:sun_elevation` value in our STAC Items.

It seems like this would be a fairly common use case and would be worthy of a standardized way of handling it.

**Comment by cholmes** [comment]
Interesting. Definitely seems worthy of supporting. The -90 to 90 seems like a slight overloading of the concept to me, but I'm no expert in this, and am definitely open to it.

Do we know what others do here? Would be great to have some sample metadata to see how they handle it. At Planet I don't think we publish any night time shots, so with that hat on I don't have a point of view. What does VIIRS do? And what are the other satellites that even do night time shots? If anyone can add any that they know that'd be great - I can try to dig up metadata for them.

**Comment by lossyrob** [comment]
I just ran into this - ASTER data can have negative values, and the values can range from -90 to 90 (see SolarDirection definition in the [L1T manual](https://lpdaac.usgs.gov/documents/300/ASTER_L1T_Product_Specification.pdf). Based on these couple of examples, I'd recommend we shift the spec to allow -90 to 90 values.

**Comment by m-mohr** [comment]
PR #919 has been merged.
