### ISSUE TITLE
STAC API for STAC 1.0

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#858]
STAC API was split off this repository (the core STAC specification) some time ago after STAC 0.9 has been published. The STAC API specification is lagging a bit behind and thus here are some guidelines for implementing STAC APIs with STAC 1.0:

- STAC 1.0 can be implemented with STAC API 0.9
- Once STAC API 1.0 is available, it can also serve STAC 1.0

As there is no way to indicate the STAC API version in API responses, the rules to resolve the STAC API version in client software is as follows:

- Check the `stac_api_version` field first. It will be any version number that is >= 1.0 (including beta/rc releases)
- If not present, check the `stac_version` field. 
   - If it is >= 1.0 (including beta/rc releases), it's a 0.9 API. 
   - Otherwise the API version is the given `stac_version`

Related issues: https://github.com/radiantearth/stac-api-spec/issues/27, #850

**Comment by m-mohr** [comment]
Strictly speaking, only a subset of 1.0.0 can be served in STAC API 0.9.0 as `bbox`, `geometry` and `datetime` in Items have slightly changed. Thus unlocated Items and Items with `datetime` set to null can't be served via STAC API 0.9.0.

**Comment by m-mohr** [comment]
@jisantuc Why has this been unpinned? There's no 1.0 API yet...

**Comment by jisantuc** [comment]
I probably fat fingered it. I have no recollection of deliberately doing that

**Comment by cholmes** [comment]
Can we close this now that we have api beta.1?
