### ISSUE TITLE
Collection Extent schema validity in STAC Catalog Landsat8 and Sentinel2

### ISSUE THREAD

**Issue by emmanuelmathot** [radiantearth/stac-spec#860]
# Context

I am developing a C# stac library. I am using some implementation to make comprehensive tests.
Using Landsat8 or Sentinel-2 catalog on AWS, I found non valid document withcollection schema (https://github.com/radiantearth/stac-spec/blob/master/collection-spec/json-schema/collection.json).

# Issue

For instance in https://sentinel-stac.s3.amazonaws.com/sentinel-2-l1c/catalog.json
Is the extent definition of this collection correct?
It seems to me it misses the bbox in spatial and interval in temporal.
Am I right? If yes, shouldn't the schema adjusted to fit with this or is there a way to regenerate those catalogs according to the schema?

```json
{
    "version": "0.1.0",
    "stac_version": "0.6.0",
    "id": "sentinel-2-l1c",
    "title": "Sentinel 2 L1C",
    "description": "Sentinel-2a and Sentinel-2b imagery",
...
    "extent": {
        "spatial": [
            -180,
            -90,
            180,
            90
        ],
        "temporal": [
            "2013-06-01",
            null
        ]
    },
...
}
```

**Comment by m-mohr** [comment]
Hi @emmanuelmathot ,

great to see work in C# being done!

You are comparing a version 0.6.0 document to the 1.0.0-beta.1 schema. The structure of the extent changed somewhere inbetween, so that is a valid STAC collection in version 0.6.0, but not in 1.0.0 anymore.

**Comment by emmanuelmathot** [comment]
right. I have not considered schema versioning so far. Thank you for the quick answer.
