### ISSUE TITLE
Label Examples need to be Updated

### ISSUE THREAD

**Issue by notthatbreezy** [radiantearth/stac-spec#870]
Some of the examples in the label extension are outdated and could use updating.

For instance, in the spacenet roads [example](https://github.com/radiantearth/stac-spec/blob/master/extensions/label/examples/spacenet-roads/roads_item.json#L155-L160) `label:assets` should be an array. The item linked to and the asset key referenced in the example are not actually the source that the labels apply to either. 

Similar issues apply to the other examples in the label extension as well.

**Comment by m-mohr** [comment]
This issue has been moved to https://github.com/stac-extensions/label/issues/3
