### ISSUE TITLE
Landsat extension

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#874]
@matthewhanson wrote:

> USGS has published an “official” Landsat STAC extension:
> https://landsat.usgs.gov/stac/landsat-extension/schema.json

We should update the examples accordingly, I think. And link it in the community extensions list.

Whom to contact for improvements? There are some things that should be updated to comply with the schemas in beta.2...

**Comment by pieschker** [comment]
@matthewhanson should be able to reach out, he's been working with them.

**Comment by jackdelab** [comment]
You can ping me and/or @matthewhanson on this and any other issues about Landsat STAC extension, thanks @pieschker for bringing this to my attention

**Comment by m-mohr** [comment]
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://landsat.usgs.gov/stac/landsat-extension/schema.json#",
  "title": "Landsat Extension",
  "description": "Landsat Extension to STAC Items.",
  "allOf": [
    {
      "$ref": "https://schemas.stacspec.org/v1.0.0-beta.2/item-spec/json-schema/item.json"
    },
    {
      "$ref": "#/definitions/landsat"
    }
  ],
  "definitions": {
    "landsat": {
      "type": "object",
      "required": [
        "stac_extensions",
        "properties"
      ],
      "properties": {
        "stac_extensions": {
          "type": "array",
          "contains": {
            "const": "https://landsat.usgs.gov/stac/landsat-extension/schema.json"
          }
        },
        "properties": {
          "type": "object",
          "minProperties": 1,
          "properties": {
            "landsat:scene_id": {
              "title": "Landsat Scene Identifier",
              "type": "string"
            },
            "landsat:collection_category": {
              "title": "Collection Category",
              "type": "string",
              "enum": [
                "A1",
                "A2",
                "T1",
                "T2",
                "RT"
              ]
            },
            "landsat:collection_number": {
              "title": "Collection Number",
              "type": "string",
              "enum": [
                "01",
                "02"
              ]
            },
            "landsat:wrs_type": {
              "title": "WRS Type",
              "type": "string",
              "enum": [
                "1",
                "2"
              ]
            },
            "landsat:wrs_path": {
              "title": "WRS Path",
              "type": "string"
            },
            "landsat:wrs_row": {
              "title": "WRS Row",
              "type": "string"
            },
            "landsat:cloud_cover_land": {
              "title": "Land Cloud Cover",
              "type": "number",
              "minimum": 0,
              "maximum": 100
            }
          }
        }
      }
    }
  }
}
```

**Comment by m-mohr** [comment]
Once that's published again, we should update our examples and make a PR to add the schema to the community extensions.

**Comment by m-mohr** [comment]
Any news on this? @matthewhanson @jackdelab

**Comment by jackdelab** [comment]
@m-mohr not yet, we have not had time to work on this lately

**Comment by matthewhanson** [comment]
@m-mohr planning on tackling this during Thursday sprint

**Comment by m-mohr** [comment]
Any news on this? We'd like to use the new schema in the next months! @matthewhanson @jackdelab

**Comment by jackdelab** [comment]
> Any news on this? We'd like to use the new schema in the next months! @matthewhanson @jackdelab

It is being worked now, we should have a more exact timeline within the next week or two

**Comment by jackdelab** [comment]
Current timeline is that it will be ready in March @m-mohr

**Comment by jjfrench** [comment]
Hey @m-mohr, you can message me or @matthewhanson about Landsat STAC extension issues going forward. We made the updates for the changes above a few months ago but haven't updated the deployed version. I'll look into making sure it fits into that linked schema.

**Comment by jjfrench** [comment]
https://landsat.usgs.gov/stac/landsat-extension/v1.0.1/schema.json
Let me know what you think

**Comment by m-mohr** [comment]
@jjfrench Looks good to me with two minor exceptions:
- There's a `"additionalProperties": false` at the end, which has no effect/is not used
- The definition for `stac_extensions` requires `properties`, but there's no field `properties` defined. 

Those issues though are just things that don't make much sense in JSON Schema, but will be ignored in validation. So it still works.

**Comment by m-mohr** [comment]
@jjfrench Is there written documentation for this extension? It would be nice to add it to the list of STAC extensions, but this would require some human-readable document.

**Comment by m-mohr** [comment]
@jjfrench @matthewhanson  Is there written documentation for this extension? It would be nice to add it to the list of STAC extensions, but this would require some human-readable document.

**Comment by jjfrench** [comment]
@m-mohr I didn't end up creating any documentation while I was at EROS, but I've shared this issue with some people that might've done so after I left
