### ISSUE TITLE
Figure out a nice display of core openapi specs

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#88]
Right now the instructions to 'explore the spec' are to put the file in to http://editor.swagger.io/

But that doesn't persist anything, and it's annoying to do that each time.

It should be pretty easy to generate the same type of online page from our documents and make it persistent. I don't actually know how to do this, so if anyone else does please let me know.

**Comment by hgs-trutherford** [comment]
Chris, I've used [swagger ui](https://swagger.io/swagger-ui/) before. It's pretty easy to get setup.

Are you thinking of using github pages for the site hosting? Or something else?

**Comment by cholmes** [comment]
Yeah, I went ahead with swaggerhub - I really just needed to invest like 3 minutes of time looking in to this. https://app.swaggerhub.com/apis/cholmesgeo/STAC-standalone/0.4.0 is now in the readme, along with the wfs one.

Swagger-ui on github pages I think would be a bit better - I don't love depending on some proprietary hosted service. But in my 3 minutes total of research I wasn't sure if it would work on github pages, and then realized I could finish the task by just using swaggerhub.
