### ISSUE TITLE
Min/Max range of values for bands

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-spec#890]
In 0.6.2 of the ee collections files, we had gee:min and gee:max for the range of values that are found in that band.  Looking at the eo extension, I don't see a place for them.

**Comment by m-mohr** [comment]
Here's a related PR that may include min/max values for bands: https://github.com/radiantearth/stac-spec/pull/879

**Comment by schwehr** [comment]
@cholmes It looks like #879 talks about the data type and the min/max zoom, but if band 12 is a 16-bin int and we want to say that the values are only going to be in the range `[0..4096]` is there something in #879 that I'm missing?

**Comment by m-mohr** [comment]
@schwehr Yes, you are missing the discussion. ;-) It is currently discussed to add min/max, but it's not yet in the actual PR.

**Comment by cholmes** [comment]
@schwehr - You mean you didn't read through the 20 pages of comments of discussion? ;) But yeah, like @m-mohr said, we've pretty much decided to add min/max, just need to figure out where and get it in. 

If you want to experiment with it in your catalog now that'd be great to help make sure we'd get it right. Looks like the names will likely be `render:min_pixel_value` and `render:max_pixel_value` (though open for feedback on the names). And you can apply it on the asset. We like to have implementations along with the extension proposal, s would be great.

It's top of the list for my spec work to get this in, but I'm quite slammed organizing the sprint, so probably won't get to it for a few weeks, though anyone else is welcome to take it over.

**Comment by schwehr** [comment]
@cholmes Does "asset" mean that it would work on `Collection`s and `Item`s?  Sounds good.

**Comment by cholmes** [comment]
Yeah, in one the recent versions we introduced the ability to properties at item or asset levels. Item is generally better, as it'll show up in search. But for the min/max pixels many people want it at the asset level. For collection I *think* the best practice would be to put it in the 'summary'?

**Comment by m-mohr** [comment]
Yes, if it's defined for item properties, it works in Collection summaries.
