### ISSUE TITLE
Order offline assets

### ISSUE THREAD

**Issue by gilltk** [radiantearth/stac-spec#891]
This issue is about ordering offline assets. Such assets could be rasters that reside a tape archive and must be 'activated' (to borrow Planet terminology) before they're available for download.
 
I am after some feedback on the following scheme for users to be able to order offline data. The vision our team has is shown at the video on this page: https://medium.com/@mojodna/a-stac-browser-348a60674061. If we get this right, then:
- a user will use a STAC browser to navigate a catalogue until they get to a StacItem
- the browser renders the Assets for the StacItem as hyperlinks
- the user can select an 'order' link to request the asset be activated
- in response, the browser renders the StacItem again, but with some updated properties on the status of the order and a link that the user can select to check the progress
- the user-browser interaction loops until the browser display's the StacItem's  'download' link, which the user selects to access the image.
 
There is more detail about our scheme below for the interested reader. If you read it, then I'd be very grateful:
- for people's thoughts on this scheme; example: is there a simpler approach? are we using the notion of an asset correctly?
- to know if we need to propose a STAC extension (like an 'order' extension) to implement this scheme? Or does the existing STAC 1.0.0-beta support it
 
Now to the detail. In our scheme, a StacItem has an 'order' asset, the URL to which is a request to our server to 'activate' the asset. The server responds with a 202 (processing) and a StacItem in the body. The StacItem's properties has an order:status field with the status of the order ('offline', 'processing', or 'online'). The returned StacItem's assets has a URL so the status can be queried again.

The following example workflow may make the scheme clearer. Below is a snippet of a StacItem returned from a search result. Note:
- The 'order' asset; it contains a link to our order endpoint so the file can be ordered
- The 'order:status' attribute in the properties; it is currently offline
 
```
{
  "id": "cemsre_t54jvn_20161118_abam4.img",
  "assets": {
    "metadata": {
      "href": "https://data-access.jrsrp.org.au/productmetadata"
    }
    "order": {
      "href": "https://stac.jrsrp.org.au/order?filenames=cemsre_t54jvn_20161108_abam4.img&state=NSW"
    }
  },
  ...

   "properties": {
    "collection": "nsw-Sentinel2-reflectance_10m",
     ...
     "order:status": "offline"
  },
}
```

A request is placed to order the file using the order-asset link. The response is a 202 (processing) and the StacItem is returned. Note:
- the order:status attribute in the returned StacItem has changed to 'processing'

```
"id": "cemsre_t54jvn_20161118_abam4.img",
"assets": {
    "metadata": {
      "href": "https://data-access.jrsrp.org.au/productmetadata"
    }
    "order": {
      "href": "https://stac.jrsrp.org.au/order?filenames=cemsre_t54jvn_20161108_abam4.img&state=NSW"
    }

  ...

  "properties": {
    "collection": "nsw-Sentinel2-reflectance_10m",
    ...
    "order:status": "processing",
  }

```

The client may use the order-asset link again to query the order's progress. When the file becomes available for download, the response will be code 200 with the body containing the StacItem as follows. Note:
- there is now a 'download' asset
- and the order:status is 'online'

```
...
...
"id": "cemsre_t54jvn_20161118_abam4.img",
"assets": {    
    "metadata": {
      "href": "https://data-access.jrsrp.org.au/productmetadata"
    }
    "download": {
      "href": "http://qld.auscover.org.au/public/data/spatial_other/jrsrp/jrsrp-data-access/order_506/cemsre_t54jup_20180224_abam4.img"
    }

  ...
  ...

  "properties": {
    "collection": "nsw-Sentinel2-reflectance_10m",
    ...
    "order:status": "online",
  }
```

**Comment by matthewhanson** [comment]
Hi @gilltk I think are certainly using assets correctly, and this seems like a good approach.  I like the idea of an "order" asset URL, and that might be good best practice. Or perhaps we can add "order" to the list of roles an asset can have which.

I see this as more useful for per-user ordering rather than for activating offline data, as it's a more common use case.  Data provider has a catalog, and an individual user may order it but that will only make it available for that user, so you wouldn't want to add a general field to the Item.

So I see two different use cases here, but not sure if extension is needed in either case:

For per-user ordering, you want an order asset

For online/offline you want the order asset + a status field which will be applicable to all users wanting to access that data

**Comment by gilltk** [comment]
Hi @matthewhanson 

Thank you for your feedback.

It's good to know you don't think an extension will be needed in either of your use cases. I thought we might have needed one because we use order:status in the Item properties - but on further reading I see the spec is flexible enough to allow this.

In our case we are focussed on the online/offline use case. Once the data is online it is online for everyone. So we will use the order asset and the order:status field. As an aside, we also think this can be implemented per-user, especially if there are access controls on the requested data.

Also, any thoughts you have on the following would be welcome.

While the spec allows any role name, I see that there's also a short list of 'standardized' roles at https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-role-types. I am certainly happy to use the 'order' in the roles list for the asset, if you think it may become a standardized in the future. I also see that it would be a good idea to use the 'data' and 'metadata' roles for the metadata and download assets I used above.

I'm not totally clear on your other use case, for per-user ordering. What use cases do you have in mind here? What I'm not clear on is: when is it not required (or useful) for a single user to know the status of an order they've placed?

**Comment by emmanuelmathot** [comment]
I started the order extension here: https://github.com/stac-extensions/order
I will take into account what has been discussed here so far

**Comment by pieschker** [comment]
Repo started
