### ISSUE TITLE
Required fields, assets and schemas

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#892]
We have recently allowed to put fields into assets, but the schemas and specifications don't fully support that.

For example, it says that sar:product_type is required, but it doesn't say what happens if I put that in assets. Is that still requiring it in properties?

Also, the JSON Schemas can't validate the fields in the assets. So we should add validation for them there and get an idea about how to handle required fields.

**Comment by matthewhanson** [comment]
Can we include Item properties in assets for validation without making any of them required and without having to duplicate the entire JSON schema under assets?

As far as requirements.....I'd say that if it is required in Item properties then it should always be required, even if you put it in assets. Putting it in assets can override the Item property for that asset, but you can't search it and some clients may rely on required fields actually being there.   So it should be some nominal, default, or most likely value.

**Comment by m-mohr** [comment]
> Can we include Item properties in assets for validation without making any of them required and without having to duplicate the entire JSON schema under assets?

With some restructuring, it should be possible.

> As far as requirements.....I'd say that if it is required in Item properties then it should always be required, even if you put it in assets. Putting it in assets can override the Item property for that asset, but you can't search it and some clients may rely on required fields actually being there. So it should be some nominal, default, or most likely value.

That makes sense. And as eo:bands is not required, we don't duplicate those.

**Comment by m-mohr** [comment]
ToDos:

- [x] stac-extensions org template
- [ ] eo
- [ ] projection
- [ ] scientific
- [ ] view
