### ISSUE TITLE
STAC/COG Storage Advice

### ISSUE THREAD

**Issue by TimJMartin** [radiantearth/stac-spec#898]
Hi

I am just starting to look at using STAC and COGs for some of our raster and imagery datasets. We use AWS S3 for storing the data as a backup, however I think there is a better way to use the bucket and the folder hierarchy to work in tandem with a STAC. Listening to some of the presentations last week it seems lots of others are using AWS so wondered if someone could give me some advice or comment on the option below. 

We have multiple different datasets refreshed at different times of year and have an archive of over 10 years to publish. We also need to potentially support multiple different projections.

I was thinking of this type of bucket structure

- BucketName

	- Dataset_Name1
		- Release_Date1
			- ProjectionA
				- COGs
					- UniqueID1.tif
					- UniqueID2.tif
				- Thumbnails
					- UniqueID1.png
					- UniqueID2.png
			- ProjectionB
				- COGs
					- etc
		- Release_Date2
			- etc
	- Dataset_Name2
		- etc

initially I will be creating a static STAC but in time would probably like to generate one more dynamically as the biggest dataset I have has 250k tif files, so if there is better storage layout to make generating a STAC easier then if someone could give me ideas that would be great
Thanks

**Comment by matthewhanson** [comment]
@TimJMartin  
What does your STAC Item look like?  Are you including multiple projections within a single STAC Item, or are they different Items?  Likewise with release date, are those the same Items?

I think there is no one structure that works for everyone and really comes down to data access pattern. I like to think of hierarchy in terms of what users are interested in first, then drill down.  For instance in a lot of use cases users are primarily interested in a geographic area first, then by date.

On the other hand the hierarchy isn't super important if you are using a STAC API, as that abstracts the actual locations in the asset URLs.   But it's still a good to have a sensible organization.

**Comment by m-mohr** [comment]
Closing due to no acitivity.
