### ISSUE TITLE
Make summaries available in catalog as well as collection

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#903]
Having the summaries back in 'catalog' will allow it to be more used to aid in navigation, and since all collections are catalogs it will still work there.

**Comment by m-mohr** [comment]
Wait, you mean summaries, right?

**Comment by cholmes** [comment]
yes :(

**Comment by cholmes** [comment]
I get confused because it's the 'stats object'. but the 'summary' field.

**Comment by matthewhanson** [comment]
+1
