### ISSUE TITLE
Label extension schema requires label:classes property even when not using categorical data

### ISSUE THREAD

**Issue by kbgg** [radiantearth/stac-spec#904]
The Label extension says that the label:classes property is "**REQUIRED** if using categorical data." and the schema for the extension says that the property is always required. STAC Validator currently fails when validating a label item does not contain that property in the case of non-categorical labels since it's reading the schema file and expecting that all items implementing the label extension must have that property no matter what. Not sure what the best solution here is, maybe just remove label:classes from the required properties in the schema?

**Comment by m-mohr** [comment]
Is there a way to determine from the JSON that data is categorical? If yes, we can make it happen that the field is required only for categorical data. Otherwise we'll likely have problems with a proper JSON Schema that models the written docs.

**Comment by kbgg** [comment]
From what I can tell, no. Simply the absence of that property indicates that the data isn't categorical.

**Comment by m-mohr** [comment]
Okay, then we should remove the requirement from the JSON Schema. Are you up to make a PR? :-)

**Comment by kbgg** [comment]
Just put it in!

**Comment by lossyrob** [comment]
Closed by #905
