### ISSUE TITLE
raster stats metadata

### ISSUE THREAD

**Issue by demiurg** [radiantearth/stac-spec#906]
Recently I have worked on issue where a client requested some "quality" information about the data being processed. One of the indicators they could use is the percentage of nodata to data values in the raster. This attribute is among some other generally useful attributes GDAL 'gdalinfo' returns using the `--stats` flag: 

```
    STATISTICS_MAXIMUM=959.73065185547
    STATISTICS_MEAN=0.11471631463069
    STATISTICS_MINIMUM=4.9432208015787e-07
    STATISTICS_STDDEV=0.34942824214698
    STATISTICS_VALID_PERCENT=65.45
```

GDAL also returns the same information using the `GetStatistics` method.

So, without reinventing the wheel, we added the following attribute per each raster, using the GDAL like names:
```
"VH": {
    "title": "VH",
    "description": "VH Polarization",
    "type": "image/tiff; application=geotiff",
    "roles": ["data"],
    "sar:polarizations": ["VH"],
    "href": "<redacted>",
    "raster_stats": [{
        "valid_percent": 54.45,
        "maximum": 636.634033203125,
        "minimum": 2.184528646864692e-8,
        "mean": 0.038179099559783936,
        "stddev": 0.12487602233886719
    }]
}
```

Would it be a good idea to standardize these "raster_stats" as an extension to the STAC spec? 

One of the important use cases for these statistics being standard is software such as QGIS using them to create color scales automatically. There has also been a prior question by @matthewhanson https://github.com/radiantearth/stac-spec/issues/803

**Comment by demiurg** [comment]
I have reviewed the pull request discussion for rendering hints (https://github.com/radiantearth/stac-spec/pull/879), and it appears that these both the above suggestion and the rendering hints are in the same category of very useful metadata.

There are a few ways to merge the metadate keys here. Currently the keys in above example use level 1 key of` ["raster_stats"][<band index>][<stat_name>]`.

* This could be re-arranged remove a level, such as ["raster_stats:"<stat_name>][<band_index>] 
* To rename it and make it part of the 'render' extention, it would be ["render:raster_stats_"<stat_name>][<band_index>]

So, first question, should these extentions be merged?
If they should, what is the best way to merge?

Personally, it seems like they can be used for the same purpose, but stats can be used for a few other things, it is not visualization specific. If it is separate, it might be better to keep as a dictionary.

**Comment by cholmes** [comment]
@demiurg - apologies for the slow response on this one. I think we might have talked about this on a call? I remember thinking about it. 

I'm compelled by keeping 'stats' separate, as more useful for things than just rendering. I think the rendering hints extension could evolve to just reference stats and data_type as other useful extensions. 

To me the biggest thing is to figure out where to put this info per band. But I'm realizing I don't have a super clear picture of how to use eo:bands to describe a basic band ordering... I think we decided you should describe bands in each item, and so if we do that then we can probably just add the stats directly there?

**Comment by cholmes** [comment]
Progress on this at https://github.com/stac-extensions/raster

**Comment by demiurg** [comment]
Thanks for the update, I'll follow the above idea as the way forward on this!
