### ISSUE TITLE
Items from Multi-Platform Acquisition

### ISSUE THREAD

**Issue by JohnBTasker** [radiantearth/stac-spec#908]
Dealing with city-scale 3D photogrammetry data (.slpk / .obj) derived from a combination of fixed-wing, helicopter and terrestrial imagery. We do not hold the raw data, just the output 3D mesh. Key issue is that we cannot represent all platforms in the current common metadata fields. To overcome this issue, it is proposing that the `platform` field in common metadata be extended to support a list structure. 

The alternative is for the 'platform', 'instruments', 'constellation' and 'mission' fields in common metadata be grouped into an instrument object, with the option to support one or more instances associated with an item. For example:

```
"instrument": {
  [
    "platform": "Piloted Aircraft",
    "instrument": "A3 Edge",
    "constellation": "XXX Company Aircraft Fleet"
    "mission": "3D Program"
  ],
  [
    "platform": "Human",
    "instrument": "Canon EOS 850D",
    "mission": "3D Program"
  ]
}
```

**Comment by m-mohr** [comment]
We are not prepared for such things with the current spec. Additionally, objects can't be searched easily (=> API) so we will have a hard time to integrate your second proposal. We always try to stick to scalar values in properties, or if necessary, arrays. So maybe platform could be platforms and an array, same for constellation. The question now is whether it's too late for such fundamental changes?!

**Comment by cholmes** [comment]
Hrm, we should definitely discuss and decide this soon, as the next couple weeks are our last chance to make such core changes. I definitely would like us to be able to represent 3d meshes made from multiple platforms in STAC well, thanks for bringing this up @JohnBTasker 

I agree that objects in the core are less good, so the instrument object sounds less good.

I think I'm not opposed to making platform a list. My only hesitation is that it seems to water it down a bit - like if you are searching for satellite imagery and you get a 3d mesh as a result that only uses 1 satellite image is that what you want? I wonder if we could keep platform as a single value, which is implicitly the 'primary' (meaning to be determined by the provider), and then an 'additional_platforms' value that is a list? 

What do people think of that? John you'd need to pick if fixed wing, helicopter or terrestial is the one you want to show up in search, does that seem reasonable? 

Another route I could see is we have a 'City 3D' extension (or whatever you want to call it, multi-source 3d?) that has an advanced 'instrument' field like you say. And then could add in more information there.

**Comment by m-mohr** [comment]
If it's a product of multiple platforms, a logical way for me would be to not specify the platform at all and link to source STACs that then include the platform for each of the sources. Another idea would be to use collection assets and summaries to describe multi platform products, but that could be less ideal. I don't fully understand the use case yet or how it's modeled, thus it's hard to judge what makes most sense.

**Comment by cholmes** [comment]
Ok, we discussed this on the call today, and decided that allowing 'platform' to be a list will water down things too much. The preferred route is to link the derived product to its 'sources' that would each have one platform. I understand in this case that there aren't actual STAC items existing, but it could be possible to create them just to be able to refer to them. Matthias's other suggestions also work. You could just use the 'collection' construct and then the summary can contain multiple ones. You can 'just' have a collection, without items, which seems sorta like the case here, where the items aren't specified. 

The other route is as I suggested, to make an explicit extension for it. And then have a richer instrument structure there, as an 'add-on'. You'd pick one platform, or leave it null, but then you could model the specific platforms in a single item.
