### ISSUE TITLE
Item geometry / proj:geometry extended to support MultiPolygon

### ISSUE THREAD

**Issue by JohnBTasker** [radiantearth/stac-spec#909]
In edge cases, the geometry of an object can be a GeoJSON MultiPolygon rather than a Polygon (e.g. aerial/drone imagery mosaic).  It is proposed that the schema for the `geometry` field in the Item spec, and `proj:geometry` in the Projection Extension be extended to support the GeoJSON MultiPolygon type to cover these instances.

**Comment by philvarner** [comment]
Item geometry does this -- it's any GeoJSON geometry and links to that spec.

I originally wrote up the Proj Extension, and I don't know now if I wasn't thinking it through or it got changed, but I do think that field *should* have the same type as Item.geometry.

**Comment by cholmes** [comment]
Discussed on call 2-18-21, everyone agreed it should have the same type as item.geometry

**Comment by m-mohr** [comment]
PR #995 addresses the issue.
