### ISSUE TITLE
doi registrant code is too restrictive in the schema

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-spec#910]
In extensions/scientific/json-schema/schema.json
```
"sci:doi": {
          "type": "string",
          "title": "Data DOI",
          "pattern": "^(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![%\"#? ])\\S)+)$"
        }, 
```

This is too narrow: `[0-9]{4,}`

https://www.doi.org/overview/DOI_article_ELIS3.pdf

```The registrant code is
a unique alphanumeric string assigned to an organization
that wishes to register DOI names (four digit numeric codes
are currently used though this is not a compulsory syntax).
The registrant code is assigned through a DOI registration
agency, and a registrant may have multiple-registrant
codes. 
```

https://www.doi.org/doi_handbook/2_Numbering.html#2.2.2

```
The registrant code is a unique string assigned to a registrant.
```

So my best guess at what the doi regex should be is this based on the `alphanumeric` statement in the pdf.

```
          "pattern": "^(10[.][0-9a-zA-Z]+(?:[.][0-9a-zA-Z]+)*/(?:(?![%\"#? ])\\S)+)$"
```

So this should be a valid doi if the prefix was registered: `10.123abc.foo.bar/issn.1476-4687/this/is/nuts`

I'm not sure what the suffix part of the pattern will match: `(?:(?![%\"#? ])\\S)+)`

https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

**Comment by m-mohr** [comment]
That seems to be a valid point. The original reg exp we used is from here: https://www.regextester.com/93795
Maybe we can also learn a bit from here: https://www.crossref.org/blog/dois-and-matching-regular-expressions/
Would you be up to contribute a new version in a PR?

**Comment by schwehr** [comment]
I will definitely cook up a PR.  I have been exploring DOIs more while working on the scientific extension in https://github.com/stac-utils/pystac/pull/199.  e.g. https://gist.github.com/schwehr/22ce6080eb9e730ef04fccfa25072e3a

I am wondering if anyone has valid DOIs that fail to validate?

**Comment by m-mohr** [comment]
With the CrossRef article in mind, I have relaxed the DOI regex to `^10\.[0-9a-zA-Z]{4,}/[^\s]+$` That should capture mostly all regexp out there, I think.
