### ISSUE TITLE
CARD4L / view:incidence_angle for SAR

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#912]
In the S1 CARD4L metadata we have the following entries:
```
         <IncAngleNearRange units="deg">30.21837</IncAngleNearRange>
         <IncAngleFarRange units="deg">45.66830041167159</IncAngleFarRange>
```

How is that intended to work with the `view:incidence_angle` field?

**Comment by emmanuelmathot** [comment]
For sentinel1, those entries refers to the min and max incidence angle according to the sensor mode and the the acquisition swath. (e.g. https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes/extra-wide-swath). The `view:incidence angle` is a normalized metadata across sensors. Usually the angle of the center of the total swath is used which is also expected for S1.
