### ISSUE TITLE
MIME types for STAC and for things like Earth Engine?

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-spec#918]
I'm wondering about mimetypes. Should there be one for STAC?  e.g. `application/stac+json`?

And what to do for EarthEngine FeatureCollections, Images and ImageCollections. These things don't return specific bytes.  The API is JSON, so something like  `application/vnd.ee.image+json`, `application/vnd.ee.imagecollection+json`, `application/vnd.ee.featurecollection+json` Although ImageCollection might be explicitly forbidden as a collection of things, but I don't think so as zip, tar, etc. are ok.

References:

- https://www.iana.org/assignments/media-types/media-types.xml has lots of things that are `+json`.
- https://en.wikipedia.org/wiki/Media_type 
- https://tools.ietf.org/html/rfc6838

**Comment by m-mohr** [comment]
Is that for Items, Collections or Catalogs? Would we need multiple media types

**Comment by schwehr** [comment]
I would think for all of the file types.  I'm not sure if they would need to be multiple types.  Some of the already registered mime types cover vast swaths of functionality. 

I reached out to [George Percivall](https://www.ogc.org/ogc/organization/staff/gpercivall) at OGC for thoughts (links added by me):

> [OGC API - Records group](https://www.ogc.org/projects/groups/apirecordsswg) handles much of that discussion.  They are meeting.  Peter Vretanos chairs that WG.
> Also, OGC is registered as a MIME authority and that discussion happens in the [OGC Naming Authority group](  https://www.ogc.org/ogcna).

**Comment by cholmes** [comment]
+1 to doing this - I just hit a potential need for it myself. From gitter @ycespb said:

 > For your info, we also need a dedicate MIME type to distinguish from other OGC representations. We are currently using "type": "application/geo+json;profile=\"https://stacspec.org\"" for STAC representations. See for instance at https://ergo.spacebel.be/collections/datasets/items/PR1_OPER_CHR_MO1_1P_20131119T035100_S25-016_E031-023_0001?httpAccept=application/geo%2Bjson;profile=%22https%3A%2F%2Fstacspec.org%22.

That seems sensible to me - communicating that it is GeoJSON (for Items), and adding a bit more. Not sure what we'd do for collections in that case though.

Eventually we'll be in OGC and can use their naming authority.

**Comment by m-mohr** [comment]
+1 for media type

So GeoTiff got `image/tiff; application=geotiff; profile=cloud-optimized`

Item: application/geo+json; application=stac; profile=item
Catalog: application/json; application=stac; profile=catalog
Collection: application/json; application=stac; profile=collection

Or something like that?

Not sure whether having a Naming Authority is a good or a bad thing?!

**Comment by cholmes** [comment]
Makes sense to me. If others have more experience defining media types please sound in. Like I don't know if 'profile' is the perfect way to differentiate item and catalog, but I don't know the alternatives. Also wondering if maybe stacspec.org would be better than 'stac', in case there are other people using 'stac'? I don't feel a need to put the full https:// on it though.

I think Naming Authority helps get you listed / linked to more. But with STAC we're clearly fine with a more bottoms up approach.

**Comment by cholmes** [comment]
Closing this in favor of #851, as I'm pretty sure they're getting at the same thing.
