### ISSUE TITLE
Separate label extensions

### ISSUE THREAD

**Issue by jisantuc** [radiantearth/stac-spec#938]
The label extension includes a number of special cases for raster labels, like those are weird labels. Work with raster labels has revealed areas that the raster label extension [doesn't handle very well](https://github.com/radiantearth/stac-spec/issues/936#issuecomment-749024743). The label extension as is is quite large in terms of the number of fields added, and raster and vector items will probably continue to drift. With this in mind, the label extension should be split at least into a `vector-label` and `raster-label` extension, possibly with a `label-common` extension holding the common fields.

This issue exists for:

- advocacy for / against splitting the label extension
- advocacy for or against the `label-common` extension that vector and raster label extensions inherit from

**Comment by philvarner** [comment]
+1 for splitting it in 3 -- or just splitting it in 2 and making sure the names used by both remain the same

**Comment by m-mohr** [comment]
Issue has been moved to https://github.com/stac-extensions/label/issues/2
