### ISSUE TITLE
Create JSON-schema for EO profile validation

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#94]
It'd be good to have a JSON-Schema file that can be used to validate the Earth Observation profile, so people can check that they're compliant.

cc @jeffnaus & @matthewhanson

**Comment by m-mohr** [comment]
I could definitely support here as I am familiar to both EO extension and JSON schema. Not sure how familiar @matthewhanson is with JSON schema?

**Comment by matthewhanson** [comment]
Haven't dealt much with JSON schema, I'd take a crack at it because I did want to figure it out but won't have time until week after next. So if you get some spare time and want to do it have at it @m-mohr

**Comment by m-mohr** [comment]
I'll put it on my list, but not sure either about time. We should first concentrate on getting the EO extension renamed and the other fields for the datasets added etc. (see https://github.com/justinwp/stac-spec/blob/feat/dataset/extensions/stac-eo-spec.md)

**Comment by cholmes** [comment]
Yup, definitely lower priority on this one - let's focus on the 'must-haves' first. Plus all those things shifting might lead to tweaks to EO profile.

**Comment by m-mohr** [comment]
New PR: #266

**Comment by m-mohr** [comment]
Got merged, thanks @jeffnaus for the initial work and PR!
