### ISSUE TITLE
Add uri-reference to JSON Schemas for abs.+rel. links

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#957]
JSON Schema got a new format called "uri-reference" with draft 6. A URI Reference is either a URI or a relative-reference, according to RFC3986, section 4.1. So I think we should just add this to the JSON Schemas for links, urls, assets etc. Then we can adopt the language here. I'll put that on my todo.

_Originally posted by @m-mohr in https://github.com/radiantearth/stac-spec/pull/953#r565678397_

**Comment by m-mohr** [comment]
I also need to check whether I should use iri-reference (https://tools.ietf.org/html/rfc3987) or uri-reference.

**Comment by cholmes** [comment]
Oh cool! Just yesterday I was reading that section of the spec where we say we just allow 'anything' in the json schema, and thinking how unsatisfying that is.

**Comment by m-mohr** [comment]
PR #953 contains the changes.
