### ISSUE TITLE
CARD4L: "processing:facility" required?

### ISSUE THREAD

**Issue by bossie** [radiantearth/stac-spec#959]
https://github.com/radiantearth/stac-spec/blob/card4l-eo/extensions/card4l-eo/README.md

On one hand, this specification for CARD4L marks the "processing" extension as optional (at least twice), but on the other, it marks the field "processing:facility" as required.

Is "processing:facility" required or not?

Thanks!

**Comment by m-mohr** [comment]
Hi @bossie, it is not required. I've updated the spec.
