### ISSUE TITLE
EO Bands recommendations / clarifications

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#960]
I'm working on updating examples, and also working on adding eo:bands to Planet data. 

But I'm unsure on the recommendations / best practices, and I think we should improve the text to be a little more clear on how you apply things (in some combination of the extension itself and/or in best practices).

* Should I include the full bands in the properties object?
* Should I also include the full bands object in each asset? 
* If I just have one asset (like an rgb or bgrn), should I just have the same band object in both places? 
* We say: 'their primary use now is only to advertise a set of bands that may be available in some of the Assets in this Item'  Does this mean having it in the properties imply that the asset uses the same? How can you know if an asset is using that band order? Like is there an assumption that if 'bands' isn't specified in an object it is defined by the property level bands? If this is true that probably means we need to force people to be explicit on bands in like UDM / QA - but I'm not sure if our band object is rich enough to describe that? 
* Is band order implied? Like if I put bands in a certain order does that mean that the asset's bands are of that order? (I think yes, since it's a list, but I think we should be clear about it, and want to confirm that is our intent)
* What is 'name' vs 'common name'? When should I use name? What should I put there? We say: `e.g., "B01", "B8", "band2", "red"`. Why would I use 'red', when that's the common name? Why would I call it b01 vs b8 vs band2 (I'm coming from Planet, where we don't have a strong definition of this)

I think most of these probably have a straightforward answer that we just need to clarify. But the crux I think is 'what is the purpose of eo:bands' in properties, vs in an asset. When would I do one or the other? And if I define in properties is that actually meaningful information about the assets? 

It seems like at the very least it may make sense to give assets some way to say 'I'm using the band information as defined at the property level'. To differentiate from 'band objects don't really make sense for this asset'. 

I'm happy to update the spec once we reach a good answer on this.

**Comment by fabricebrito** [comment]
We've been quite active creating STAC items out of several EO missions and we often run into that question as well.

There's one case where eo:bands definitely have to exist at Asset level:
- an XS geotiff with multiple bands 
- a pan geotiff
My two cents to your questions:
1. Not really. If it's available in the Assets, that is fine and IMHO more useful
2. Yes, there's one case (among others) where eo:bands definitely have to exist at Asset level:
- an XS geotiff with multiple bands 
- a pan geotiff
3. I'd be happy with enforcing people to be explicit on bands. As EO processing services developers, this is where we look for the information for using the assets correctly 
4. We do rely on the band order. I don't see another way of being sure to have the right asset
5. As EO processing services developers, we always check the "common name" since the name is not a controlled dictionary. We often use name=common name but that's just to ease things.

Hope that helps

**Comment by cholmes** [comment]
@fabricebrito - thanks for sounding in!

I've been thinking about this last night, and I feel like we just need to tighten the spec up a bit. Right now I feel like we're conflating two slightly different things, without providing clear guidance. 1) Inform about the bands that this item / scene has, and 2) describe the bands and band order in each asset.

I think you and @matthewhanson have been focused on 2), and I think it's the 'more' useful thing - indeed I know many cases where eo:bands has to exist at the asset level (and less where it really has to at the properties level). But the extension right now is ambiguous as to the use cases it solves. I could see us just saying 'eo bands belongs at the asset level' - it precisely describes the bands of actual assets. 

I think the only thing that doesn't really work with that is that 'summaries' potentially get a bit weird. They are the other useful bit for eo bands - you can look at the collection and it will tell you what bands this collection has. I guess for the 'collection only' use case (no items) it's fine - you can have a summary of bands. It just feels a bit weird to have the summary of a real collection of items not actually be a summary of the properties, but some implied roll-up of the bands that are used in the assets.

We could explicitly say 'eo bands at the property level is just informative', and that asset level is where it 'matters'. But that does feel like it'd often be duplicative. 

The other idea that would make sense to me would be to bring back the eo:bands reference array. Like in 0.9 and before you could say "eo:bands": [0] in the asset, referring to the index of the array of the bands object in properties. That used to often be in a 'merging' paradigm - I think we'd not bring the merging back - each item would need to list its full eo:bands object, but it wouldn't need to replicate it every asset. Going this route would help me in some of my assets - as Planet tends to have 5-8 assets that are all 3 or 4 band data, so it'd a lot of replicating the same band info in each asset. 

Sorry for the long message, just trying to think through all this together. I see two main options:

* Require eo bands at the asset level, as they are more useful there, to decrease the confusion as to where they put them and what exactly the property level implies for the assets. Only issue is it 'feels' a bit weird with summaries.
* Require eo bands at the property level, and bring back the asset reference array.

Thoughts from others? I'm sure there's other ideas than those two options, but those seem the best to me, and would give me a clear path of what to do.

**Comment by kylebarron** [comment]
> * Is band order implied?

I thought this was already implied by the spec but I agree since it's a list the order of `eo:bands` should definitely match the order of the bands within the asset.

> * What is 'name' vs 'common name'?

To me 'name' just refers to "any user-friendly name", whereas 'common name' gives band information in a much more developer-friendly way than parsing the `center_wavelength` and `full_width_half_max` manually.

> eo:bands reference array

I'm not opposed to the idea of a reference array. To me, it's not hard to check if the value is an integer, and if it is, grab its index from the item-level `eo:bands` object. Python pseudocode:

```py
item_bands = item['properties']['eo:bands']
asset_bands = item['assets'][asset_name]['eo:bands']
new_bands = []
for band in asset_bands:
	if type(band) == int:
		new_bands.append(item_bands[band])
	else:
		new_bands.append(band)

# use new_bands
```

> in a 'merging' paradigm

I don't quite understand what the merging support was, but I agree it doesn't sound necessary. 

> each item would need to list its full eo:bands object

That would just be `eo:bands: [2, 3, 4]`? That's so tiny I don't know why not to put that on every asset.

**Comment by cholmes** [comment]
>> Is band order implied?
> I thought this was already implied by the spec but I agree since it's a list the order of eo:bands should definitely match the order of the bands within the asset.

Yeah, I just want to make it explicit in the spec, and was asking to confirm.

> To me 'name' just refers to "any user-friendly name", whereas 'common name' gives band information in a much more developer-friendly way than parsing the center_wavelength and full_width_half_max manually.

Makes sense, it's like the 'title' - the thing that would be displayed in the UI? I can add a bit more language on the spec. Though hrm, if that's what it's for maybe we just use 'title', since that's what it is everywhere else in the spec.

>> each item would need to list its full eo:bands object

> That would just be eo:bands: [2, 3, 4]? That's so tiny I don't know why not to put that on every asset.

Sorry, I wasn't clear here. I was meaning if we didn't use the array thing then you'd need to list the full bands object each time. The array thing was the idea for the smaller thing that is much more reasonable to put on every asset. I agree the requirement if we went this route would be for each asset that has an eo band use the eo band reference object.

**Comment by m-mohr** [comment]
Yes, band order was meant to be implied. As name is not required (e.g. for hyperspectral), the order is actually important as otherwise you would have no clue at all.

We removed the band "indexes" due to the fact that it was error prone and (without software) easy to understand. We also found that duplication is not that big of a deal with assets that are often 1GB+, while the STAC item is just some kilobytes.

I don't think we had any merging in tooling. Most tooling did (mostly?) ignore eo:bands in assets, I think.

Common name is - as said - an easy way to get the right band in an interoperable way without needing to check wavelengths, proprietary band names etc. For us a very important aspect!

I'm pretty happy with how it works at the moment, but it likely needs better descriptions. eo:bands in properties if bands are the same across data assets. eo:bands in assets if bands are different across assets. (All per item) You can still duplicate in properties if you want to give an overview as the properties basically get "overruled" by the asset entries.

**Comment by cholmes** [comment]
> Yes, band order was meant to be implied. As name is not required (e.g. for hyperspectral), the order is actually important as otherwise you would have no clue at all.

Cool, I'll work to clarify the spec.

> Common name is - as said - an easy way to get the right band in an interoperable way without needing to check wavelengths, proprietary band names etc. For us a very important aspect!

Yeah, common name I get is super important. I question the value of 'name', that is similar but used 'however'? What do you think about calling it 'title'? Or does it serve other purposes than just display?

> I'm pretty happy with how it works at the moment, but it likely needs better descriptions. eo:bands in properties if bands are the same across data assets. eo:bands in assets if bands are different across assets. (All per item) You can still duplicate in properties if you want to give an overview as the properties basically get "overruled" by the asset entries.

Ok, I think this explanation is the key thing that I was missing, as it wasn't in the spec at all. I think if we just make this clear then it can be ok - I don't need to push for the indexes. Let me try to summarize in my own words:

* eo:bands in properties is the 'default' bands. If your assets all have the same bands just use this.
* if your bands across assets are different then just put eo:bands in assets. (recommendation to leave them off the properties?)
* If there is bands in properties and bands in an asset then the asset 'overrules' - clients should use the asset.

I think I like this, and it mostly works for me - the spec itself does not yet make clear the 'overruled'/default stuff. My use case is 5 assets with bgrn, 1 with rgb and 1 UDM ('qa') band. So it sounds like I can set bgrn in properties, and then it's the default for my 5 assets. My 1 rgb asset I should have a bands object with the proper order. 

I think the one question I have is with the UDM geotiff. It has 1 band, that is not bgrn. It seems like in the current scheme a client would reasonably assume on opening that geotiff that it uses the 'default' band order (bgrn in my case). And we don't have a 'QA' band (perhaps we should). But even if we had that particular QA band what if I have a geotiff of like land classification from ML in 3 'bands' (that aren't based on physical properties). 

It feels like we need a way to explicitly say 'I use the bands as described in properties'. Or else clients wouldn't know if a particular asset reflects that, or is just some other geotiff, or even something else entirely. Like how do you actually know that 'bands' applies to the asset. The 'index' would do this, but I get that it's overly complicated and duplication doesn't really matter. But it seems like just eo:bands=true or something at the asset level to indicate 'yes this asset is multiband data that is described by the 'default'. 

If this isn't clear let me know and I can prep some explicit examples and we can discuss on monday.

**Comment by kylebarron** [comment]
> I think I like this, and it mostly works for me - the spec itself does not yet make clear the 'overruled'/default stuff. My use case is 5 assets with bgrn, 1 with rgb and 1 UDM ('qa') band. So it sounds like I can set bgrn in properties, and then it's the default for my 5 assets. My 1 rgb asset I should have a bands object with the proper order.

One question with this: what happens if one of the assets has "unknown" bands? Then bands set Item-wide would need to be overruled to be "null". The asset could have an empty `"eo:bands": []`, but that could be interpreted as that asset having 0 bands? (Though that doesn't really make sense).

**Comment by m-mohr** [comment]
> Yeah, common name I get is super important. I question the value of 'name', that is similar but used 'however'? What do you think about calling it 'title'? Or does it serve other purposes than just display?

It's similar and we've discussed this before. Title is misleading as it's something human-readable usually ("Sentinel-10 launched"), but name (or maybe `id`) is better as it is more an identifier ("B01_NDVI"). I guess we also had a reason not to take id, but can't remember clearly. Anyway, this feels like bike-shedding and I wouldn't break things just for a name change here. I mean it's the name for the (provider-specific) band and common_name is commonly used name.



>     * eo:bands in properties is the 'default' bands. If your assets all have the same bands just use this.
> 
>     * if your bands across assets are different then just put eo:bands in assets. (recommendation to leave them off the properties?)
> 
>     * If there is bands in properties and bands in an asset then the asset 'overrules' - clients should use the asset.

To be clear: That is my just understanding and what I remember from the discussions. I'm not sure whether that is what we actually agreed on. Especially the overruling thing I'm not sure about.



> My use case is 5 assets with bgrn, 1 with rgb and 1 UDM ('qa') band. So it sounds like I can set bgrn in properties, and then it's the default for my 5 assets. My 1 rgb asset I should have a bands object with the proper order.

Sounds right, although I'm not sure we actually decided on the overruling or whether we agreed on just put all bands into assets in this case and don't specify in properties. @matthewhanson can you remember? Or did we actually agree that in properties you have the union of all unique bands and the order doesn't matter in this case? I think I remember something like that now...


> One question with this: what happens if one of the assets has "unknown" bands? Then bands set Item-wide would need to be overruled to be "null".

I'd say don't use item-wide bands in this case. But as said above, not sure about the overruling thing. Maybe it was actually the case that we agreed on that eo:bands in properties is always just a summary of the bands in the assets. Let's wait for @matthewhanson to sound in, maybe he can remember better. But the longer I'm thinking about it, the more I think it was the summary thing.

Then Chris' summary would be:

* eo:bands in properties (optionally) specifies the union of all bands available in assets as a set (i.e. unique values). If your assets all have the same bands just use this. No need to repeat in assets it applies to all if no asset has eo:bands.
* if your bands across assets are different then just put eo:bands in assets and summarize in properties.

**Comment by cholmes** [comment]
> > Yeah, common name I get is super important. I question the value of 'name', that is similar but used 'however'? What do you think about calling it 'title'? Or does it serve other purposes than just display?

> It's similar and we've discussed this before. Title is misleading as it's something human-readable usually ("Sentinel-10 launched"), but name (or maybe id) is better as it is more an identifier ("B01_NDVI"). I guess we also had a reason not to take id, but can't remember clearly. Anyway, this feels like bike-shedding and I wouldn't break things just for a name change here. I mean it's the name for the (provider-specific) band and common_name is commonly used name.

Cool, sorry for rehashing, that explanation makes sense. But I think we need to get better at explaining what we actually decided in the text. We just say The name of the band (e.g., "B01", "B02", "B1", "B5", "QA"). No guidance as to what this is for, that's why I brought it up (and is what leads to bike-shedding). I can't say I'm clear enough on what it is actually for with this explanation. It's like an id? It's what the provider names the band? In this case I'm the provider and we don't have strong 'names' for our bands, so I'm still not sure what I should put here, and how it will be used. Should I just not use it if the 'common_name' works for me?

> To be clear: That is my just understanding and what I remember from the discussions. I'm not sure whether that is what we actually agreed on. Especially the overruling thing I'm not sure about.

Cool, let's talk on monday. The overruling makes sense to me, but there was nothing in the spec clarifying either way. The union of unique bands makes some sense too. With my planet provider hat on the former is a bit better for me, but I think either is probably fine.

**Comment by cholmes** [comment]
Ok, I think we reached consensus on this. Summary is: 

* If you are using eo:bands then you must have at least one at the asset level. 
* eo:bands used in properties should be considered a 'summary' of what is in the assets. It should be the 'union' of all possible bands in assets.
* Thus you should not use eo:bands in properties unless there is at least one asset that has it.
* The 'name' field can be thought of as an optional 'id' - if the same band is represented more than once in multiple assets then they should all use the same 'name' (along with the rest of the fields). It is also what clients are recommended to display when representing a particular band.

So there is no over-ruling / default - everything must be explicitly set in an asset. There will be duplication in Items that have multiple assets with the same band order, and that is ok, as the size of the file is small, and as the ecosystem evolves most people should view using tools instead of reading json directly.
