### ISSUE TITLE
SAR backscatter measurement and convention

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#961]
> for the backscatter image assets (or as overall metadata), BackscatterMeasurement (should be gamma0 for CARD4L, but for other radar product, this can be sigma0, beta0 etc), and BackscatterConvention (amplitude or power, this is important!) should be defined. These two (and probably a few others) would make most sense to be included in the sar extension.

_Originally posted by @fangfy in https://github.com/radiantearth/stac-spec/issues/922#issuecomment-770502545_

Currently, values have the card4l prefix in the CARD4L SAR extension.

**Comment by m-mohr** [comment]
| Field Name                  | Type      | Description                                                  |
| --------------------------- | --------- | ------------------------------------------------------------ |
| sar:measurement_type         | string    | The product's type of measurement. One of `beta0`, `gamma0` or `sigma0`. |
| sar:measurment_convention          | string    | The measurement convention. One of `amplitude` (linear amplitude), `power` (linear power) or `angle`.  |

**Comment by m-mohr** [comment]
Additionally, it seems to be useful for have something like sar:pixel_spacing_row and sar:pixel_spacing_column...

**Comment by emmanuelmathot** [comment]
Like in my comment [here](https://github.com/radiantearth/stac-spec/pull/962#issuecomment-773564964), measurements conventions applied for SAR is valid for calibrated backscatter products (ARD)

**Comment by m-mohr** [comment]
Closing, no consensus found.
