### ISSUE TITLE
Create filtering extensions for the EO profile in the STAC API

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#97]
The core filters are just time and geometry. In the eo profile we can count on a few fields, with a number of optional ones that will often be used. We should define the filters that are used against them.

We might consider making more fields required, so we can count on more filters.

**Comment by matthewhanson** [comment]
Unless I'm misunderstanding this, I think this is already covered by the query API extension.

**Comment by m-mohr** [comment]
It is :-)
