### ISSUE TITLE
Better index.html for schemas.stacspec.org

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#983]
http://schemas.stacspec.org is a great resources to see the schemas, but at the root index there are no links. It'd be good to enable users to navigate down, instead of having to remember the structure. Can be a pretty simple html page, but should be a bit more than it is.

**Comment by matthewhanson** [comment]
See https://stac-extensions.github.io/sar/ for an example implementation

**Comment by m-mohr** [comment]
Seems to be done.
