### ISSUE TITLE
Rename 'scientific extension' to 'citation extension' 

### ISSUE THREAD

**Issue by tedhabermann** [radiantearth/stac-spec#990]
A name that reflects what is in this extension would be more appropriate. Maybe Citation extension.

**Comment by schwehr** [comment]
@tedhabermann, I don't know how this changes your thinking, but (Link Object)[https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md#link-object)  and (Provider Object)[https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object] are directly about connections.  

For Earth Engine, there are `source` and `cite-as` in the links:

```
  "links": [
    {
      "rel": "self",
      "href": "https://earthengine-stac.storage.googleapis.com/catalog/NOAA_GOES_16_FDCC.json"
    },
    {
      "rel": "parent",
      "href": "https://earthengine-stac.storage.googleapis.com/catalog/catalog.json"
    },
    {
      "rel": "root",
      "href": "https://earthengine-stac.storage.googleapis.com/catalog/catalog.json"
    },
    {
      "rel": "preview",
      "href": "https://mw1.google.com/ges/dd/images/NOAA_GOES_16_FDCC_sample.png"
    },
    {
      "rel": "license",
      "href": "https://developers.google.com/earth-engine/datasets/catalog/NOAA_GOES_16_FDCC#terms-of-use"
    },
    {
      "rel": "source",
      "href": "https://console.cloud.google.com/storage/browser/gcp-public-data-goes-16/ABI-L2-FDCC/"
    },
    {
      "rel": "cite-as",
      "href": "https://doi.org/10.1175/BAMS"
    }
  ],
```

And providers:

```JSON with comments
  "providers": [
    {
      "name": "NOAA",
      "roles": [
        "producer",
        "licensor"
      ],
      "url": "https://data.noaa.gov/dataset/dataset/noaa-goes-r-series-advanced-baseline-imager-abi-level-2-fire-hot-spot-characterization-fdc"
    },
    {
      "name": "Google Earth Engine",
      "roles": ["host"],
      "url": "https://developers.google.com/earth-engine/datasets/catalog/NOAA_GOES_16_FDCC"
    }
  ],
```

**Comment by matthewhanson** [comment]
I agree, `scientific` is a poor name. I can think of several other things a `scientific` extension might deal with but I'd be wrong.

`citation` is more descriptive, I would support a change here.

**Comment by cholmes** [comment]
I agree that citation is a bit more descriptive as to what this is. Changed the issue title to reflect it.

Do we think the prefix needs to change? Or do we keep `sci:`? 

My only hesitation is that in #946 we agreed to make scientific to be a 'core' extension. I don't think we should change the prefix right before deeming it stable. But if we just want to change the name of the extension I think that's ok. 

@m-mohr - any thought on this issue? As you're the owner of this extension.

**Comment by m-mohr** [comment]
The scientific extension was meant to evolve a bit over time so that other fields would be added. It never took place so now it is indeed not the best name.

I'd be fine with renaming it to a different name, but I guess changing the prefix is not ideal indeed.

What about simply renaming it to "Scientific Citation Extension" and leave everything as is?

**Comment by m-mohr** [comment]
I've created PR #1003 as a potential solution, let's discuss there.

**Comment by cholmes** [comment]
+1 to renaming as scientific citation extension.
