### ISSUE TITLE
Provider object needs an identifier

### ISSUE THREAD

**Issue by tedhabermann** [radiantearth/stac-spec#993]
Identifiers for organizations are becoming more and more important. Need one here. Might also consider a schema or type for the identifier, i.e. GRID, ROR, ISNI, ...

**Comment by m-mohr** [comment]
Could you give a use case where an identifier in addition to the name would be useful?

**Comment by m-mohr** [comment]
Seems stale, closing. Feel free to comment and we'll re-open.
