### ISSUE TITLE
alternate hrefs

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#997]
This has come up for Landsat Collection 2, and also discussed in #991 as a use case by @davidraleigh .   

For Collection 2 there is a the main URL which is a Cloudfront URL requiring authentication, but is backed by an object on s3. These are the URLs in the [Landsat STAC API](https://landsatlook.usgs.gov/sat-api/stac) (note this is an old version of STAC API). Bandwidth can be controlled by USGS this way, putting a control on egress costs.

Alternately, users can access the data directly through the bucket, which is requestor_pays, but you can't infer the bucket name and full path from the URL, you must know the bucket and the path prefix then can construct it. Less than ideal.

Another use case would be if you had a complete mirror of an archive and wanted to link to both from a single STAC catalog. The Sentinel-2 COGs are like this in that the Earth-search API points to the Sentinel-2 COGs in us-west-2, but all the scenes within African are replicated in the Cape Town region. 

It may be worth how to combine the proposed storage extension with the idea of having multiple representations.  Perhaps an `alternate_urls` field is an array of Objects where each element contains the `storage` fields.  This way you could have the href and also the s3 representation.  Perhaps we add an `href` field to the storage extension and have min requirement of 1 field, that way if your alternate hrefs were just URLs, this would be able to handle that too.

**Comment by cholmes** [comment]
Seems reasonable. I do wonder if there are different ways to model this - like instead of an alternate_urls field you list multiple assets, or you have two items. Though neither of those sound ideal - having it all represented as 'the same' makes a lot of sense.

Are you proposing this to just be in an extension, or something we want to try to get in for 1.0.0-RC1?

**Comment by m-mohr** [comment]
Has been published here: https://github.com/stac-extensions/alternate-assets
